### ISSUE TITLE
audio is not coming from earphone

### ISSUE THREAD

**Issue by rnqayush** [aws-samples/amazon-chime-react-native-demo#101]
Hi team, 
1- I have cloned this demo repo and noticed that audio was not coming from inbuilt speaker of phone nor from earphone. however I have used this library  https://github.com/divergent-thinking/react-native-switch-audio-output to solve this.
2- Now after using it audio is coming from loud speaker (inbuilt speaker) but not from earphone .
 
Kindly help me to resolve this issue

**Comment by zhinang-amazon** [comment]
Hi @rnqayush ,

I see that you have found #5 that has answer to how to switch audio using the device controller from our SDK. We do not support debugging with the usage of another library.
I will close this issue, and use #5 to answer your questions.

**Comment by rnqayush** [comment]
@zhinang-amazon , thanks for your response and have my apologies I will look onto it and will revert if i face any issue.
