### ISSUE TITLE
Video crash on android on react-native version 0.63.4

### ISSUE THREAD

**Issue by youssefhaitham-callvita** [aws-samples/amazon-chime-react-native-demo#103]
**Describe the bug**
As described in this [issue](https://github.com/aws-samples/amazon-chime-react-native-demo/issues/85) the video crashes in react-native version 0.63.4. But, when downgrading react-native version to 0.61.XX the video works fine. 

As stated in the issue above, one fix was to downgrade NDK, but this didn't solve the issue. 

Also downgrading the react-native is not an option as it crashes the application. I would like to ask how can I solve this issue and start having video on Android?

**Comment by hokyungh** [comment]
Will close this issue. Feel free to reopen if you still have issue.
