### ISSUE TITLE
Error when running React Native Demo (iOS)

### ISSUE THREAD

**Issue by vats05** [aws-samples/amazon-chime-react-native-demo#106]
Hi Team, 

Followed all the required steps to run the React Native Demo for iOS, but getting the below error: 

Can you please help. 

Xcode : 12.5 (M1 Chip)

<img width="1440" alt="Screenshot 2021-08-26 at 4 03 42 PM" src="https://user-images.githubusercontent.com/85572032/130952689-2dd9e31a-f4a0-4c66-80b5-d74c1c8e242e.png">

**Comment by khamisEDX** [comment]
I am having an issue also running the sample app
<img width="1393" alt="Screen Shot 2021-09-20 at 10 19 03 AM" src="https://user-images.githubusercontent.com/68809241/133967871-620220d1-7c0c-4ab0-8e1e-8284ed066048.png">

**Comment by khamisEDX** [comment]
> @ziyiz-amzn , waiting for the resolution here?

so any luck ? i am stuck with the ios

**Comment by khamisEDX** [comment]
so i fixed all the above issues and got this, app worked until you click button (start).
![simulator_screenshot_404C4304-E2D5-49DF-9C97-EF88998CDFEC](https://user-images.githubusercontent.com/68809241/134511757-9823d312-efaa-46df-8989-9d234d0bb3b7.png)
