### ISSUE TITLE
getting meeting response as undefined

### ISSUE THREAD

**Issue by ShaikAnsar1568** [aws-samples/amazon-chime-react-native-demo#108]
I successfully integrated the package and it is working fine for the first time. When i go back and come again to the same meeting after 5 minutes, iam getting meeting response "undefined" and iam not able to join the meeting again.

**Comment by hokyungh** [comment]
Hi this is the behavior fo the amazon chime meeting. If you look at [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end)
```
An Amazon Chime SDK meeting ends when you run the DeleteMeeting API action. Also, a meeting automatically ends after a period of inactivity, based on the following rules:

No audio connections are present in the meeting for more than five minutes.
Only one audio connection is present in the meeting for more than 30 minutes.
24 hours have elapsed since the meeting was created.
```

I think in your case, your meeting might not have anyone, so it automatically ended the meeting in five minutes.

**Comment by ShaikAnsar1568** [comment]
I agree with that. But when will I be able to join the same meeting again? I mean can we recreate the same meeting after how many hours?

**Comment by hokyungh** [comment]
Do you mind clarifying the term `same meeting`? 
If same meeting refers to meeting that has same name like `meeting1` and if you are using serverless demo, you will see that [code](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L300), you can join it after a day.

**Comment by hokyungh** [comment]
Closing the ticket since it is not related to mobile behavior.
