### ISSUE TITLE
Running amazon chime on android emulator

### ISSUE THREAD

**Issue by youssefhaitham-callvita** [aws-samples/amazon-chime-react-native-demo#110]
I integrated amazon chime with my application and it runs on physical devices only as described in the readme file, Is there a way to run it on an android emulator?

**Comment by youssefhaitham-callvita** [comment]
@zhinang-amazon Can you please help?

**Comment by linsang21** [comment]
Hi @youssefhaitham-callvita, currently there's no easy way to use an android emulator yet, sorry for the inconvenience. Is there any specific emulator you're hoping to use? I understand an emulator could be handy but for meeting experience a real physical device could cover more media usage. Also you could consider some remote physical devices with 3rd party vendor if you can't get access to a physical device.  

At the same time, I'll labeling this as a feature request.

**Comment by youssefhaitham-callvita** [comment]
> Hi @youssefhaitham-callvita, currently there's no easy way to use an android emulator yet, sorry for the inconvenience. Is there any specific emulator you're hoping to use? I understand an emulator could be handy but for meeting experience a real physical device could cover more media usage. Also you could consider some remote physical devices with 3rd party vendor if you can't get access to a physical device.
> 
> At the same time, I'll labeling this as a feature request.

Hello @linsang21, thank you for the response. Unfortunately, we need to run the app on android emulators as it is hard for the company to get physical devices for all employees. We don't need to test amazon chime on the emulator we just need to run the application to test other things. You wrote in the readMe file that I can run amazon chime on an ARM emulator, the problem is ARM emulators give errors when I try to run them. So any other option to run on an emulator ? 

Thank you.

**Comment by linsang21** [comment]
Unfortunately, there's not many workaround at this moment. We'll keep this thread updated once we have any new progress.

**Comment by reest** [comment]
+1 this issue. We are finding this to be a major blocker in integrating this solution

**Comment by hokyungh** [comment]
Closing it as duplicate and will track it in native https://github.com/aws/amazon-chime-sdk-android/issues/342
