### ISSUE TITLE
multiple tileId of single attendee after switching off and switching on my camera.

### ISSUE THREAD

**Issue by rnqayush** [aws-samples/amazon-chime-react-native-demo#112]
hi team, 
1-I have created a app for video meeting in which speaker gets to fullscreen if actively speaking else it will appear with small video tiles on bottom of screen.
2-firstly when two users enter in meeting the list of tileId to show is [1,0] and [0,2] respectively on their devices and due to active speaker tileId which is on fullscreen is "0" on device1 and "2" on device2.
3-now if device2 turns off its camera and then turns on again the tileId to show is getting [0,0,1] on device1 while [2,2,0] on device2.
4-and now if device1  turns off its camera and then turns on again the tileId to show is getting [1,1,0] on device1 and [0,0,2] on device2.

i also used chrome debug tools for it and noticed that if device1 is switching of its camera then firstly "MobileSDKEvent.OnRemoveVideoTile" callback is triggered then automatically "MobileSDKEvent.OnAddVideoTile" is getting triggered .

i am sharing my code below kindly suggest some idea to resolve to.

**Comment by YumTheDeathGod** [comment]
Hey @rnqayush ,
I have just started to implement active speaker video tile functionality into the react native application. But I am kind of stuck. Hope you can help me over here.

Basically my query is that whenever an active speaker's tile id changes then we have to unbind the video tile and again have to bind the other video tile. But I am not able to figure it out how do I do that. cause whenever I tried to render that active speaker's video gets render one time and whenever active speaker tile id is toggle the video gets blacken out.

Note: I have implemented same kind of logic to get tile ids of users as yours.
Thanks in an advance.
