### ISSUE TITLE
Messaging Components missing ins react native sdk

### ISSUE THREAD

**Issue by PaulGobin** [aws-samples/amazon-chime-react-native-demo#117]
The react native SDK does not have information regarding the messaging components. If you can please add the usage example in the demo app, similar to how the iOS, Android and JS demo app have it would be much appreciated.

**Expected behavior**
Sending and receiving messages such as Chat messages using the message components, not working.

related inquiry:
https://github.com/aws-samples/amazon-chime-react-native-demo/issues/50

**Comment by PaulGobin** [comment]
Thanks @linsang21 
I will keep an eye out for any updates.

**Comment by albrich-me** [comment]
@linsang21 other than the React Native Demo code are there any other resources that might help them sort out how to bridge RN to native API's for both iOS and Android?

**Comment by ziyiz-amzn** [comment]
@PaulGobin @albrich-me  Basically, we have 2 options. 

1. Our team is working on an implementation of messaging in RN via data message. Will update with you once complete.

2. You can build native messaging functionality using [AWS Chime SDK Messaging](https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations_Amazon_Chime_SDK_Messaging.html) for both [iOS](https://github.com/aws-amplify/aws-sdk-ios/tree/main/AWSChimeSDKMessaging) and [Android](https://github.com/aws-amplify/aws-sdk-android/tree/main/aws-android-sdk-chimesdkmessaging). There are 2 sample apps([iOS](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat-ios) and [Android](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat-android)) to demonstrate how to build apps using these 2 SDKs. Also, you can refer to the blog post [Build chat applications in iOS and Android with Amazon Chime SDK messaging](https://aws.amazon.com/blogs/business-productivity/build-chat-applications-in-ios-and-android-with-amazon-chime-sdk-messaging) to learn more.

**Comment by ziyiz-amzn** [comment]
Hi @PaulGobin @albrich-me [#120](https://github.com/aws-samples/amazon-chime-react-native-demo/pull/120) has been merged, could you try new master branch and see if data message works as expected?

**Comment by PaulGobin** [comment]
Thanks guys, much appreciated 
We will give it a shot.

Thank You
Paul Gobin
