### ISSUE TITLE
Attendees(tiles) video is not visible in ios device

### ISSUE THREAD

**Issue by chetangodiya-simformsolutions** [aws-samples/amazon-chime-react-native-demo#118]
**Describe the bug**
I am creating the streaming app i can see the other attendees(tiles) in android but not in ios 

**To Reproduce**
1. Go to - attend the meeting

**Expected behavior**
all other user tiles are visible in ios end

**Logs**
no logs 

**Screenshots**
no screenshot

**Test environment Info (please complete the following information):**
 - Device: iPhone 12 Pro Max (simulator)
 - OS: 14.4
 - Version amazon-chime-sdk: 0.18.0
 - Version amazon-chime-sdk-media: 0.14.0
 - Can you reproduce this in the demo app?- i haven't run demo app

**Comment by zhinang-amazon** [comment]
Hi @chetangodiya-simformsolutions,

Please try to run our RN demo app on iOS and see if you have the same issue.
It's difficult for us to investigate if the issue is only in your app. We would need a way to reproduce the issue on our side.

**Comment by chetangodiya-simformsolutions** [comment]
#import <AmazonChimeSDK/AmazonChimeSDK-Swift.h> error

![image](https://user-images.githubusercontent.com/63835578/147319621-ab45e458-a561-49a8-99c0-183710496005.png)

**Comment by chetangodiya-simformsolutions** [comment]
i run the demo project and it is not getting started in android end like when  i join the meeting the app gets crash

**Comment by chetangodiya-simformsolutions** [comment]
Since i have everything working fine on the android end there might be something wrong with ios latest release @zhinang-amazon

**Comment by ziyiz-amzn** [comment]
Have you tested with a physical iOS device?

**Comment by chetangodiya-simformsolutions** [comment]
yes,  found similar there too

**Comment by santthosh** [comment]
I had a similar issue, the buttons went invisible because of the RN image issue, this link fixed it for me https://stackoverflow.com/a/64495360/115278

**Comment by chetangodiya-simformsolutions** [comment]
> I had a similar issue, the buttons went invisible because of the RN image issue, this link fixed it for me https://stackoverflow.com/a/64495360/115278

it is not the similar issue i am facing
