### ISSUE TITLE
Video call crashes with the below reason on iOS [MeetingObservers videoTileSizeDidChangeWithTileState

### ISSUE THREAD

**Issue by jalajjha9** [aws-samples/amazon-chime-react-native-demo#12]
Below is the logs from xcode.

-[MeetingObservers videoTileSizeDidChangeWithTileState:]: unrecognized selector sent to instance 0x282d7e880
2020-08-17 21:42:50.621494+0530 eResearch[452:28325] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MeetingObservers videoTileSizeDidChangeWithTileState:]: unrecognized selector sent to instance 

Please can you help us on this , as we don't find this method mentioned anywhere in the sdk

**Comment by jalajjha9** [comment]
@weichenhamzn please can you help me with the above error

**Comment by hokyungh** [comment]
@jalajjha9 Could you see if this [PR](https://github.com/aws-samples/amazon-chime-react-native-demo/pull/13) fixes your issue?

**Comment by jalajjha9** [comment]
@hokyungh  Thank you. It is working now with the new pull request.
