### ISSUE TITLE
[React native] - Android The video is cropped when scalingType AspectFit

### ISSUE THREAD

**Issue by dhavalpanchani** [aws-samples/amazon-chime-react-native-demo#121]
The video is cropped when scalingType AspectFit property is not worked in android.

**Comment by dhavalpanchani** [comment]
![Screenshot 2022-01-06 at 7 28 33 PM](https://user-images.githubusercontent.com/25957550/148394048-b6ecb7b4-528f-40c0-b9f5-1d4f7ba13a19.png)

I have implemented code like this and using this property the video should be fit on the screen but it's not working like aspecting.

**Comment by hokyungh** [comment]
Sorry for late reply. Would you be able to have parent view on top of DefaultRenderView and set its scaling type such as following https://github.com/aws/amazon-chime-sdk-android/blob/master/app/src/main/java/com/amazonaws/services/chime/sdkdemo/adapter/VideoAdapter.kt#L50?

**Comment by dhavalpanchani** [comment]
@hokyungh Could you please provide example for that because I don't have much experience in native android developer So

**Comment by ashirkhan94** [comment]
> Sorry for late reply. Would you be able to have parent view on top of DefaultRenderView and set its scaling type such as following https://github.com/aws/amazon-chime-sdk-android/blob/master/app/src/main/java/com/amazonaws/services/chime/sdkdemo/adapter/VideoAdapter.kt#L50?

How to do it in react native demo app. thank you
