### ISSUE TITLE
How can we fetch the participants on active meeting 0r attendeId's on the meeting?

### ISSUE THREAD

**Issue by sthapa1** [aws-samples/amazon-chime-react-native-demo#124]
React Native Chime Demo is using externalUserId for handling the users information that is  joining to the meeting. I want to get all the references of attendees on the meeting.

**Comment by alnlau** [comment]
Hello,

The demo's event emitter is sending the `attendeeId` and `externalUserId` ([Android](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L37) [iOS](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/MeetingObservers.m#L27)). You can modify the [handler](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/containers/Meeting.js#L37) to do what you need with each participant's `attendeeId`. Let us know if you have further questions.
