### ISSUE TITLE
How can I map videoTile Ids with attendeeId? 

### ISSUE THREAD

**Issue by sthapa1** [aws-samples/amazon-chime-react-native-demo#126]
I can see videoTiles as [0,1,2] but I cannot map those Ids to particular attendeeId. Is there any method to achieve this?

**Comment by dylonChime** [comment]
Hi sthapa1,
When the PR above is merged, you can access AttendeeId from [OnAddVideoTile](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/232668d5909a8240f714b5a8bc2276fcf870cc8e/src/containers/Meeting.js#L75) callback using tileState.

**Comment by dylonChime** [comment]
I'll close this issue for now. Feel free to reopen if that didn't solve your problem.
