### ISSUE TITLE
Native SDKs versus Javascript SDK versus React Library

### ISSUE THREAD

**Issue by georgeflug** [aws-samples/amazon-chime-react-native-demo#128]
As a newcomer to Chime and React Native, I'm confused about whether I need to use the Native SDKs as demonstrated here or whether the [Javascript SDK](https://github.com/aws/amazon-chime-sdk-js/) or the [React Library](https://github.com/aws/amazon-chime-sdk-component-library-react) would be sufficient.

Do the javascript-based libraries work in React Native? If so, what is the difference between using those versus using the approach in this repo?

Thank you kindly.

**Comment by hokyungh** [comment]
> Do the javascript-based libraries work in React Native?

Hi [Javascript SDK](https://github.com/aws/amazon-chime-sdk-js/) or the [React Library](https://github.com/aws/amazon-chime-sdk-component-library-react) might not be fully compatible with React Native. 

It should be working if you use web-view though.

You might also want to check out [does it work with react native](https://reactnative.dev/docs/libraries#does-it-work-with-react-native).

> If so, what is the difference between using those versus using the approach in this repo?

This repo demonstrates using Native SDKs and porting it into react native. This will allow us to keep development in the Native SDK, and additionally support react native.

**Comment by georgeflug** [comment]
Thank you very much for explaining that. It makes sense to me now.
