### ISSUE TITLE
iOS-React-Native-Bridge for Broadcast-ScreenShare

### ISSUE THREAD

**Issue by saurabhghadi0401** [aws-samples/amazon-chime-react-native-demo#130]
Hello,

I am trying to create a bridge for entire screen share on Chime-React-Native-Demo, and have setup broadcast extension as per the guide (https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/content_share.md#device-level-screen-sharing). I create a custom-bridge to render **RPSystemBroadcastPickerView** in our code. But when I click it, it doesn't show me the app to broadcast it. 
![image](https://user-images.githubusercontent.com/62549260/156115200-4bb54b47-6b67-4dc0-8deb-d9c409a4efa5.png)
![image](https://user-images.githubusercontent.com/62549260/156116012-6f891410-51bb-45ac-9d1c-fae9685619bb.png)

![image](https://user-images.githubusercontent.com/62549260/156115960-2ba2cb29-566c-43a5-8251-adcfcc6848b5.png)

I tried to run chime native iOS code and it installed the extension, but when I tried to do the same on react-native side, it's not getting installed. is there any method I need to setup so that extension will get installed When I join the meeting? 
Kindly please suggest any way to install/invoke the extension.

Thanks,
Saurabh

**Comment by hokyungh** [comment]
It might be hard to help without what you have implemented. Based on the guide, device level screen share requires at least `Add App Groups Capability`, `RPSystemBroadcastPickerView`, `SampleHander`, `ReplayKitSource`. Do you have all the implementation?

**Comment by saurabhghadi0401** [comment]
I see in AWS-Chime-sdk-ios (https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingViewController.swift#:~:text=self%2C%20action%3A%20%23selector(-,broadcastButtonTapped,-)%2C%20for%3A%20.touchUpInside)) isBlocked property of BroadcastScreenCaptureModel is set and then it'll invoke **saveMeetingSessionConfigToUserDefaults** function to set appGroupUserDefaults values. 
Can I set those values when meetingSession is generated?

**Comment by saurabhghadi0401** [comment]
I configured **saveMeetingSessionConfigToUserDefaults**  function when meetingSession is created but it didn't show me the app in broadcast list. I checked the logs and saw this error log ->  ### Couldn't read values in CFPrefsPlistSource which means App extension is not getting installed right?
![image](https://user-images.githubusercontent.com/62549260/156356136-95727551-87e3-47f9-82d7-a1f812493ad7.png)

**Comment by saurabhghadi0401** [comment]
@hokyungh , I figured out the way to integrate screen-share in iOS.

**Comment by ziyiz-amzn** [comment]
@saurabhghadi0401 Glad to see you found the way. Feel free to share it in this thread, so that we may add it into our demo app. Closing this for now.
