### ISSUE TITLE
Receive the leave attendee and a few log lines later we get an add video

### ISSUE THREAD

**Issue by albrich-me** [aws-samples/amazon-chime-react-native-demo#135]
**Describe the bug**
We are facing an issue with Android mostly and very intermittent on iOS, please note that we are using React Native.

(Guys, please keep me honest here)
What’s happening is when an attendee leaves a meeting the attendee’s video tiles remains on the others screen and shows as blank—a blank video. The team traced it down and believe they found the culprit, I attached the details which we believe is causing the issue, and this issue correlates with the events below, whenever it happens.

Notice that we receive the leave attendee and a few log lines later we get an add video. Whenever this sequence occurs, we get the blank video issue.
However, when the “add video” event does not occur after the leave attendee (only the “leave event” occurs) then everything works great.

Please advise.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/72471320/158442480-8642bcc3-3677-49af-a7e7-747bed5f27d5.png">

**To Reproduce**

Join a meeting with 3 or more participants
Join with Android
Leave the meeting on Android
The meeting tile of the user that left stays on the screen as a blank tile.

**Expected behavior**

**Logs**
If applicable, add logs from logcat to help explain your problem.

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: [e.g. Pixel3]
 - OS: [e.g. Android 10]
 - Version amazon-chime-sdk: [e.g. 0.4.0]
 - Version amazon-chime-sdk-media: [e.g. 0.4.0]
 - Can you reproduce this in the demo app?

We are using the below version for Mobile (react-native)

Android—>
amazon-chime-sdk-0.14.0
amazon-chime-sdk-media-0.14.0

iOS—->
AmazonChimeSDK-0.18.0
AmazonChimeSDKMedia-0.14.0

If you are reporting a crash:
 - Please provide full crash logs.

**Additional context**

**Comment by alnlau** [comment]
Hello,

What triggers add video for an attendee in your app? I didn't notice anything about enabling video in the reproduce steps.

If the Android attendee is enabling video between joining and leaving, could you also add log statements on the Android side for `onAttendeesLeft` and `onVideoTileAdded`? I'd be interested in seeing if there's an issue with the ordering for observer methods on the Android SDK side or if something happened to the order when bridging to the JS side.
