### ISSUE TITLE
Strange behavior when connected on 4G (React Native)

### ISSUE THREAD

**Issue by PaulGobin** [aws-samples/amazon-chime-react-native-demo#137]
We are noticing some strange behavior in mobile app testing while on 4G. I’m attaching a screenshot below. We had 6 participants in this meeting and out that 3 are with video. We are continuously getting Add and Remove VideoTile events from web sockets. These participants are not even touching their phones or web portal. We have no clue why we are getting  these events in aws websocket. Based on these events video is automatically getting turned ON and OFF in our mobile app. 
 
We tested the same case connecting to wifi and we have no issues ( test ran for 45 min ). We were able to duplicate it when we switch back to 4G.

If the below React Native bridges can be implemented, I believe this should fix the issue.

```
override fun onConnectionBecamePoor() {
        // Not implemented for demo purposes
    }

    override fun onConnectionRecovered() {
        // Not implemented for demo purposes
    }

```

Thanks,
![image](https://user-images.githubusercontent.com/9370041/160197264-02c0a0e1-9d1f-44c3-a9ef-5e5d2199f184.png)

**Comment by ziyiz-amzn** [comment]
@PaulGobin Thanks for reporting. When these events happened, what is the content of these video tiles? Did the camera automatically turn on for these 3 attendees?

**Comment by netstratum-labs** [comment]
Out of those 3 participants, one is a publisher and other 2 are subscribers. Publisher's camera is turning on and off automatically. Subscribers video is missing in the view and appear after some time automatically.
