### ISSUE TITLE
amzon chime react native demo app not working on android device

### ISSUE THREAD

**Issue by kapilmyakal** [aws-samples/amazon-chime-react-native-demo#139]
**Describe the bug**
I am trying to Run the React Native Demo Application after clicking on start meeting not getting started , what should i do??
(isInMeeting not setting to true from chime sdk )

**Expected behavior**
after clicking on start button on login page it should launch meeting screen 

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: [e.g. Pixel 4a]
 - OS: [e.g. Android 12]
 - Version amazon-chime-sdk: [e.g. 0.15.0]
 - Version amazon-chime-sdk-media: [e.g. 0.15.0]
 - implementation 'software.aws.chimesdk:amazon-chime-sdk:0.15.0'
    implementation 'software.aws.chimesdk:amazon-chime-sdk-media:0.15.0'

 - Can you reproduce this in the demo app? yes
If you are reporting a crash:
 - Please provide full crash logs.

**Additional context**
we need to integrate chime sdk with existing react native app , getting error after adding kotlin step 3 and step 4

**Comment by hokyungh** [comment]
Hi could you tell us the behavior of what's happening? Does it give error message? Were you able to build and run with aar file? Did you set https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/utils/Api.js#L6?
