### ISSUE TITLE
Can not resize or stretch Video in react native 

### ISSUE THREAD

**Issue by Saifak34** [aws-samples/amazon-chime-react-native-demo#140]
**Describe the bug**
we are trying to resize Video which we are using via <RNVideoRenderView /> , when the other person in meeting starts their video it automatically leaves a lot of space around itself and that doesn't look good. IS there any way we can style these native components ?
![Screen Shot 2022-04-20 at 3 07 18 PM](https://user-images.githubusercontent.com/78328030/164304514-4722d2fc-7c40-4d1c-a1c9-a2711a128fcc.png)

**Comment by saurabhghadi0401** [comment]
@Saifak34 , Yes you can customize the styling of the video tile (RNVideoRenderView). You can wrap **RNVideoRenderView** in View component and provide styling to it. For reference, I will attach the code: 
```
<View
                  style={{
                    //   styles.localVideoContainer,
                    width: width * 0.2,
                    height: height * 0.15,
                    position: 'absolute',
                    bottom: 100,
                    right: 13,
                    overflow: 'hidden',
                    borderRadius: 12,
                    borderWidth: 1,
                    backgroundColor: 'black',
                    zIndex: 20000,
                  }}
                >
                  <RNVideoRenderView
                    key={this.state.localVideo.tileId}
                    tileId={this.state.localVideo.tileId}
                    style={styles.localVideo}
                  />
                </View>
```
width: screen width; height: screen height 
You can also customize the style of  **RNVideoRenderView**
```
localVideo: {
    width: "auto",
    height: "100%",
    resizeMode: "contain",
    borderRadius: 12,
    // margin: '1%',
    // aspectRatio: 16 / 9,
  },
```

**Comment by Saifak34** [comment]
Hello , 

thanks for the input, I do have a doubt about resizeMode working with <View /> ?

**Comment by Saifak34** [comment]
> @Saifak34 , Yes you can customize the styling of the video tile (RNVideoRenderView). You can wrap **RNVideoRenderView** in View component and provide styling to it. For reference, I will attach the code:
> 
> ```
> <View
>                   style={{
>                     //   styles.localVideoContainer,
>                     width: width * 0.2,
>                     height: height * 0.15,
>                     position: 'absolute',
>                     bottom: 100,
>                     right: 13,
>                     overflow: 'hidden',
>                     borderRadius: 12,
>                     borderWidth: 1,
>                     backgroundColor: 'black',
>                     zIndex: 20000,
>                   }}
>                 >
>                   <RNVideoRenderView
>                     key={this.state.localVideo.tileId}
>                     tileId={this.state.localVideo.tileId}
>                     style={styles.localVideo}
>                   />
>                 </View>
> ```
> 
> width: screen width; height: screen height You can also customize the style of **RNVideoRenderView**
> 
> ```
> localVideo: {
>     width: "auto",
>     height: "100%",
>     resizeMode: "contain",
>     borderRadius: 12,
>     // margin: '1%',
>     // aspectRatio: 16 / 9,
>   },
> ```

**Comment by Saifak34** [comment]
while w

> @Saifak34 , Yes you can customize the styling of the video tile (RNVideoRenderView). You can wrap **RNVideoRenderView** in View component and provide styling to it. For reference, I will attach the code:
> 
> ```
> <View
>                   style={{
>                     //   styles.localVideoContainer,
>                     width: width * 0.2,
>                     height: height * 0.15,
>                     position: 'absolute',
>                     bottom: 100,
>                     right: 13,
>                     overflow: 'hidden',
>                     borderRadius: 12,
>                     borderWidth: 1,
>                     backgroundColor: 'black',
>                     zIndex: 20000,
>                   }}
>                 >
>                   <RNVideoRenderView
>                     key={this.state.localVideo.tileId}
>                     tileId={this.state.localVideo.tileId}
>                     style={styles.localVideo}
>                   />
>                 </View>
> ```
> 
> width: screen width; height: screen height You can also customize the style of **RNVideoRenderView**
> 
> ```
> localVideo: {
>     width: "auto",
>     height: "100%",
>     resizeMode: "contain",
>     borderRadius: 12,
>     // margin: '1%',
>     // aspectRatio: 16 / 9,
>   },
> ```

when I try to wrap it in <View> I get this error , (screenshot)

code:

`video={ <View>
                         {<RNVideoRenderView style={styles.video}  tileId={this.state.localVideo.tileId}/> } </View>
                    }
                />`

**Comment by saurabhghadi0401** [comment]
You have enclosed RNVideoRenderView in {}.. remove those { }
