### ISSUE TITLE
Module 'AVFAudio' not found

### ISSUE THREAD

**Issue by wikramdas** [aws-samples/amazon-chime-react-native-demo#143]
I have followed all the steps as described in the documentation. I am 100% sure I did not miss anything but after compiling the code on xcode I am having this issues.
Module 'AVFAudio' not found in AmazonChimeSDK-Swift.h file
I have attached a screenshot

**Screenshots**
![Screenshot 2022-05-06 at 5 43 01 PM](https://user-images.githubusercontent.com/45879181/167133680-649e85be-a3b2-4a89-85c5-a2d14cfc5023.png)

 - Device: Xcode Version 12.4 (12D4e)
 - OS: iOS 11 Pro Max
 - Version amazon-chime-sdk: 0.19.4
 - Version amazon-chime-sdk-media: 0.15.4

**Comment by linsang21** [comment]
Hi @wikramdas, AVFAudio is a system framework, see [here](https://developer.apple.com/documentation/avfaudio). Could you check the if the framework is accessible from your environment?

**Comment by georgezy-amzn** [comment]
Hi @wikramdas, AVFAudio is only available on iOS 14.5+, you need Xcode 12.5+.
