### ISSUE TITLE
 Could not build module 'AmazonChimeSDK'

### ISSUE THREAD

**Issue by wikramdas** [aws-samples/amazon-chime-react-native-demo#144]
I have followed all the steps as described in the documentation. I am 100% sure I did not miss anything but after compiling the code on xCode I am having this issues.
Could not build module 'AmazonChimeSDK' in MeetingObserver.h

I have attached a screenshot
![Screenshot 2022-05-06 at 5 52 34 PM](https://user-images.githubusercontent.com/45879181/167135043-d1b54e5f-39da-4730-88e9-4a7992dfc34f.png)

- Device: Xcode Version 12.4 (12D4e)
 - OS: iOS 11 Pro Max
 - Version amazon-chime-sdk: 0.19.4
 - Version amazon-chime-sdk-media: 0.15.4

**Comment by ziyiz-amzn** [comment]
Thank you @wikramdas  for reporting this. We will verify the build/run steps with latest Chime iOS/Android SDKs and update.

**Comment by linsang21** [comment]
This is because of the AmazonChimeSDK model is not built successfully due to `AVFAudio` model can't be found. Let's track the issue in that one https://github.com/aws-samples/amazon-chime-react-native-demo/issues/143
