### ISSUE TITLE
Current demo fails to build in XCode 13.4 for iOS 15.5

### ISSUE THREAD

**Issue by SebassCoates** [aws-samples/amazon-chime-react-native-demo#146]
**Describe the bug**
Building for iOS 15.5 fails with XCode 13.4 after following instructions in repo.

**To Reproduce**
1. Clone repo
2. npm install
3. install pods
4. npm run ios

**Expected behavior**
Successful build

**Logs**
The following build commands failed:
	CompileC /Users/sebass/Library/Developer/Xcode/DerivedData/RNDemo-ftmaypgfvaiwpwbohgtbuwewmryd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ReactCommon.build/Objects-normal/x86_64/RCTTurboModuleManager.o /Users/sebass/newmuto/amazon-chime-react-native-demo/node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ReactCommon' from project 'Pods')
(1 failure)

I also see this message throughout
warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'React-Core' from project 'Pods')

**Test environment Info (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.5

**Additional context**
I'm trying to chase down a crash - want to be able to reproduce in the Demo but can't build. I've tried disabling Flipper and cleaning Pods cache / Derived Data.

**Comment by georgezy-amzn** [comment]
Hi @SebassCoates,
Thanks for reporting the issue, we'll look into it ASAP.

**Comment by hokyungh** [comment]
Could you try 
1. Clean in Xcode
2. Delete Derived Data
3. Clean Pods
4. Rerun?

**Comment by SebassCoates** [comment]
@hokyungh I cleaned in XCode, deleted all the directories in Derived Data, cleaned + reinstalled pods using the following commands (CocoaPods 1.11.3)
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

Re-running with npm run ios still results in a build error.

**Comment by hokyungh** [comment]
Thanks for reporting, could you try https://github.com/aws-samples/amazon-chime-react-native-demo/pull/148 for shorterm fix and see if it works?

**Comment by hokyungh** [comment]
For the crash, would you be able to open new issue with reproduction steps and logs?

**Comment by hokyungh** [comment]
Feel free to open new issue if you find any problem.
