### ISSUE TITLE
AmazonChimeSDK.MediaErrorCode=1

### ISSUE THREAD

**Issue by anoop-sharma** [aws-samples/amazon-chime-react-native-demo#15]
![img_4082](https://user-images.githubusercontent.com/11596072/91629163-19082180-e9e4-11ea-991d-40290ab699da.png)

I am getting above error on starting meeting. Tried to search for the issue but nothing found. The application is asking for permission of camera and microphone. After this I get this error.

Version of Amazon Chime SDK 0.8.2
Version of Amazon Chime Media SDK 0.6.1
Version of React Native 0.63.2

**Comment by hokyungh** [comment]
Thank you for reporting. Do you mind pasting full logs?

**Comment by anoop-sharma** [comment]
> Thank you for reporting. Do you mind pasting full logs?

Okay will share the full logs.

**Comment by linsang21** [comment]
Hey, just want to check if you got change to repro and share the log? Is the issue still ongoing?

**Comment by anoop-sharma** [comment]
> Hey, just want to check if you got change to repro and share the log? Is the issue still ongoing?

Apology I forgot to update the issue. The reason we were getting error because we have not implemented videoTileSizeDidChangeWithTileState method in MeetingObservers.m

After adding it the issue is resolved.
