### ISSUE TITLE
Unable to set the RNVideoView for Opposite user

### ISSUE THREAD

**Issue by knvsshetty** [aws-samples/amazon-chime-react-native-demo#150]
How to separate the user & opposite user RNVideoView Styles in amazon-chime-react-native.I tried using

this.state={selfVideoEnabled:false,videoTiles:[]

}
 {this.state.videoTiles.length > 0 ? (
            this.state.videoTiles.map((tileId) => (
              <>
//for self user
{ tileId == 0 && this.state.selfVideoEnabled &&
    <RNVideoRenderView
       key={tileId}
       tileId={tileId}
    />
}
//for opposite user
{  tileId == 2  &&
              
     <RNVideoRenderView
         key={tileId}
         tileId={tileId}
/>}
</>
            )))
: 
(<View />
          )}

i console tileid array also it giving initially [0,2] then after switching the video button multiple times its giving array as [0,2,2,2,2,2,0] etc. Can u please update on this issue

**Comment by hokyungh** [comment]
Hi sorry for late reply, is it the `videoTiles` that contains duplicates?

**Comment by linsang21** [comment]
Resolve for no response, please let us know if you still encounter the same issue with more information.
