### ISSUE TITLE
Sample project not runing

### ISSUE THREAD

**Issue by vikramsinghrajpoot** [aws-samples/amazon-chime-react-native-demo#155]
**Describe the bug**
After git clone
npm install
try to run app using npx react-native run-ios
giving following error

<img width="397" alt="Screenshot 2022-08-07 at 11 37 17 PM" src="https://user-images.githubusercontent.com/19968326/183304959-f37daf3f-4d54-4eb5-8f07-2d91ab4ab382.png">

**Comment by georgezy-amzn** [comment]
Hi @vikramsinghrajpoot,

I'm able to run the app. The error indicates `Api.js` is missing from `./src/utils/Api.js`, please make sure the file is there with the correct file permission, and configured properly as instructed in `README`.

**Comment by vikramsinghrajpoot** [comment]
there is no change in path just i have downloaded and try to run i
<img width="314" alt="Screenshot 2022-08-08 at 10 09 32 PM" src="https://user-images.githubusercontent.com/19968326/183468988-51f0972b-de97-44e4-bb9b-c6b2fc531550.png">
t

**Comment by georgezy-amzn** [comment]
how about the permissions?

**Comment by georgezy-amzn** [comment]
Please follow this [step](https://github.com/aws-samples/amazon-chime-react-native-demo#ios-1) for iOS instead of using `npx react-native run-ios`, as instructed in README.
