### ISSUE TITLE
Can't able to switch audio devices, like speaker to earpiece and vice versa

### ISSUE THREAD

**Issue by ashirkhanpm** [aws-samples/amazon-chime-react-native-demo#158]
Hi,
How can I switch to the specific audio device [bluetooth/earpiece/speaker/headset], when using the demo app ,
found something similar on #93 , but it's only connecting to a recently connected device

**Comment by ashirkhanpm** [comment]
Hi,
 @ziyiz-amzn thanks for your replay, and I already tried with the chooseAudioDevice and listAudioDevices, but IOS app getting crashed when trying 
 
 `RCT_EXPORT_METHOD(switchToEarPice){
  NSArray<MediaDevice *> *AudioDevices=[meetingSession.audioVideo listAudioDevices];
  NSString *dictionaryKey = @"type";
  NSPredicate *predicate = [NSPredicate predicateWithFormat:@"%K MATCHES %@",dictionaryKey,MediaDeviceTypeAudioHandset];
  NSArray *results= [AudioDevices filteredArrayUsingPredicate:predicate];
  [meetingSession.audioVideo chooseAudioDeviceWithMediaDevice:results[0]];
NSLog(@"test-Audio-list earpice %@",results );
}`
 
 this is my code

**Comment by ziyiz-amzn** [comment]
I think it is the correct approach. You will need to debug the result you get from `meetingSession.audioVideo.listAudioDevices()` and then see if the filter you implement works. Any error reported before the crash?

**Comment by ashirkhanpm** [comment]
@ziyiz-amzn  I think the issue in the filtering

**Comment by ashirkhanpm** [comment]
<img width="998" alt="Screenshot 2022-09-17 at 7 25 30 PM" src="https://user-images.githubusercontent.com/91265849/190860651-16c925a5-34aa-422f-adff-40b3f510930b.png">
I got this error when i call the switchToEarPice method

**Comment by ziyiz-amzn** [comment]
does it work without the filter? is it contains the list of all devices ?

**Comment by ashirkhanpm** [comment]
@ziyiz-amzn 
yes, it work without filter

**Comment by ziyiz-amzn** [comment]
Then you may need to debug your filters.
