### ISSUE TITLE
Android - incorrect camera behavior

### ISSUE THREAD

**Issue by alexbutovv** [aws-samples/amazon-chime-react-native-demo#162]
**Describe the bug**
There are several cases where the camera behaves strangely

User1 - connect from web
User2 - connect from android mobile device 

1) If the User1 has already connected and turned on the camera (the listener sees that there is a connection), then it will not be displayed on the User2 side until the camera on the User2 side is turned on
2) Only the User1 camera is displayed BUT the User2 camera has active status (steps described below)
3) Displays a black background when the User2 camera is enabled

**To Reproduce**
--------------------
First bug: 
1. start a session with the camera turned on by the User1
--------------------
Second bug:
1. start a session with the camera turned on by the User1
2. enable User2 camera
3. Turn off the camera on the User1 side
4. Turn on the camera on the User1 side
--------------------
Third bug
1. start a session without the camera turned on by the User1
2. enable user User2

**Expected behavior**
First bug - User1 video is displayed
Second bug - App displays both enabled cameras (both User1 and User2)
Third bug - All interface elements are displayed without blackout

**Screenshots**
Our design:
![Screenshot 2022-10-13 at 16 05 22](https://user-images.githubusercontent.com/115708358/195592529-ca5090ce-237f-4cc7-9019-edd0c8c1ea49.png)
Third bug:
![image-20220908-161415](https://user-images.githubusercontent.com/115708358/195591212-aef1c6fb-309c-4d8b-bd7d-bd467518ba55.png)

**Test environment Info:**
 - Device: any android device
 - OS: Android
 - Version amazon-chime-sdk: [0.17.5]
 - Version amazon-chime-sdk-media: [0.17.6]

**Comment by ethanjanadrake** [comment]
Hi @alexbutovv,
We cannot reproduce this issue on our demo app. It looks possible that you may need to call `meetingSession.audioVideo.startRemoteVideo()`. Are you doing that already?

**Comment by alexbutovv** [comment]
Hey @ethanjanadrake, thanks for your answer!

Of course, this method was used in our app.
I didn't change anything from demo app when I integrated code except UI and added a couple of new methods like `switchCamera` and `chooseAudioDevice` from guide.

**Comment by ethanjanadrake** [comment]
Hi @alexbutovv,
It might be an issue with binding logic, then. How are you binding the tile? In particular, how are you using `bindVideoView`?

**Comment by alexbutovv** [comment]
Hi @ethanjanadrake 

As I mentioned before I just reused logic from rn demo code

```
export class RNVideoRenderView extends React.Component {
  componentDidMount() {
    // we need to delay the bind video
    // Because "componentDidMount" will be called "immediately after the initial rendering occurs"
    // This is *before* RCTUIManager add this view to register (so that viewForReactTag() can return a view)
    // So we need to dispatch bindVideoView after this function complete
    setTimeout(() => {
      NativeFunction.bindVideoView(findNodeHandle(this), this.props.tileId)
    })
  }

  componentWillUnmount() {
    NativeFunction.unbindVideoView(this.props.tileId)
  }

  render() {
    return <RNVideoRenderViewNative {...this.props} />
  }
}

const RNVideoRenderViewNative = requireNativeComponent('RNVideoView', RNVideoRenderView)
```

And use it in our screen component

```
<RNVideoRenderView
            key={tileId}
            tileId={tileId}
            style={styles.getVideoStyle(tileId)}
/>
```

That's it)

**Comment by alexbutovv** [comment]
any updates here? still have a problems with android

**Comment by bedzhanyan** [comment]
We still look forward to getting an update on this ticket. Please assist.
