### ISSUE TITLE
Firefox with slow internet connection is causing Screenshare to freeze instantly (reproducible)

### ISSUE THREAD

**Issue by codingyourlife** [aws-samples/amazon-chime-react-native-demo#165]
**Describe the bug**
When I am on slow internet and I use latest Firefox (107.0.1) and I do a Screenshare (yes that simple) the Screenshare is instantly frozen. I have about 10Mbit Down and 1Mbit Up.

**To Reproduce**
1. Go to chime meeting (2+ people in the room)
2. Click on screenshare
3. Other person sees stuck screenshare

**Expected behavior**
Screenshare reduces quality, camera turns off everything so screenshare is working. In Google Meets it just works.

**Test environment Info (please complete the following information):**
 - Device: Macbook Air M1 2020
 - OS: macOS Ventura 13.0.1
 - Version amazon-chime-sdk: 3.6.0 (just realized there is a newer version that is not default here on github)
 - Can you reproduce this in the demo app?
Yes everything default and freshly deployed with SAM

**Additional context**
Google meets works, other video applications also have problems but Firefox is still very common and screenshare should always work at least in low quality.

**Comment by dylonChime** [comment]
Hi @codingyourlife,

Thanks for reporting this issue. I have a few questions that will help us investigate.

What is your use case? Have you tried using the [Amazon Chime JS SDK](https://github.com/aws/amazon-chime-sdk-js)? You may find better screenshare performance there.

You mentioned the other person sees stuck screenshare. Does the sender see a stuck screenshare as well?

What environment are the sender and receiver on? Are they both on Firefox using the Amazon Chime React Native demo with no other modifications?

What steps did you take after starting the RN development server with `npm start`?

**Comment by georgezy-amzn** [comment]
Close due to stale, feel free to reopen if issue still exists.
