### ISSUE TITLE
Meeting Audio disconnect issue when end an external phone call

### ISSUE THREAD

**Issue by ashirkhan94** [aws-samples/amazon-chime-react-native-demo#166]
For handling external phone call we are using `react-native-callkeep` library, and we successfully hold the meeting and accept the phone call, but after some time the meeting attendee leave from the remote side automatically and trigger the `- (void)audioSessionDidStopWithStatusWithSessionStatus:(MeetingSessionStatus * _Nonnull)sessionStatus;` at our side(mobile user side) with status code `78`
how to reconnect the audio session when getting sessionStatus code `78`,
Got the same issue when we end the external phone call at caller side.

**Test environment Info**

- Device: iPhone 7
- OS: iOS 15.6.1
- Version amazon-chime-sdk: 0.22.3
- Version amazon-chime-sdk-media: 0.17.7

**Comment by georgezy-amzn** [comment]
Hi @ashirkhan94,

`78` means unknown error. you may need to increase the log level for the detail. For reconnecting, are you able to start the session again with the same meeting configuration?

**Comment by ashirkhan94** [comment]
Hi @georgezy-amzn 
yes I can able to start the session again with the same meeting configuration, but after start the meeting session we are getting the `OnMeetingEnd` event from SDK side
Why this happening

**Comment by ashirkhan94** [comment]
Hi,
Any update

**Comment by hokyungh** [comment]
Hi @ashirkhan94 sorry for late response. I might have two questions. 
1. How long were you on the call?
2. How many attendees were in the meeting?

Meeting ended automatically if there is not enough attendee, so wanted to make sure if that's the case.
```
An Amazon Chime SDK meeting ends when you invoke the [DeleteMeeting](https://docs.aws.amazon.com/chime/latest/APIReference/API_DeleteMeeting.html) API action.

Also, a meeting automatically ends after a period of inactivity, based on the following rules:

For [Amazon Chime SDK](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_Operations_Amazon_Chime_SDK_Meetings.html) namespace:

No audio connections are present in the meeting for more than five minutes.
24 hours have elapsed since the meeting was created.
For [Amazon Chime](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_Operations_Amazon_Chime.html) namespace:

No audio connections are present in the meeting for more than five minutes.
Only one audio connection is present in the meeting for more than 30 minutes.
24 hours have elapsed since the meeting was created.
```

**Comment by ashirkhan94** [comment]
Hi @hokyungh 
there were 3 attendees in each meetings, and meeting duration is below 1 minute.
and the `OnMeetingEnd` event is coming with error `error: audioFailedToStart`
how to solve this issue

**Comment by ashirkhan94** [comment]
Hi @hokyungh 
Any update

**Comment by ashirkhan94** [comment]
> Hi @hokyungh there were 3 attendees in each meetings, and meeting duration is below 2 minute. and the `OnMeetingEnd` event is coming with error `error: audioFailedToStart` how to solve this issue

Hi Team 
Any solution for this
