### ISSUE TITLE
How to add CallKit in React native demo app

### ISSUE THREAD

**Issue by ashirkhan94** [aws-samples/amazon-chime-react-native-demo#168]
Hi,
what is the syntax for `AudioVideo.start(callKitEnabled: isCallKitEnabled)` in Objective C, and where can i add this line in bridge File

**Comment by georgezy-amzn** [comment]
Obj-C syntax:
`BOOL started = [meetingSession.audioVideo startWithCallKitEnabled:isCallKitEnabled error:&error];`

You can replace it [here](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/NativeMobileSDKBridge.m#L202).
