### ISSUE TITLE
How we can use sendDataMessage to send a data message to all attendees ?

### ISSUE THREAD

**Issue by Saifak34** [aws-samples/amazon-chime-react-native-demo#169]
**Describe the bug**
This is not a bug but a help request, how we can send data messages in react-native application? do we need to add extra native code in kotlin and C# ? or we can just add it in Bridge.js as a Native function and use it ?

How to use [DataMessageObserver](https://aws.github.io/amazon-chime-sdk-ios/Protocols/DataMessageObserver.html) observer to receive messages ?

why we are triggering NativeFunction.sendDataMessage(dataMessage.topic, str, 1000); while subscribing

```
const onDataMessageReceivedSubscription = getSDKEventEmitter().addListener(
             MobileSDKEvent.OnDataMessageReceive, 
            (dataMessage) => {
            const str = `Received Data message (topic: ${dataMessage.topic}) ${dataMessage.data} from ${dataMessage.senderAttendeeId}:${dataMessage.senderExternalUserId} at ${dataMessage.timestampMs} throttled: ${dataMessage.throttled}`;
            console.log('received',dataMessage);
            NativeFunction.sendDataMessage(dataMessage.topic, str, 1000);
          })

```

**Comment by georgezy-amzn** [comment]
Hi @Saifak34,

As long as all attendees are subscribed to the same topic, they will be able to receive messages from this topic. 

Please follow this [commit](https://github.com/aws-samples/amazon-chime-react-native-demo/commit/232668d5909a8240f714b5a8bc2276fcf870cc8e#diff-507328caaa4c633907645ed5c210987ee518742d3590e75f6a02723fca11ecaf) for using [DataMessageObserver](https://aws.github.io/amazon-chime-sdk-ios/Protocols/DataMessageObserver.html).

`NativeFunction.sendDataMessage` in the code snippet is just for demo purpose, don't worry about it.
