### ISSUE TITLE
Issue: New NativeEventEmitter requires a non-null argument

### ISSUE THREAD

**Issue by sambeetsahu** [aws-samples/amazon-chime-react-native-demo#172]
**Describe the bug**

Getting issue while following the steps what was mentioned on the readme file for ios app chime integration. I copy the files that are required for bridging in my ios folder. And added the permission info.plist and as well as added the line   pod 'AmazonChimeSDK-Bitcode', '0.19.1' to pod file as well but while running the app and loading the screen its hows New NativeEventEmmiter requires a non-null argument error as shown in the image 

![Simulator Screen Shot - iPhone 13 - 2023-01-19 at 19 25 40](https://user-images.githubusercontent.com/89605585/213462044-81c328fd-854f-4fe0-a118-5f9cea7f4e67.png)

**Additional context**
I run this demo repo and its working fine only while implementing in my project giving error. The version of react and react studio is same as in the demo app ..

Please help me resolving the issue please

**Comment by hokyungh** [comment]
Hi do you mind providing minimal repo that causes this issue since you said demo is working, but not your project, it might be some dependencies.

**Comment by sambeetsahu** [comment]
Hi @hokyungh here is the url https://github.com/sambeetsahu/ioschime

**Comment by hokyungh** [comment]
Hi @sambeetsahu , I have looked at the code and it seems that you did not add m and h files to xcode project. See the [code](https://github.com/sambeetsahu/ioschime/blob/main/ios/awschime.xcodeproj/project.pbxproj#L33) you have vs [our code](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo.xcodeproj/project.pbxproj#L19). Try to open Xcode project and add this file.

**Comment by hokyungh** [comment]
Feel free to reopen if you still have issue after adding files.

**Comment by sambeetsahu** [comment]
> Hi @sambeetsahu , I have looked at the code and it seems that you did not add m and h files to xcode project. See the [code](https://github.com/sambeetsahu/ioschime/blob/main/ios/awschime.xcodeproj/project.pbxproj#L33) you have vs [our code](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo.xcodeproj/project.pbxproj#L19). Try to open Xcode project and add these files.

Hi @hokyungh i have copy and paste the .m file and .h file to the ios folder directly.. becuse of that i guess the refrrence of the file is nit showing as u highlighted in that file m and h files are missing 


Can you please guide me the steps to create this m and h files in xcode .. that will be helpfull

**Comment by sambeetsahu** [comment]
Thanks @hokyungh finally it got resolved.

**Comment by yashukla47** [comment]
Hey @sambeetsahu how did you resolve it?

**Comment by sambeetsahu** [comment]
@yashukla47  I am guessing u are also doing the same thing like copy and paste the file directly in to the ios folder.
if you do like this then the file reference will not added as mentioned above in message thread. 
So you need to create first header file and empty file for (.m file) inside the ios/your project folder for header file and .m file
