### ISSUE TITLE
Screen Sharing, Meeting Recording and Background for react native

### ISSUE THREAD

**Issue by AliBaig-xD** [aws-samples/amazon-chime-react-native-demo#177]
Hi, I am fairly new to native programming and have been struggling on implementing the screen sharing, meeting recording and background changing feature in my react native app. I have integrated the sdk and is working for audio/video calls and texts but the example source code has no implementation of the mentioned features. Any help would be appreciated.

**Comment by equilizer** [comment]
Please update if you have found any solution regarding screen sharing @AliBaig-xD

**Comment by linsang21** [comment]
Hi @AliBaig-xD, @equilizer, thanks for reaching out. Our RN sample app covers the basic functionalities with mobile SDKs to demonstrate the idea / structure on how RN customer can use them. However we don't have cadence to demonstrate all features at this time, I'm adding this as a feature request. 

If it helps, you can take a look at the related guide on the Android / iOS SDK repo:
* https://github.com/aws/amazon-chime-sdk-android/tree/master/guides
* https://github.com/aws/amazon-chime-sdk-ios/tree/master/guides

**Comment by equilizer** [comment]
Found a way to implement screen share on Android using Amazon chime SDK.

**Comment by Aastikraj233k** [comment]
> Found a way to implement screen share on Android using Amazon chime SDK.

Found it ??

**Comment by equilizer** [comment]
yes. Its working!

**Comment by Doma-byte** [comment]
> yes. Its working!

Dude, can you help ?? How did you do it? and does it work on both android and ios??
