### ISSUE TITLE
Unable to modify render view when width is increased the render view is zoomed in

### ISSUE THREAD

**Issue by sridharvthink** [aws-samples/amazon-chime-react-native-demo#180]
**We are trying to make render view width is double of height but it getting zoomed in**

**To Reproduce**
1. Increase the width as double of height

**Expected behavior**
It should be ad default view instead of zoomed in

**Screenshots**

**Test environment Info (please complete the following information):**
All devices

**Comment by ethanjanadrake** [comment]
When you say it is getting zoomed in do you mean:
1. A portion of the frame is being enlarged to fit the width
2. The resolution is blurry

If it is the first one, have you tried [this](https://developer.apple.com/documentation/uikit/uiview/contentmode/scaleaspectfit)?

**Comment by hokyungh** [comment]
Closing due to no response feel free to reopen if you still have issue.
