### ISSUE TITLE
How to record aws chime videos 

### ISSUE THREAD

**Issue by sambeetsahu** [aws-samples/amazon-chime-react-native-demo#181]
I looking for record the meetings

I have used the react native chime in my app. Please let me know is there is possibility to record the meeting using the app

**Comment by hokyungh** [comment]
Hi have you tried [media-capture-pipelines](https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/) and see if it suits your need?
