### ISSUE TITLE
React native live transcription for multiple languages

### ISSUE THREAD

**Issue by salimkt** [aws-samples/amazon-chime-react-native-demo#186]
**Issue**
I am looking behind an issue for transcribing the voice into multiple languages as user preference. We tried the workflow as suggested here

[https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-transcribe-streaming/](url)

But it gets loss the audio stream data into an empty string after PCM encoding step. similar with below issue

https://github.com/aws-amplify/amplify-js/issues/6404

We tested alot of npm packages and non npm packages but no change in output.

 
**Solution needed**
As amazon chime provides the facility for transcription there should add the facility to transcript multiple languages . Otherwise we needs proper dierection to use above package in react native.

Any helps would be appreciated.

**Comment by dylonChime** [comment]
Hi @salimkt,
Thanks for your interest. See if the conversation from #184 helps you. I'll close this in favor of that feature request.

**Comment by salimkt** [comment]
Thanks @dylonChime
