### ISSUE TITLE
Camera preview tile

### ISSUE THREAD

**Issue by revin122** [aws-samples/amazon-chime-react-native-demo#19]
Hello,

I was able to follow the steps to build and run the application. I was able to see the other users in the meeting in the app but I can't see a preview of my own camera. I checked the event 'MobileSDKEvent.OnAddVideoTile' and I saw that it was being called as intended when I press the camera button. It was something like {...tileId: 0}. The other users can see me but I can't see myself.

I tried to create my own preview by using RNCamera but then what happens is that RNCamera gets the camera usage and the other users will just get a blank screen from my tile.

Any suggestions on how to implement this?

**Comment by LilianAlvarez123** [comment]
Hello @revin122,

I get the same issue as you did. How did you fix it please ?

Best regards,
Lilian.

**Comment by chetangodiya-simformsolutions** [comment]
Hello @revin122  

have you solved this issue? if yes then can you please share this 

Best regards,
Chetan.
