### ISSUE TITLE
RNVideoRenderView ui issue in ios, not same in android and ios both

### ISSUE THREAD

**Issue by AbhishekSri979** [aws-samples/amazon-chime-react-native-demo#197]
I am using RNVideoRenderView to render video tile in IOS and Android both.
Problem is that: In the android working fine it means ui is properly visible with proper height and width but in the IOS ui get disturb, also when i try to apply borderRadius in these tiles but not working.

here is my code written in react native JS

const renderTilesView = ()=>{
    return (
        <View style={{
            width: '100%',
            height: '100%',
        }}>
             <RNVideoRenderView style={[ height: '100%', width: '100%',borderRadius: 6,} key={data?.tileId} tileId={data?.tileId} mirror={true} />
        </View>
    )
};

please check the screenshot and give me some solution to resolve this issue in ios

IOS:

![IMG_0203](https://github.com/aws-samples/amazon-chime-react-native-demo/assets/144427339/98f8374a-b80b-49f7-ad06-0faf7d5b6595)

Android:

![MicrosoftTeams-image](https://github.com/aws-samples/amazon-chime-react-native-demo/assets/144427339/b03640bd-0878-4a9b-869f-26e3e5e47b14)

**Comment by ashirkhan94** [comment]
Hi @AbhishekSri979 
Try to use ` borderRadius: 6` and `overflow: 'hidden'` for the parent `View` of `RNVideoRenderView`
Like
```
<View style={{
width: '100%',
height: '100%',
borderRadius: 6,
overflow: 'hidden'
}}>
<RNVideoRenderView style={[ height: '100%', width: '100%',} key={data?.tileId} tileId={data?.tileId} mirror={true} />
</View>
```
pls try

**Comment by AbhishekSri979** [comment]
Hi @ashirkhan94 
Thanks for the comment and solution border radius issue has been resolved now.
But one another problem is still exist that is in the IOS, i am not able to manage height and width of video tiles, it is visible different in android and IOS both, you can check attached screenshot, in the android it is working fine but getting problem in the ios, when i try to adjust same height and width as in the android but it is not working fine, so can you tell me what will be the reason and how to resolve this

**Comment by ashirkhan94** [comment]
Hi @AbhishekSri979 
for resizing video, you can use UIViewContentMode for ios, dont know how to implement it on ios
there is one code sample for android [https://github.com/aws-samples/amazon-chime-react-native-demo/issues/121#issuecomment-1006616997](url)
pls check, it may help you

**Comment by ashirkhan94** [comment]
Hi @AbhishekSri979 
or Pls Try
`UIViewContentModeScaleAspectFill` instead of `UIViewContentModeScaleAspectFit`
in `RNVideoViewManager.m` file

```
#import "RNVideoViewManager.h"

@implementation RNVideoViewManager
static NSMutableDictionary<NSString*, NSValue*> *videoMap;

RCT_EXPORT_MODULE(RNVideoView);

- (UIView *)view
{
  DefaultVideoRenderView *innerView = [[DefaultVideoRenderView alloc] init];
  innerView.contentMode = UIViewContentModeScaleAspectFill;
  return innerView;
}

@end
```

**Comment by AbhishekSri979** [comment]
Hi @ashirkhan94 

Thanks a lot @ashirkhan94.  It is working fine now
