### ISSUE TITLE
Some Video tiles randomly freeze

### ISSUE THREAD

**Issue by AbhishekSri979** [aws-samples/amazon-chime-react-native-demo#200]
useCase: If we join more meeting with more than 2 or 3 devices then video tiles get freeze automatically and sometime video tiles get blank.

can someone please help me, because i got stuck and i didn't find any solution for freezing video.

environment:
react-native:"0.71.10"
aws-chime-sdk:"0.18.2"

**Comment by ashirkhan94** [comment]
Hi @AbhishekSri979 
Pls see the comments [https://github.com/aws-samples/amazon-chime-react-native-demo/issues/195#issuecomment-1711360513](url)
It may help you
Thanks

**Comment by AbhishekSri979** [comment]
Hi @ashirkhan94

i checked this https://github.com/aws-samples/amazon-chime-react-native-demo/issues/195, and implemented as per comments but i am getting below error, also when i calling setPauseTile and setResumeTile function then nothing happening, so can you suggest me what i missing

![IMG_8040A3759902-1](https://github.com/aws-samples/amazon-chime-react-native-demo/assets/144427339/c68ea9fd-833f-42b4-862a-9553be1ebb3d)

**Comment by AbhishekSri979** [comment]
@ashirkhan94 

Also my internet connectivity is fine, so why video tiles is freezing or blank out, if there any other approach to fix this then please suggest me.

**Comment by ashirkhan94** [comment]
Hi @AbhishekSri979 
I think you may check the cause of video freeze by checking the value of `tileState.pauseState`

**Comment by ashirkhan94** [comment]
> setPauseTile

You need to Change 
`Bridge.js` like
```
export const MobileSDKEvent = {
  OnMeetingStart: 'OnMeetingStart',
  OnMeetingEnd: 'OnMeetingEnd',
  -----------
  -----------
  OnPauseVideoTile: 'OnPauseVideoTile',
  OnResumeVideoTile: 'OnResumeVideoTile',
  
```
for Ios
`meetingObserver.h`

```
//need to define OnPauseVideoTile and OnResumeVideoTile here

#define kEventOnMeetingStart @"OnMeetingStart"
#define kEventOnMeetingEnd @"OnMeetingEnd"
.
.
#define KEventonOnPauseVideoTile @"OnPauseVideoTile"
#define KEventOnResumeVideoTile @"OnResumeVideoTile"
```

in `NativeMobileSDKBridge.m`
need to add ` KEventonOnPauseVideoTile` and `KEventOnResumeVideoTile` here
```
- (NSArray<NSString *> *)supportedEvents
{
  return
  @[
    kEventOnMeetingStart,
    kEventOnMeetingEnd,
    .
    .
    KEventonOnPauseVideoTile,
    KEventOnResumeVideoTile,
    .
    .
    kEventOnError  
  ];
}
```

**Comment by AbhishekSri979** [comment]
@ashirkhan94 
yes i am already doing this

**Comment by AbhishekSri979** [comment]
ok thanks @ashirkhan94, i will check again

**Comment by ashirkhan94** [comment]
@AbhishekSri979 
In  android `MeetingObservers.kt` file
```
import com.amazonaws.services.chime.RNDemo.RNEventEmitter.Companion.RN_EVENT_VIDEO_TILE_PAUSED
import com.amazonaws.services.chime.RNDemo.RNEventEmitter.Companion.RN_EVENT_VIDEO_TILE_RESUME
``` 

need to import above lines for pause and resume

**Comment by AbhishekSri979** [comment]
yes @ashirkhan94 i implemented all above code.

**Comment by ashirkhan94** [comment]
> Hi @ashirkhan94
> 
> i checked this #195, and implemented as per comments but i am getting below error, also when i calling setPauseTile and setResumeTile function then nothing happening, so can you suggest me what i missing
> 
> ![IMG_8040A3759902-1](https://user-images.githubusercontent.com/144427339/276101446-c68ea9fd-833f-42b4-862a-9553be1ebb3d.jpeg)
> 
> Below are the implemented code
> 
> For IOS: In MeetingObserver.m file
> 
> * (void)videoTileDidPauseWithTileState:(VideoTileState * _Nonnull)tileState
>   {
>   // Not implemented for demo purposes
>   [_bridge sendEventWithName:KEventonOnPauseVideoTile body:@{@"tileId":[NSNumber numberWithInt: (int)tileState.tileId],@"attendeeId":[tileState attendeeId], @"isLocal":@(tileState.isLocalTile), @"isScreenShare":@(tileState.isContent),@"pauseState":@(tileState.pauseState)}];
>   }
> * (void)videoTileDidResumeWithTileState:(VideoTileState * _Nonnull)tileState
>   {
>   // Not implemented for demo purposes
>   [_bridge sendEventWithName: KEventOnResumeVideoTile body:@{@"tileId":[NSNumber numberWithInt: (int)tileState.tileId],
>   @"attendeeId":[tileState attendeeId], @"isLocal":@(tileState.isLocalTile), @"isScreenShare":@(tileState.isContent), @"pauseState":@(tileState.pauseState)}];
>   }
> 
> In NativeMobileSDKBridge.m RCT_EXPORT_METHOD(setPauseTile:(NSNumber * _Nonnull)tileId) { [meetingSession.audioVideo pauseRemoteVideoTileWithTileId:[tileId integerValue]]; }
> 
> RCT_EXPORT_METHOD(setResumeTile:(NSNumber * _Nonnull)tileId) { [meetingSession.audioVideo resumeRemoteVideoTileWithTileId:[tileId integerValue]]; }
> 
> For Android: in MeetingObserver.kt override fun onVideoTilePaused(tileState: VideoTileState) { // Not implemented for demo purposes logger.info(TAG, "Received event for VideoTilePaused: $tileState") eventEmitter.sendVideoTileEvent(RN_EVENT_VIDEO_TILE_PAUSED, tileState) } override fun onVideoTileResumed(tileState: VideoTileState) { // Not implemented for demo purposes logger.info(TAG, "Received event for VideoTileResumed: $tileState") eventEmitter.sendVideoTileEvent(RN_EVENT_VIDEO_TILE_RESUME, tileState) }
> 
> in NativeMobileSDKBridge.kt @ReactMethod fun setPauseTile(tileId: Int) { logger.info(TAG, "setPauseTile: $tileId") meetingSession?.run { audioVideo.pauseRemoteVideoTile(tileId) } } @ReactMethod fun setResumeTile(tileId: Int) { logger.info(TAG, "setResumeTile: $tileId") meetingSession?.run { audioVideo.resumeRemoteVideoTile(tileId) } }
> 
> in recat native side
> 
> const onPauseVideotileSubscription = () => getSDKEventEmitter().addListener( "OnPauseVideoTile", async (data) => { console.log('onPauseVideotileSubscription', data); // if (tileState.pauseState == 2) { // console.log("Video was paused due to a poor network connection") // } } );
> 
> ```
> const onResumeVideotileSubscription = () =>
>     getSDKEventEmitter().addListener(
>        "OnResumeVideoTile",
>         async (data) => {
>             console.log('onResumeVideotileSubscription', data);
>         }
>     );
> ```
@AbhishekSri979 
Does the error still exist?

**Comment by AbhishekSri979** [comment]
> > Hi @ashirkhan94
> > i checked this #195, and implemented as per comments but i am getting below error, also when i calling setPauseTile and setResumeTile function then nothing happening, so can you suggest me what i missing
> > ![IMG_8040A3759902-1](https://user-images.githubusercontent.com/144427339/276101446-c68ea9fd-833f-42b4-862a-9553be1ebb3d.jpeg)
> > Below are the implemented code
> > For IOS: In MeetingObserver.m file
> > 
> > * (void)videoTileDidPauseWithTileState:(VideoTileState * _Nonnull)tileState
> >   {
> >   // Not implemented for demo purposes
> >   [_bridge sendEventWithName:KEventonOnPauseVideoTile body:@{@"tileId":[NSNumber numberWithInt: (int)tileState.tileId],@"attendeeId":[tileState attendeeId], @"isLocal":@(tileState.isLocalTile), @"isScreenShare":@(tileState.isContent),@"pauseState":@(tileState.pauseState)}];
> >   }
> > * (void)videoTileDidResumeWithTileState:(VideoTileState * _Nonnull)tileState
> >   {
> >   // Not implemented for demo purposes
> >   [_bridge sendEventWithName: KEventOnResumeVideoTile body:@{@"tileId":[NSNumber numberWithInt: (int)tileState.tileId],
> >   @"attendeeId":[tileState attendeeId], @"isLocal":@(tileState.isLocalTile), @"isScreenShare":@(tileState.isContent), @"pauseState":@(tileState.pauseState)}];
> >   }
> > 
> > In NativeMobileSDKBridge.m RCT_EXPORT_METHOD(setPauseTile:(NSNumber * _Nonnull)tileId) { [meetingSession.audioVideo pauseRemoteVideoTileWithTileId:[tileId integerValue]]; }
> > RCT_EXPORT_METHOD(setResumeTile:(NSNumber * _Nonnull)tileId) { [meetingSession.audioVideo resumeRemoteVideoTileWithTileId:[tileId integerValue]]; }
> > For Android: in MeetingObserver.kt override fun onVideoTilePaused(tileState: VideoTileState) { // Not implemented for demo purposes logger.info(TAG, "Received event for VideoTilePaused: $tileState") eventEmitter.sendVideoTileEvent(RN_EVENT_VIDEO_TILE_PAUSED, tileState) } override fun onVideoTileResumed(tileState: VideoTileState) { // Not implemented for demo purposes logger.info(TAG, "Received event for VideoTileResumed: $tileState") eventEmitter.sendVideoTileEvent(RN_EVENT_VIDEO_TILE_RESUME, tileState) }
> > in NativeMobileSDKBridge.kt @ReactMethod fun setPauseTile(tileId: Int) { logger.info(TAG, "setPauseTile: $tileId") meetingSession?.run { audioVideo.pauseRemoteVideoTile(tileId) } } @ReactMethod fun setResumeTile(tileId: Int) { logger.info(TAG, "setResumeTile: $tileId") meetingSession?.run { audioVideo.resumeRemoteVideoTile(tileId) } }
> > in recat native side
> > const onPauseVideotileSubscription = () => getSDKEventEmitter().addListener( "OnPauseVideoTile", async (data) => { console.log('onPauseVideotileSubscription', data); // if (tileState.pauseState == 2) { // console.log("Video was paused due to a poor network connection") // } } );
> > ```
> > const onResumeVideotileSubscription = () =>
> >     getSDKEventEmitter().addListener(
> >        "OnResumeVideoTile",
> >         async (data) => {
> >             console.log('onResumeVideotileSubscription', data);
> >         }
> >     );
> > ```
> 
> @AbhishekSri979 Does the error still exist?

**Comment by AbhishekSri979** [comment]
Hi, @ashirkhan94 

i am busy in other feature of aws chime, so i will check this again and let you know if working or not.

**Comment by AbhishekSri979** [comment]
hi @ashirkhan94 

i checked my code again , and all required code are exist but still not working , listener is not calling and in ios crash is appearing

**Comment by AbhishekSri979** [comment]
Hii @ashirkhan94 

onPause and onResume listener are calling now.

i am explaining what issue i am facing

can you please suggest me ?
whenever i got pauseState value 2, then my video tile getting freeze or blank so at that time what should i do ?

below is the ui for video meeting

<img width="984" alt="Screenshot 2023-10-26 at 9 24 00 PM" src="https://github.com/aws-samples/amazon-chime-react-native-demo/assets/144427339/36d3572b-097e-4d41-9f2f-3ee987f7479c">

 


i thought after calling setResume method video tile will resume but now working.


whenever i will get pauseState value 2 in any of the video tile then what should i do in that case ?

Thanks
