### ISSUE TITLE
How to reduce video quality

### ISSUE THREAD

**Issue by AbhishekSri979** [aws-samples/amazon-chime-react-native-demo#203]
is there any way to reduce the quality of video so that video will not get freeze in case of poor network

**Comment by georgezy-amzn** [comment]
Hi @AbhishekSri979, please follow this [guide](https://github.com/aws/amazon-chime-sdk-android/blob/master/guides/configuring_remote_video_subscription.md) to configure remote video priority/resolution, specifically, the resolution can be configured using `VideoSubscriptionConfiguration`.
