### ISSUE TITLE
How to handle other users camera and mic

### ISSUE THREAD

**Issue by AbhishekSri979** [aws-samples/amazon-chime-react-native-demo#208]
Hello Everyone

can you guys suggest that how to handle others attendees camera and mic ?

I want to On/Off camera and Mic of other users.

please tell me how to handle this features.

**Comment by saurabhghadi0401** [comment]
Hey @AbhishekSri979  you can make use of Data Channels to send on/off events that will get listened to by all users in the Video call room. Send correct payload to identify whom mic/camera you want to switch.

**Comment by AbhishekSri979** [comment]
Ok Thanks @saurabhghadi0401 
Now, i am able to handle camera/mic.
