### ISSUE TITLE
Main Thread issue for iOS.

### ISSUE THREAD

**Issue by LilianAlvarez123** [aws-samples/amazon-chime-react-native-demo#21]
Hello !

I am a bit confuse with threading inside the `MeetingObservers.h` file.

Indeed, VideoTileObserver methods aren't implementing dispatch queue main. However, in the documentation it's specify that the method for VideoTileObserver are called on the main thread : 

https://aws.github.io/amazon-chime-sdk-ios/Protocols/VideoTileObserver.html#/c:@M@AmazonChimeSDK@objc(pl)VideoTileObserver(im)videoTileSizeDidChangeWithTileState:

Am i missing something or is should we have : 
`- (void)videoTileDidAddWithTileState:(VideoTileState * _Nonnull)tileState
{
   dispatch_async(dispatch_get_main_queue(), ^{
      [_bridge sendEventWithName:kEventOnAddVideoTile body:@{@"tileId":[NSNumber numberWithInt: (int)tileState.tileId], @"isLocal":@(tileState.isLocalTile), @"isScreenShare":@(tileState.isContent)}];
   });
}`

Instead of : 

`- (void)videoTileDidAddWithTileState:(VideoTileState * _Nonnull)tileState
{
  [_bridge sendEventWithName:kEventOnAddVideoTile body:@{@"tileId":[NSNumber numberWithInt: (int)tileState.tileId], @"isLocal":@(tileState.isLocalTile), @"isScreenShare":@(tileState.isContent)}];
}`

Thanks for your answer !

**Comment by tianyux-amz** [comment]
Hi @LilianAlvarez123 ,

Thank you for reaching out!

`VideoTileObserver` callbacks were called using `ObserverUtils.forEach()` ([example](https://github.com/aws/amazon-chime-sdk-ios/blob/c3fdcdf17671f8d102140a73552312b96890c673/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/DefaultVideoTileController.swift#L134-L136)), which essentially implementing an [async dispatch queue on main thread](https://github.com/aws/amazon-chime-sdk-ios/blob/c3fdcdf17671f8d102140a73552312b96890c673/AmazonChimeSDK/AmazonChimeSDK/internal/utils/ObserverUtils.swift#L15).

Let me know if that resolves your question. Thanks!

Best,
Tianyu
