### ISSUE TITLE
start and stop meeting 

### ISSUE THREAD

**Issue by LilianAlvarez123** [aws-samples/amazon-chime-react-native-demo#22]
Hello Guys ! 

So here is the problem we are facing : 

We first launch a meeting with 2 people (one on the web and another one on an iPhone).

Then, the one on the iPhone close the app **without** actually calling stopMeeting() method.

After that, we go back on the app and call back the startMeeting().

In the code there is a condition in the method startMeeting() in the file NativeMobileSDKBridge.m

`  if (meetingSession != nil) {
    [meetingSession.audioVideo stop];
    meetingSession = nil;
  }`

In order to prevent that kind of behavior i am describing. Except that is doesn't work. In a sense that the stop function does not seem to finish to execute before starting the meeting.

We replaced the code above by this : 
`  if (meetingSession != nil) {
    [meetingSession.audioVideo stop];
    meetingSession = nil;
    [NSThread sleepForTimeInterval:3.0f];
  }`

=> The problem vanishes then. 

However, it's not very pretty code. And I am not sure if behind stopMeeting() there is an API Rest call. Because if that's the case the 3s value I put might change according to the network quality.

Thanks for the feedback !

**Comment by haifengx** [comment]
Hi @LilianAlvarez123 ,

Thanks for trying out the demo app. You're right, the example we provided is just a very simple use case and may not handle race conditions gracefully due to asynchronicity of the `stop` operation.

Ideally in a real world production app, you may want to create different meeting session objects for different meetings/calls instead of sharing a single variable, and properly terminate the audio/video session if a call is supposed to end. 

Let me know if that makes sense.

**Comment by LilianAlvarez123** [comment]
Hello ! @haifengx 

Thank you very much for the quick answer. 

Do the stop operation is making a networking call ? 

Actually, my case is a bit different. I wan't to join the same meeting again. But if I join it without stopping it first, i get an "Illegal state error".

Here is the precise stack trace : 

API/DefaultAudioVideoFacade/stop
Stopping VideoClient
Running Amazon Chime SDK (0.10.0)
Failed to start meeting, error: illegalState
{ type: 'chime:set:live:host:uuid',
  payload: { liveHostUuid: '2b60c10b-bba0-42fd-824e-2e119e3066e7' } }
'Visio.OnError', 'Failed to start meeting, error: illegalState'
'Visio.OnMeetingEnd', undefined
NativeMobileSDKBridge - videoClientDidStop
NativeMobileSDKBridge - VideoClient is being destroyed

**Comment by Beos24vi** [comment]
@haifengx @LilianAlvarez123 how did you solve this?
