### ISSUE TITLE
Very low call volume

### ISSUE THREAD

**Issue by shalon1** [aws-samples/amazon-chime-react-native-demo#25]
the audio level/volume is extremely low during a call. I've made sure the speaker is active and the audio is still very faint even with the device audio turned up all the way.

**Comment by tianyux-amz** [comment]
Hi @shalon1,

Thank you for reaching out.

- Are you seeing this issue on your app, or on the RN demo app we provided?
- Could you double check and make sure that 1) there is no sound coming from the receiver; 2) there is sound coming from the speaker, but the volume is very low; 3) other apps can play music via speaker on your test device with normal volume.

Best,
Tianyu

**Comment by shalon1** [comment]
> Hi @shalon1,
> 
> Thank you for reaching out.
> 
> * Are you seeing this issue on your app, or on the RN demo app we provided?
> * Could you double check and make sure that 1) there is no sound coming from the receiver; 2) there is sound coming from the speaker, but the volume is very low; 3) other apps can play music via speaker on your test device with normal volume.
> 
> Best,
> Tianyu

Something i missed to mention previously, I'm testing on android.

The issue is on the RN demo app provided.
1. there is sound coming from the receiver 2.speaker works but very low and can't be controlled. 3. music or any other audio works well.

I tried it out on few more devices and it worked as its supposed to on one device with android 10.
Couple things i noticed 
1) on the device with normal functioning audio the volume buttons would increase/decrease the in-call volume level.
2)other devices(android 8.0.1) volume buttons would change the ringer volume and didn't show a in-call volume control even in the expanded view.
3) volume buttons do not affect the RN demo call volume.
4)manually setting the in-call volume to max by using another calling app or regular gsm call increases the volume inside the RN demo app but by a small margin but still very much lower than normal.

**Comment by tianyux-amz** [comment]
Thanks for providing additional details. Could you also let me know what's the make and model of the Android device where you run into this issue? Also, what's the version of the SDK and Media library you are using?

**Comment by shalon1** [comment]
The one with the issue is a huawei nexus 6P.
SDK Platform 26. I don't understand the Media library question.

Also the app hasn't been modified in any way.
I'm starting to think its a problem specific to this device, but I've only tested 3 devices uptill now.

**Comment by tianyux-amz** [comment]
Hi @shalon1, I was asking for the Chime SDK and Chime Media library version (as mentioned [here](https://github.com/aws-samples/amazon-chime-react-native-demo/issues/25)).

I have a Huawei Nexus 6P test device. Let me try on my side and see if I can reproduce the issue.

**Comment by tianyux-amz** [comment]
I wasn't able to reproduce the issue on my Huawei Nexus 6P. I am using Android 8.0.0 instead of 8.0.1, but I don't think that matters. I'm using amazon-chime-sdk v0.7.1 and amazon-chime-sdk-media v0.6.1.

**Comment by shalon1** [comment]
I'm using the same as you. Amazon-chime-sdk v0.7.1 and amazon-chime-sdk-media v0.6.1.

**Comment by shalon1** [comment]
problem seems to be device related

**Comment by kvntzn** [comment]
@hokyungh yes it is. Although it is  very low even if the volume is maxed  out. I wonder if it should be using in call volume instead of speaker. 
<img src="https://user-images.githubusercontent.com/29770932/117881106-71b1ed00-b2db-11eb-873f-b7be9d1cc59a.jpg" width="100" />

**Comment by hokyungh** [comment]
Hi @kvntzn, just wanted to double check. Is volume coming from speaker or earpiece? If earpiece, are you saying that volume is very low when you put ear nearby? If it is not coming from speaker, you would need to use [ChooseAudioDevice](https://aws.github.io/amazon-chime-sdk-android/amazon-chime-sdk/com.amazonaws.services.chime.sdk.meetings.audiovideo/-default-audio-video-facade/choose-audio-device.html) to change to speaker.
