### ISSUE TITLE
Integrating with iOS CallKit

### ISSUE THREAD

**Issue by ceremonious** [aws-samples/amazon-chime-react-native-demo#28]
Are there any resources on how to integrate this React Native demo with iOS Callkit? I see this [post](https://aws.amazon.com/blogs/business-productivity/how-to-integrate-apples-callkit-into-ios-applications-using-the-amazon-chime-sdk/) about integrating with native iOS, however, it seems to be written in Swift, while most of this demo is on Obj C.

**Comment by hokyungh** [comment]
Thank you for opening issue. Unfortunately, we do not have example for Objective C, so based on [post](https://aws.amazon.com/blogs/business-productivity/how-to-integrate-apples-callkit-into-ios-applications-using-the-amazon-chime-sdk/) and [demo](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingModel.swift), you would have to port Swift into Objective C. Sorry for any inconvenience.
