### ISSUE TITLE
Can't resume video tile after pause.

### ISSUE THREAD

**Issue by LilianAlvarez123** [aws-samples/amazon-chime-react-native-demo#29]
Describe the bug
Contexte :
In the spirit of networking optimization, we decided to pause all remote video tile id when the app goes to background.
When the app come back, we call the method `[meetingSession.audioVideo resumeRemoteVideoTileWithTileId: [tileId integerValue]];` in order to unpause the video and to display it on the screen.

Except that even if the method is call there is no video stream coming back. We can observe it thought the Network report section inside Xcode.

So, even if, the resume method is being called, the video never resume.

To Reproduce

Start a meeting from the mobile.
Join the from the web with an active camera and mic.
Pause the video tile id from the Web
Set the web camera and mic on.
Resume the video tile id of the web.
The video is not showing up.
Expected behavior
We should video should appear in the step 6.

Test environment Info (please complete the following information):

iPhone 11 Pro Max
iOS 12.1
Version AmazonChimeSDK: [e.g. 0.11.1]
Version AmazonChimeSDKMedia: [e.g. 0.7.1]
React Native app.
Additional context
Here is the added methods inside the bridge (NativeMobileSDKBridge.m) :

```
RCT_EXPORT_METHOD(pauseRemoteVideoId:(NSNumber * _Nonnull)tileId) {
  dispatch_async(dispatch_get_main_queue(), ^{
    [meetingSession.audioVideo pauseRemoteVideoTileWithTileId: [tileId integerValue]];
  });
}

RCT_EXPORT_METHOD(resumeRemoteVideoId:(NSNumber * _Nonnull)tileId) {
  dispatch_async(dispatch_get_main_queue(), ^{
    [logger infoWithMsg:[NSString stringWithFormat:@"resumeRemoteVideoId %ld", (long)tileId]];
    [meetingSession.audioVideo resumeRemoteVideoTileWithTileId: [tileId integerValue]];
  });
}
```

We also put an issue on the iOS Chime SDK https://github.com/aws/amazon-chime-sdk-ios/issues/166.
I duplicate the issue here by their demand.

**Comment by hokyungh** [comment]
@LilianAlvarez123 Is there way for us to get more implementation details on react native side (JS) portion? How are pause and resume called?

I have tried with our demo application by adding two buttons, but I wasn't able to reproduce your issue.

**Comment by LilianAlvarez123** [comment]
Hello @hokyungh.

Thank you for the feedback.

Did you add the method below inside meetingObservers.m ?

```
- (void)videoTileDidResumeWithTileState:(VideoTileState * _Nonnull)tileState
{
  [_logger infoWithMsg:[NSString stringWithFormat:@"Klaxoon Live videoTileDidResumeWithTileState %ld", (long)tileState.tileId]];
  [_bridge sendEventWithName:kEventOnResumeVideoTile body:@{@"tileId":[NSNumber numberWithInt: (int)tileState.tileId], @"isLocal":@(tileState.isLocalTile), @"isScreenShare":@(tileState.isContent), @"attendeeId":[tileState attendeeId]}];
}
```

If I pause the videoTile, then go to background with the app. And go back and trigger the resume method. The event never gets called.

Does it get call for you ?

**Comment by hokyungh** [comment]
Yes. Device used: iPhone 6S Plus (12.4)
MeetingObserver.m
```
- (void)videoTileDidResumeWithTileState:(VideoTileState * _Nonnull)tileState
{
  // Not implemented for demo purposes
  [_logger infoWithMsg:[NSString stringWithFormat:@"Klaxoon Live videoTileDidResumeWithTileState %ld", (long)tileState.tileId]];
}
```

NativeMobileSDKBridge.m
```
RCT_EXPORT_METHOD(pauseVideo:(NSNumber * _Nonnull)tileId) {
  dispatch_async(dispatch_get_main_queue(), ^{
    [meetingSession.audioVideo pauseRemoteVideoTileWithTileId: [tileId integerValue]];
  });
}

RCT_EXPORT_METHOD(resumeVideo:(NSNumber * _Nonnull)tileId) {
  dispatch_async(dispatch_get_main_queue(), ^{
    [logger infoWithMsg:[NSString stringWithFormat:@"resumeRemoteVideoId %ld", (long)tileId]];
    [meetingSession.audioVideo resumeRemoteVideoTileWithTileId: [tileId integerValue]];
  });
}
```

Meeting.js
```
        <View style={styles.videoContainer}>
          {this.state.videoTiles.length > 0 ? (
            this.state.videoTiles.map((tileId) => (
              <View>
                <RNVideoRenderView style={styles.video} key={tileId} tileId={tileId} />
                <Button title="p" onPress={() => NativeFunction.pauseVideo(tileId)} />
                <Button title="r" onPress={() => NativeFunction.resumeVideo(tileId)} />
              </View>
            ))
          ) : (
            <Text style={styles.subtitle}>No one is sharing video at this moment</Text>
          )}
        </View>
```
Do you mind testing it with our demo app to see if it is reproducible?

**Comment by dchen-aws** [comment]
@LilianAlvarez123 any chance you calling stopRemoteVideo before app entering the background? we had a bug where paused video tiles can't be resumed if you had called stopRemoteVideo. The issue has been fixed in the recent release. Can you give it a shot? CC @hokyungh
