### ISSUE TITLE
Switch camera from front to rear and then rear to front

### ISSUE THREAD

**Issue by tuneerclixlogix** [aws-samples/amazon-chime-react-native-demo#30]
Can we switch the rear and front cameras ?

**Comment by hokyungh** [comment]
Hi react-native might not example of switching camera, but you can use
Android: [switchCamera](https://aws.github.io/amazon-chime-sdk-android/amazon-chime-sdk/com.amazonaws.services.chime.sdk.meetings.device/-device-controller/switch-camera.html)
iOS: [switchCamera](https://aws.github.io/amazon-chime-sdk-ios/Protocols/DeviceController.html#/c:@M@AmazonChimeSDK@objc(pl)DeviceController(im)switchCamera)

You would have to implement it in [iOS Bridge](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/NativeMobileSDKBridge.m) and [Android Bridge](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt)

**Comment by tianyux-amz** [comment]
Resolving as we provided solution above. Feel free to reopen if you have more questions regarding this.

**Comment by timorss** [comment]
Any guided solution for this please?

**Comment by hokyungh** [comment]
Hi @timorss
Basically, you would need to add
```
@ReactMethod
  fun switchCamera() {
        meetingSession?.audioVideo?.switchCamera()
  }
```

similar for iOS.
