### ISSUE TITLE
Audio in background stops during meeting on Android 9.1

### ISSUE THREAD

**Issue by LilianAlvarez662** [aws-samples/amazon-chime-react-native-demo#31]
**Describe the bug**
When going in background (without killing the app) during a meeting after about 65 seconds audio stops transmitting.

**To Reproduce**
1. Start a meeting from an Android Phone.
2. Have another account to join the meeting on the web (cut the mic of the web).
3. Leave the app (without killing it) with your android phone.
4. Speak, make sound, you should be able to hear it from the web browser.
5. After about 40-80s of being on any other app or just on the phone menu the microphone will not emit sound anymore.

**Expected behavior**
5. We should still be able to emit sound.

**Logs**
No logs indicating any change.

**Screenshots**

**Test environment Info (please complete the following information):**
 - Honor 9 Lite
 - Android 9.1
 - Version amazon-chime-sdk: 0.8.0. 
 - Version amazon-chime-sdk-media:  0.8.0.
- Same effect from the previous version of the SDK.
- React Native 0.61.5
**Additional context**

**Comment by hokyungh** [comment]
@LilianAlvarez662 Do you know if your app is using [service](https://developer.android.com/reference/kotlin/android/app/Service)? It is very possible that Android OS either killed it or took the resource from it. By running it in Service, Android should retain those.

**Comment by LilianAlvarez123** [comment]
Yes, you were right, by using a service it solves the issue of background.

**Comment by hokyungh** [comment]
Thank you for confirming. We'll close the issue. Feel free to reopen if you have any issue.
