### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by tahamazari** [aws-samples/amazon-chime-react-native-demo#32]
I am basically making an app that can have multiple rooms. Each room can have their own meeting and members. 
Currently the issue im facing is that when i go to one room start meeting, go back to another room, the app crashes.
Can you please help?

**Comment by tianyux-amz** [comment]
Hi @tahamazari, thank you for reaching out. We need more details to help you troubleshooting the issue.

- What SDK and Media library versions are you using?
- Could you provide the crash log?
- When you said "each room can have their own meeting and members", do you mean you create multiple concurrent meetings in the app? Generally I'd like more details on your implementation, e.g. what APIs do you call when you "go to one room start meeting, and go back to another room".

Thanks!

**Comment by tahamazari** [comment]
> Hi @tahamazari, thank you for reaching out. We need more details to help you troubleshooting the issue.
> 
> * What SDK and Media library versions are you using?
> * Could you provide the crash log?
> * When you said "each room can have their own meeting and members", do you mean you create multiple concurrent meetings in the app? Generally I'd like more details on your implementation, e.g. what APIs do you call when you "go to one room start meeting, and go back to another room".
> 
> Thanks!

In project level build.gradle I have, 
    **ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 23
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.+"
        firebaseVersion = "17.6.0"
        ext.kotlin_version = '1.3.72'
        androidXCore = "1.0.2"
    }**

- I am using React Native version 0.59.
- I cant provide the crash log as the app simply has a Native Modules crash, so no crash log
- Yes, for the app I am making, you can create multiple meetings but there is one meeting at a single time.
- Meetings requests are send uniquely using each Rooms Id.
- Meetings are held in rooms (in my implementation), If you join a room meetings start by sending an api call mentioned in the demo i.e. **createMeetingRequest**. This then using that response call **NativeFunction.startMeeting()**.
- When you join a new room, then the meeting that is being held in previous room should call **NativeFunction.stopMeeting()**, and then the api call goes for new meeting to be instantiated in that room using **createMeetingRequest** which then calls **NativeFunction.startMeeting()**
- I am also saving meeting data in redux persist. So that no need to call meeting **createMeetingRequest**, just start again meeting by calling **NativeFunction.startMeeting()**

**Sidenote:**
I also get error (from backend ) i.e **Internal Server Error** if I create meeting  **createMeetingRequest** by sending the the same room Id again and again


Tianyux, it would be a great pleasure if you help me sort out these issues 👍

**Comment by tianyux-amz** [comment]
Hi @tahamazari ,

According your description, what you do sounds about right. There should be only one `meetingSession` available at any time, and if you go to another room, you call `stopMeeting` to stop audio/video client and clean up old meetingSession, and call `startMeeting` to re-initialize a new meetingSession and restart audio/video client.

Are you able to tell from the log that when did the crash happen, when you end the previous meeting or when you start the new meeting?

**Comment by tahamazari** [comment]
Hey @tianyux-amz , the crash happens when I stop the previous meeting session and call startMeeting for new room. Is stopMeeting asynchronous?

**Comment by tahamazari** [comment]
So I used Bugsnag to tell me why there is an issue, here are the logs, apparently there is an issue with video client I guess?

/data/app/com.treble-AlEBFZ0DgCoF_K8Sfv1GOA==/lib/arm64/libamazon_chime_media_client.so:1182960Java_com_xodee_client_video_VideoClient_isActive	
/apex/com.android.runtime/lib64/libart.so:13074760x75e895f354	
/apex/com.android.runtime/lib64/libart.so:12705840x75e8956338	
/apex/com.android.runtime/lib64/libart.so:1331376art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)	
/apex/com.android.runtime/lib64/libart.so:3025052art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)	
/apex/com.android.runtime/lib64/libart.so:3004712bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)	
/apex/com.android.runtime/lib64/libart.so:5900612MterpInvokeVirtual	
/apex/com.android.runtime/lib64/libart.so:12472560x75e8950818	
/apex/com.android.runtime/lib64/libart.so:5901396MterpInvokeVirtual	
/apex/com.android.runtime/lib64/libart.so:12472560x75e8950818	
/apex/com.android.runtime/lib64/libart.so:5907520MterpInvokeInterface	
/apex/com.android.runtime/lib64/libart.so:12477680x75e8950a18	
/apex/com.android.runtime/lib64/libart.so:28307960x75e8ad31cc	
/apex/com.android.runtime/lib64/libart.so:5840348artQuickToInterpreterBridge	
/apex/com.android.runtime/lib64/libart.so:13077560x75e895f46c	
0x9c92fed8

**Comment by hokyungh** [comment]
@tahamazari what SDK version are you using?

**Comment by tahamazari** [comment]
> @tahamazari what SDK version/Media version are you using?

I downloaded these sdk from the demo project,
amazon-chime-sdk-0.7.1.tar.gz
amazon-chime-sdk-media-0.6.1.tar.gz

**Comment by hokyungh** [comment]
@tahamazari do you mind testing with at least 0.7.2?

In my belief, some of those null pointer exception was fixed from 0.7.2 https://github.com/aws/amazon-chime-sdk-android/releases

**Comment by tahamazari** [comment]
> @tahamazari do you mind testing with at least 0.7.2?
> 
> In my belief, some of those null pointer exception was fixed from 0.7.2 https://github.com/aws/amazon-chime-sdk-android/releases

Thank you so much @hokyungh , will try and let you know if the issue was fixed :)

**Comment by tahamazari** [comment]
@hokyungh , still got
**/data/app/com.treble-3hzmA3dVZHkQT-8Hf5LixQ==/lib/arm64/libamazon_chime_media_client.so:982224Java_com_xodee_client_video_VideoClient_isActive**

May be im not executing stopMeeting correctly? Why doesnt video client is doesnt stop :/

**Comment by tahamazari** [comment]
Apparently the error is of type 
**SIGSEGV · Segmentation violation (invalid memory reference**

**Comment by tahamazari** [comment]
Ok so after testing alot, I have come to the conclusion that **stopMeeting()** is not closing the previous meeting properly, thats why the app keeps on crashing. Any idea or solution to this problem?

**Comment by hokyungh** [comment]
@tahamazari thank you for reporting. Do you mind sharing with us what was the version of SDK and new Media library you used?

**Comment by tahamazari** [comment]
My SDK version is 0.8.1, Media version is also 0.8.1. 

So basically trying to elaborate the issue to you, consider a **Room** component in which when you join i.e componentDidMount, a meeting is initiated by calling createMeetingRequest api. Once response is received, NativeFunction.startmeeting(meeting, attendee) is called (and meeting and attendee is saved in reducer so that API call isnt sent, values are taken directly from reducer and NativeFunction.startmeeting is called).

In this components ComponentWillUnmount, NativeFunction stopMeeting is called. So when I go back, stopmeeting is called. But when I immediatly go back to same component (and same Room), the app crashes as previous meeting has not ended probably and new meeting is again called in componentDidMount().

I have attached a picture for your reference for the concept of Rooms, you can hold meeetings with your friends in a Room.
https://pbs.twimg.com/media/Enr70eUVkAAmCAO?format=jpg&name=large

**Comment by tianyux-amz** [comment]
@tahamazari Instead of calling `startmeeting()` and `stopMeeting()` in RN component lifecycle callbacks, could you rely on the audio/video session lifecycle callbacks instead:
- In `componentDidMount`, call `createMeetingRequest`, save the response and call `startMeeting()`.
- When click the "Back" button of the current room, call `stopMeeting()`.
- Implement `MeetingObservers` and navigate back to the room list after [`audioSession` stopped](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/858c6cee539e373300b93ed9a272ad6efc0048b6/ios/RNDemo/MeetingObservers.m#L125) and/or [`videoSession` stopped](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/858c6cee539e373300b93ed9a272ad6efc0048b6/ios/RNDemo/MeetingObservers.m#L151).

This should make sure the audio and video clients were properly stopped before you enter a room again.

**Comment by tahamazari** [comment]
Is there any good documentation for Meeting Observers? Would appreciate if there exists for React Native :)

**Comment by tahamazari** [comment]
Should I create new Meeting Observers MeetingObservers.kt? I thought you could not create new ones as I believe those that exist are are provided by sdk and you cant make new ones

**Comment by tianyux-amz** [comment]
[MeetingObservers](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/858c6cee539e373300b93ed9a272ad6efc0048b6/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt) currently implements RealtimeObserver, VideoTileObserver and AudioVideoObserver interfaces. You can find documentations of these interfaces in iOS and Android API Overview, e.g. AudioVideoObserver [in iOS](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/api_overview.md#4-register-an-audio-video-observer), [in Android](https://github.com/aws/amazon-chime-sdk-android/blob/master/guides/api_overview.md#4-register-an-audio-video-observer). 

There are already stubs for [onAudioSessionStopped](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/858c6cee539e373300b93ed9a272ad6efc0048b6/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L113) and [onVideoSessionStopped](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/858c6cee539e373300b93ed9a272ad6efc0048b6/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L133). You need to send a ReactNative event in these callbacks to notify RN side that audio/video was stopped, and then you can safely go into a new Room.

**Comment by tahamazari** [comment]
Do you guys have any plans to implement these observers yourself in the near future?

**Comment by tianyux-amz** [comment]
No we don't. This RN repo is for demo purposes only, which give you a rough idea on how to integrate Amazon Chime SDK into your React Native application. Also, different builders have different use case requirements, which cannot be all captured in one single demo. We can provide some help if you run into issues implementing your own observer callbacks though.

**Comment by tahamazari** [comment]
`    override fun onAudioSessionStopped(sessionStatus: MeetingSessionStatus) {
        logger.info(TAG, "Audio session ended")
        // Not implemented for demo purposes
        eventEmitter.sendReactNativeEvent(RNEventEmitter.RN_EVENT_MEETING_END, null)
    }`

Would this be enough for enabling the event to check of the audio was stopped?

**Comment by tahamazari** [comment]
@tianyux-amz @hokyungh please help

**Comment by tianyux-amz** [comment]
You don't need to make changes inside the SDK library. 

> **override fun onAudioSessionStopped(sessionStatus: MeetingSessionStatus) {**
> _logger.info(TAG, "Audio session ended") eventEmitter.sendReactNativeEvent(RNEventEmitter.RN_EVENT_MEETING_END, null)_
> **}**

The above code won't work. `onAudioSessionStopped` will be called **after** the audio session fully stopped, but you probably already using `RN_EVENT_MEETING_END` to tell RN that `audioVideo.stop()` was called and the async call was started ([ref](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/cabe07a5001d1dbc5c5fc08b960d957a9880f256/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L155)). Instead, you can send a new type of event to RN to notify that the meeting was fully stopped and it's ok to navigate back to meeting list.

Something like this:

- In RNEventEmitter.kt:
```kotlin
// Event types
...
const val RN_EVENT_MEETING_FULLY_ENDED = "OnMeetingFullyEnded"
```

- In MeetingObservers.kt:
```kotlin
override fun onAudioSessionStopped(sessionStatus: MeetingSessionStatus) {
    eventEmitter.sendReactNativeEvent(RNEventEmitter.RN_EVENT_MEETING_FULLY_ENDED, null)
}
```

- In src/utils/Bridge.js:
```typescript
export const MobileSDKEvent = {
    OnMeetingFullyEnded: 'OnMeetingFullyEnded',
    ...
}
```

- In src/App.js:
```typescript
componentDidMount() {
    ...
    this.onMeetingFullyEndedSubscription = getSDKEventEmitter().addListener(MobileSDKEvent.OnMeetingFullyEnded, () => {
        // Navigate back to the meeting list now, as the previous meeting was properly stopped
    }
}

componentWillUnmount() {
    ...
    if (this.onMeetingFullyEndedSubscription) {
        this.onMeetingFullyEndedSubscription.remove();
    }
}
```
