### ISSUE TITLE
onAudioSessionStarted event not triggering

### ISSUE THREAD

**Issue by tahamazari** [aws-samples/amazon-chime-react-native-demo#34]
I added onAudioSessionStarted to Bridge.js, its not working when (a meeting starts)I call it using
```
  this.onAudioSessionStarted = getSDKEventEmitter().addListener(MobileSDKEvent.onAudioSessionStarted, () => {
    console.log("audio has started!!!")
  });
```

Am I missing something or doing something wrong?

**Comment by tianyux-amz** [comment]
Hi @tahamazari ,

Could you share the code to show me how you defined `onAudioSessionStarted` event type in Bridge.js, and how you send the `onAudioSessionStarted` event from the native side?
