### ISSUE TITLE
Lag in Audio

### ISSUE THREAD

**Issue by tahamazari** [aws-samples/amazon-chime-react-native-demo#35]
Hey, I have solved App crash issues. But there is still problem of lag when communicating. I have deployed my serverless app on a bucket that is located in the USA. Also, my `SERVER_REGION` in my `src/utils/Api.js` is set to `eu-central-1` i.e. Frankfurt. I am currently developing the App in Pakistan.

Should I deploy my server on a bucket based somewhere close to South Asia? And also, should I set SERVER_REGION to Mumbai?

Lastly, when scaling to millions of users, how will we have to deploy various servers for each region and call the one which is nearest to a user?

**Comment by tianyux-amz** [comment]
Hi @tahamazari, in our RN demo, [`SERVER_REGION` in `src/utils/Api.js`](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/059d8c6f29644f5889923ab19bac634c507c7b12/src/utils/Api.js#L11) will be propagated as [`MediaRegion` in `CreateMeetingRequest`](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L49-L51). You can find more informations on this topic in [this doc](https://docs.aws.amazon.com/zh_cn/chime/latest/dg/chime-sdk-meetings-regions.html), including a list of all the available media regions and how to determine which region you should use.

I'm resolving this for now. Feel free to reopen if you have more questions regarding this.

**Comment by tahamazari** [comment]
Thank you so much @tianyux-amz !
