### ISSUE TITLE
Is there way to detect if user left meeting

### ISSUE THREAD

**Issue by tahamazari** [aws-samples/amazon-chime-react-native-demo#36]
Hi, Im trying to make a social media application in RN that leverages the power Chime.
Wanted to know if there is a method in the sdk to detect the number of users within a meeting that is currently being held based on the `ExternalMeetingId`? 

I want to track the number of users in the meeting so in order to check which users are online.

**Comment by zhinang-amazon** [comment]
Hi, you can listen to events on `RealTimeObserver` from native iOS and Android SDK.
We have sample bridging to RN in this repo `MeetingObservers`
iOS:
[attendeesDidJoinWithAttendeeInfo](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/MeetingObservers.m#L23)
[attendeesDidLeaveWithAttendeeInfo](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/MeetingObservers.m#L32)
[attendeesDidDropWithAttendeeInfo](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/MeetingObservers.m#L75)
Android: 
[onAttendeesJoined](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L32)
[onAttendeesLeft](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L39)
[onAttendeesDropped](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L46)

Let us know if you have more questions

**Comment by tahamazari** [comment]
Great, but there is an issue, currently when a user hangs up meeting only then I get updated state attendees. I also want to check on runtime if user left when ever they quit the app. In this case state attendees should update remove user who left but it doesn't

**Comment by zhinang-amazon** [comment]
Hi @tahamazari,
Amazon Chime SDK will not handle App life cycle events.
What you can do: In your iOS native code, in [AppDelegate](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/AppDelegate.m#L31), add implementation of [applicationWillTerminate:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623111-applicationwillterminate?language=objc) to leave the meeting and clean up other app states if needed. This will make sure `attendeesDidLeaveWithAttendeeInfo` will be sent to other active attendees.
This delegate method will be invoked when user force kill the app.
I'm sure you can find resources online on how to handle force kill on Android also :)
