### ISSUE TITLE
[Android] Video stuttering / frozen with multiple participants

### ISSUE THREAD

**Issue by nealmanaktola** [aws-samples/amazon-chime-react-native-demo#37]
Hi there,

I've done a side by side comparison with web and android. On calls with 5+ video tiles, I see other video's freezing for 20-30+ seconds, very laggy performance, or stutters.

Have you experienced such issues? 
Web seems to be working just fine. 

Thanks

**Comment by hokyungh** [comment]
@nealmanaktola I think we might need more information. The performance can depend on multiple factors like cpu/network/memory. Would you be able to give more information on following?

1. When you were testing you, were testing with Android Chrome browser or just Chrome on the computer VS Android app? 
2. What is the device you are using?
3. What are SDK/Media SDK version?
4. Do you have any logs?
5. How many video tiles were you displaying?

**Comment by nealmanaktola** [comment]
1. Chrome on computer VS Andorid app
2. Pixel 3
3. 0.7.1/0.6.1 (same as README.md)
4. No, I'll reproduce and add logs
5. There was at least 7-8 tiles

I'll reproduce and add logs for you. This is via the react native app btw.

**Comment by nealmanaktola** [comment]
I was wondering to see if the core issue was on the react native layer or if it was with Android specifically.
I did a test with the android sample app:

![Screenshot_20201216-130325](https://user-images.githubusercontent.com/1707258/102396637-b5156300-3faa-11eb-96fc-15c3571d8ddf.png)
There were around 12 attendees. I was seeing black tiles at times, video's freezing, it was a bad experience all in all.
I did a test with 4 attendeeds, and the experience was great. No freezing, no black tiles.

I was doing a side by side comparison with web. Web was working fine.
I've added some logs too. Let me know if I should move this issue to the android-sdk repo.

[chime-av-log.txt](https://github.com/aws-samples/amazon-chime-react-native-demo/files/5705064/chime-av-log.txt)

**Comment by hokyungh** [comment]
@nealmanaktola do you mind implementing some pagination and upgrade your SDK version? 

There has been few numerous improvements regarding video as described here https://github.com/aws/amazon-chime-sdk-android/releases. 

You can also see the guide for [pagination](https://github.com/aws/amazon-chime-sdk-android/blob/development/guides/video_pagination.md). Please note that mobile is very limited on cpu and memory, so having 12 video tiles could be a lot.

**Comment by nealmanaktola** [comment]
I have implemented paging but do see this from time to time. It's definitely not as bad as before, but still happens. I've also made some modifications:
1. Added a VideoFrameBroadcaster to support multiple tiles
2. Pause/Resume removes the VideoSinks inside the VideoFrameBroadcaster, instead of calling the actual pause/resume on the `audioVideo` obj
