### ISSUE TITLE
No Video is Displayed

### ISSUE THREAD

**Issue by sacmii** [aws-samples/amazon-chime-react-native-demo#38]
### iOS only issue
RNVideoView component not displaying Video in the Mobile SDK.
It's showing Empty Space as shown in the Image
![img001](https://user-images.githubusercontent.com/12546974/101822707-c6481500-3b4f-11eb-897c-0e3964ec2f41.jpg)
But when a background color is applied to RNVideoRenderView, the output is as follows
![img002](https://user-images.githubusercontent.com/12546974/101822778-e2e44d00-3b4f-11eb-9ef8-5b9ede269a4a.jpg)
where the '#eee' colored views are **RNVideoRenderView** components

Environment
System:
OS: macOS 10.15.7
CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
Memory: 157.21 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.0 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
Android SDK:
API Levels: 28, 29, 30
Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
System Images: android-30 | Google APIs Intel x86 Atom
Android NDK: Not Found
IDEs:
Android Studio: 4.1 AI-201.8743.12.41.6858069
Xcode: 12.2/12B45b - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_272 - /usr/bin/javac
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: ^16.14.0 => 16.14.0
react-native: ^0.63.3 => 0.63.3
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

**Comment by sacmii** [comment]
Everything works fine on android

**Comment by hokyungh** [comment]
@sacmii Would you be able to provide SDK/Media SDK version you are using? Additionally, do you mind trying to test with [v0.12.2](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.12.2)? I am trying to see if fix on video freeze issue also fixes your issue.

**Comment by hokyungh** [comment]
@sacmii see https://github.com/aws/amazon-chime-sdk-ios/issues/178 as reference.

**Comment by hokyungh** [comment]
Issue resolved. Feel free to reopen this ticket if issue continues.
