### ISSUE TITLE
Activate video in call app crashes

### ISSUE THREAD

**Issue by IronTony** [aws-samples/amazon-chime-react-native-demo#39]
Hi all,

I am using the RNDemo app with the serverless demo, and I am using the lastest SDK and MediaSDK (AmazonChimeSDK-0.12.2 and AmazonChimeSDKMedia-0.8.2).
I can join the chat using web and React-Native app, but when someone activate the video (web or RN app) the iOOS app crashes with this error in the console:

```
*** First throw call stack:
(0x1902fa9d8 0x1a4663b54 0x19020abbc 0x192b97e14 0x1902fcd58 0x1902fef8c 0x103a1b00c 0x103a1bfd4 0x103a1c074 0x103a130d4 0x103a18bd4 0x1039ed068 0x1039ed33c 0x103a19228 0x1050a3ce4 0x1050a5528 0x1050b3994 0x19027a5e0 0x190274a88 0x190273ba0 0x1a6fb1598 0x192b633d8 0x192b68958 0x10252a240 0x18ff52568)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RNVideoView onVideoFrameReceivedWithFrame:]: unrecognized selector sent to instance 0x129e79ff0'
terminating with uncaught exception of type NSException
```

Any hint?

**Comment by IronTony** [comment]
I tried with the SDK and MediaSDK of the example (ChimeSDK 0.7.1 and MediaSDK 0.6.1) and not crash. Maybe the example code has to be fixed?

All the best

**Comment by hokyungh** [comment]
Thank you for the report. I'll label as bug.

**Comment by IronTony** [comment]
Thank you so much 🤞 🤞 🤞

**Comment by hokyungh** [comment]
Issue resolved. Feel free to reopen if you still encounter issue.
