### ISSUE TITLE
Android : use demo files into an existing project

### ISSUE THREAD

**Issue by rlebosse** [aws-samples/amazon-chime-react-native-demo#4]
Hi,

I'm trying to figure out what is the minimum configuration needed in `android/app/build.gradle` and `android/build.gradle` files.

#### android/app/build.gradle

Are these lines required ? I don't find where these dependencies are needed ?

```gradle
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3'
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
```

When I look at the ** page in Android developers : https://developer.android.com/kotlin/add-kotlin, the 2 above lines are not added.

Moreover, there is another dependency added :

```gradle
implementation "androidx.core:core-ktx:1.0.1"
```

Is this one unnecessary in your demo ?

Thanks in advance for you answers and for this awesome sample !

**Comment by weichenhamzn** [comment]
Hi, those are used to make HTTP request in Android, since we migrate the HTTP request to JS, So they are no longer needed. 
For the minimum configuration, just make sure react-native dependencies are satisfied.
