### ISSUE TITLE
Code signing "AmazonChimeSDK.framework" failed.

### ISSUE THREAD

**Issue by SeanRenet** [aws-samples/amazon-chime-react-native-demo#41]
When I try to validate or distribute my app, it fails with this message.

Code signing "AmazonChimeSDK.framework" failed.

**Comment by hokyungh** [comment]
Thanks for reporting. Do you mind providing more details on error logs? Do you think it might be related to https://github.com/aws/amazon-chime-sdk-ios/issues/29?
