### ISSUE TITLE
Feature Request : stop Rotation inside RNVideoRenderView.

### ISSUE THREAD

**Issue by LilianAlvarez123** [aws-samples/amazon-chime-react-native-demo#43]
**Is your feature request related to a problem? Please describe.**
When i rotate my iPhone during a live conversation with camera. The video stream rotate too. I am not talking about the view.
If you film yourself with the camera (selfie mode). You will see that even if you rotate your phone, your face is always in the same direction. 

**Describe the solution you'd like**
I would like it to remain in portrait mode when needed.

**Describe alternatives you've considered**
i tried to redefined without success the RNVideoView in the method : 

`[meetingSession.audioVideo bindVideoViewWithVideoView:(RNVideoView*)view tileId:[tileId integerValue]];`

from `NativeMobileSDKBridge.m`. 

I tried to configure a RNVideoView with a rotation to 0 as described here : https://github.com/aws/amazon-chime-sdk-ios/issues/161

**Comment by LilianAlvarez123** [comment]
Hello Guys, is it the right place for this issue ? @hokyungh @zhinang-amazon :)

**Comment by hokyungh** [comment]
@LilianAlvarez123 Sorry for late reply. I think easiest way is to have your own implementation of `DefaultCameraCaptureSource` [updateOrientation](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/capture/DefaultCameraCaptureSource.swift#L180) and [startLocalVideo](https://aws.github.io/amazon-chime-sdk-ios/Classes/DefaultAudioVideoController.html#/c:@M@AmazonChimeSDK@objc(pl)AudioVideoControllerFacade(im)startLocalVideoWithSource:) with that source. You can eliminate orientation update code and just have initial orientation. Let us know if this worked out.
