### ISSUE TITLE
how to increase audio quality

### ISSUE THREAD

**Issue by iamhaaamed** [aws-samples/amazon-chime-react-native-demo#47]
is it possible to increase audio quality? i have no problem with video but audio quality is not good

**Comment by zhinang-amazon** [comment]
Hi @iamhaaamed 
Our iOS and Android SDK supports Voice Focus feature. [iOS doc](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/api_overview.md#11-using-amazon-voice-focus-optional) [Android doc](https://github.com/aws/amazon-chime-sdk-android/blob/master/guides/api_overview.md#11-using-amazon-voice-focus-optional)

Please use the latest iOS and Android SDK and turn on Voice Focus and see if audio quality is improved for you.

**Comment by iamhaaamed** [comment]
can anything be done for lag and disconnecting audio?

**Comment by hokyungh** [comment]
Could you provide little bit more information?

1. SDK/Media SDK version you are using
2. network (3G/4G/wifi (maybe speed))
3. Device you are using to test
4. The number of people that were in the meeting

**Comment by iamhaaamed** [comment]
sure, here you are:
1. SDK version: 0.8.2
2. network: wifi
3. Device: android v8, android v10
4. The number of people that were in the meeting: 2

**Comment by hokyungh** [comment]
@iamhaaamed Do you mind adding logs as well? Based on the conditions you provided, it doesn't look like audio should be bad. For audio quality, any specific issue you are experiencing?
1. Audio is lagging
2. Audio is soft
3. Audio is very unclear, so receiving end cannot understand the sending portion.

**Comment by iamhaaamed** [comment]
Audio is lagging and unclear...

**Comment by hokyungh** [comment]
Could you enable verbose logging [Logger](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L49)? Set log level to verbose and send the logs to us along with [meeting Id](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L123)?
