### ISSUE TITLE
Join Meeting

### ISSUE THREAD

**Issue by PatchDevel** [aws-samples/amazon-chime-react-native-demo#48]
Hello,

Thaks for your demo app.
I get the attend and meeting info from server.
The meeting is already created on the server.
Then how to join the meeting on the react native app.
There are startMeeting & stopMeeting but I can't see the joinMeeting.
So when I call the startMeeting(), it shows my phone camera, but can't see the another user.

How can I solve this problem?

**Comment by hokyungh** [comment]
If you already has meeting info, you can just get that info and pass it to [`startMeeting`](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/App.js#L67).

For video, could you check if [onAddVideoTIle](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/b72d6316f4ac00dd739bef1d099a246dd40c8e2b/src/containers/Meeting.js#L75) is called?

The basic idea is to create [`VideoTileObserver`](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/b72d6316f4ac00dd739bef1d099a246dd40c8e2b/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L25) and add to audiovideo facade by [addVideoTileObserver](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/b72d6316f4ac00dd739bef1d099a246dd40c8e2b/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L114).
