### ISSUE TITLE
getting error to startMeeting

### ISSUE THREAD

**Issue by kalpeshims** [aws-samples/amazon-chime-react-native-demo#49]
Hello, 

Facing issue on start meeting, 
i have desktop app, web app working fine, i recently cloned the "amazon-chime-react-native-demo" and setup the android environment and run the app, but it is not working infect it stuck at entry level, i mean not able to start meeting [NativeFunction.startMeeting](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/App.js#L67) getting null error. same api working fine in desktop and web app. so how to solve the issue.

![Screenshot_1611840496](https://user-images.githubusercontent.com/53003080/106173891-7209fa80-61ba-11eb-958e-3cbedadda9d4.png)

**Comment by zhinang-amazon** [comment]
Hi @kalpeshims,
Are you trying to run on a simulator? We documented [here](https://github.com/aws-samples/amazon-chime-react-native-demo#android-1) that we currently do not support x86 architecture/simulators.
