### ISSUE TITLE
Meeting Audio Coming from EarSpeaker and not from loud speaker

### ISSUE THREAD

**Issue by dumbre-prasad** [aws-samples/amazon-chime-react-native-demo#5]
I have followed all the steps from the readme and able to run the app in physical device,
Only issue i am facing is the Audio output is coming from Earpiece and nor from main loud speaker
Please help me with resolution

Device: Samsung J6( Android 10), Samsung M30 (Android 9)
OS: Android 10, Android 9
Version amazon-chime-sdk: 0.5.1
Version amazon-chime-sdk-media: 4.0.3

**Comment by hhemmati81** [comment]
I have the same issue.

**Comment by weichenhamzn** [comment]
Hi, to adjust the audio output, you could either use [DeviceController](https://aws.github.io/amazon-chime-sdk-android/amazon-chime-sdk/com.amazonaws.services.chime.sdk.meetings.device/-default-device-controller/index.html) provides as part of the Amazon SDK. Or [Android MediaRouter](https://developer.android.com/guide/topics/media/mediarouter) from official Android SDK. 

Since those SDK are only available in native language, you could also use some third-party React native package like [react-native-switch-audio-output](https://github.com/divergent-thinking/react-native-switch-audio-output) to manage output switching for you

**Comment by vaibhav11504561** [comment]
@dumbre-prasad , you can do trick 
import RNSwitchAudioOutput from 'react-native-switch-audio-output';
import AudioJackManager from 'react-native-audio-jack';

 var audioJackListener = AudioJackManager.addListener(({isPluggedIn}) => {if(isPluggedIn === false){
      RNSwitchAudioOutput.switchAudioOutput(true)
    }else{
      RNSwitchAudioOutput.switchAudioOutput(false)
    }});

**Comment by sacmii** [comment]
any updates on this issue

**Comment by dbuiza** [comment]
I have the same problem, could this issue be solved?

**Comment by vlad-dewitt** [comment]
Can someone help with this? Is there any updates on this issue?

**Comment by minziz1810** [comment]
+1

**Comment by kvntzn** [comment]
any update on the issue ?

**Comment by hokyungh** [comment]
@kvntzn 

Currently react native demo app doesn't have device selection. However, the SDK does support device selection. You would need to do modify [NativeBridge.kt](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L61) and [NativeBridge.m](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/NativeMobileSDKBridge.m#L90) to add another react exported for device controller. See the code for choosing device [Android code](https://github.com/aws/amazon-chime-sdk-android#use-case-4-choose-an-audio-device-by-passing-a-mediadevice-object) and [iOS code](https://github.com/aws/amazon-chime-sdk-ios#use-case-4-choose-audio-device-by-passing-mediadevice-object).

Then you can use it in the JS layer.

**Comment by kvntzn** [comment]
@hokyungh It works and  uses loud speaker but only for  the first meeting when you open the app,  subsequent meetings uses the ear speaker again. I've only  updated startAudioVideo function on the NativeMobileSDKBridge.
```
  private fun startAudioVideo() {
        meetingSession?.let {
            it.audioVideo.addRealtimeObserver(meetingObservers)
            it.audioVideo.addVideoTileObserver(meetingObservers)
            it.audioVideo.addAudioVideoObserver(meetingObservers)
            it.audioVideo.start()
            it.audioVideo.startRemoteVideo()


            val audioDevices = it.audioVideo.listAudioDevices().filter {
                it.type != MediaDeviceType.OTHER
            }
            val device = audioDevices.find { ad -> ad.type == MediaDeviceType.AUDIO_BUILTIN_SPEAKER }
            it.audioVideo.chooseAudioDevice(device!!)
        }
    }
```

**Comment by hokyungh** [comment]
@kvntzn It could be possible that you called it without meeting session is started? 
There is section on given code 
```
You should call chooseAudioDevice after the session started, or it'll be a no-op. You should also call chooseAudioDevice with one of the devices returned from listAudioDevices.
```

Do you mind putting chooseAudioDevice after [onAudioSessionStarted](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/7cf2944bd77068041260c62e0b00011bdacab06f/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L105) has been invoked? so either in JS layer or Bridge layer.

**Comment by kvntzn** [comment]
I thought it would work after it started  `it.audioVideo.start()`. Calling it after `onAudioSessionStarted  `works  thanks @hokyungh

**Comment by KONDO-Yuuki** [comment]
I found same issue in iOS.
And pull request is here 😄 

#93

**Comment by rnqayush** [comment]
@kvntzn @hokyungh  @zhinang-amazon  I have used the same code and getting some errors kindly help me to resolve this.

  private fun startAudioVideo() {
        meetingSession?.let {
            it.audioVideo.addRealtimeObserver(meetingObservers)
            it.audioVideo.addVideoTileObserver(meetingObservers)
            it.audioVideo.addAudioVideoObserver(meetingObservers)
            it.audioVideo.start()
            it.audioVideo.startRemoteVideo()


            val audioDevices = it.audioVideo.listAudioDevices().filter {
                it.type != MediaDeviceType.OTHER
            }
            val device = audioDevices.find { ad -> ad.type == MediaDeviceType.AUDIO_BUILTIN_SPEAKER }
            it.audioVideo.chooseAudioDevice(device!!)
        }
    }




![loud](https://user-images.githubusercontent.com/74084740/129369496-46d742e2-0e35-416e-af59-d07e1681fb33.png)

**Comment by zhinang-amazon** [comment]
Hi @rnqayush,
 Please look at @hokyungh 's comment here

> @kvntzn It could be possible that you called it without meeting session is started?
> There is section on given code
> 
> ```
> You should call chooseAudioDevice after the session started, or it'll be a no-op. You should also call chooseAudioDevice with one of the devices returned from listAudioDevices.
> ```
> 
> Do you mind putting chooseAudioDevice after [onAudioSessionStarted](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/7cf2944bd77068041260c62e0b00011bdacab06f/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt#L105) has been invoked? so either in JS layer or Bridge layer.

Regarding your errors, please make sure you have imported [`MediaDeviceType`](https://github.com/aws/amazon-chime-sdk-android/blob/4cc826f91d8c6ff76de99c13e4a4008bb673d07d/amazon-chime-sdk/src/main/java/com/amazonaws/services/chime/sdk/meetings/device/MediaDevice.kt#L102) where you are adding the invocation

**Comment by rnqayush** [comment]
@zhinang-amazon I did the import and error is resolved but got stuck at another point.
1- I am using  getActiveAudioDevice() to detect the current active audio device. It is returning me the response in format of    "deviceName (currentActiveStateOfAudio)".
2- I want to get this currentActiveStateOfAudio from the response which is there inside brackets .
3- I have used predifined functions like .contains(" ") and .length() but i am getting errors while using these functions. 

Kindly suggest some idea how i can get this currentActiveStateOfAudio which is there inside brackets  and also how i can resolve these errors after using predefined java functions in native module.
![zing1](https://user-images.githubusercontent.com/74084740/129535343-9de8ea55-f97e-4191-a6f4-86549913c190.png)
![zing2](https://user-images.githubusercontent.com/74084740/129535361-64e1404e-fc4e-4439-b692-2847a7c50d73.png)

**Comment by AlkanV** [comment]
hello @hokyungh is there any plan to implement or merge the PR for this feature?

**Comment by hokyungh** [comment]
Hi we do not have any plan soon to open PR for this feature, but you can reference https://github.com/aws-samples/amazon-chime-react-native-demo/commit/38ebabcc3a08dc284d8be28240dc2e7727dd087c and https://github.com/aws-samples/amazon-chime-react-native-demo/pull/93.
