### ISSUE TITLE
Chat component

### ISSUE THREAD

**Issue by IronTony** [aws-samples/amazon-chime-react-native-demo#50]
Hi all,

I didn't find, and I'd like to understand/know if there is the possibility to have a chat embedded in a component for React-Native, similar to the AttendeeList.

How to implement a chat component?
Does the SDK have a method to be used from a component?

All the best and thank you for the example

**Comment by zhinang-amazon** [comment]
Hi @IronTony,
This react native sample repo does not utilize all the features that are available in our native iOS and Android SDK. 
We will consider this as an enhancement.

**Comment by IronTony** [comment]
Hi @zhinang-amazon ,
thank you so much for the answer. Just to understand, the SDK has the chat in it, but the JS part doesn't? Am I right?

**Comment by zhinang-amazon** [comment]
Amazon Chime SDK for [iOS](https://github.com/aws/amazon-chime-sdk-ios#data-message) [Android](https://github.com/aws/amazon-chime-sdk-android#data-message) and [JS](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/03_API_Overview.md#9-send-and-receive-data-messages-optional) all have Data Message component that can be used for chat during a meeting session. We did not implement this in this React Native demo application.

**Comment by IronTony** [comment]
Awesome, thank you so much

**Comment by ashirkhan94** [comment]
Hi Team,

Any plans to implement chat component or Data Message component to react native. We are kind of stuck. Or please give a documentation on how to implement this we can attempt it from our side. We are using 0.13.0 version of Android SDK

**Comment by hokyungh** [comment]
Hi @ashirkhan94  https://github.com/aws-samples/amazon-chime-react-native-demo/pull/120 has been merged, could you try new master branch and see if data message works as expected?
