### ISSUE TITLE
Overlaying videos on Android

### ISSUE THREAD

**Issue by yboyer** [aws-samples/amazon-chime-react-native-demo#52]
When two videos are overlaid and the bottom video disables and then reactivates its tileId, the top video disappears.

Can you help me with this bug @hokyungh ? 🙏

**Comment by zhinang-amazon** [comment]
Hi @yboyer can you see if the information on this issue can help you?
https://github.com/aws-samples/amazon-chime-react-native-demo/issues/23

**Comment by yboyer** [comment]
It works ! Thanks a lot ! 🙏
