### ISSUE TITLE
Error: packages.add(new NativeMobileSDKBridgePackage()) in MainApplication.java. cannot find symbol class NativeMobileSDKBridgePackage

### ISSUE THREAD

**Issue by SuhailBt** [aws-samples/amazon-chime-react-native-demo#54]
Facing this issue while integrating into existing react-native project.

here is the sample code

package com.abc.test;

import  com.abc.test.NativeMobileSDKBridgePackage;

    @Override
    protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new ModuleRegistryAdapter(mModuleRegistryProvider));
      // packages.add(new KeychainPackage());
      packages.add(new NativeMobileSDKBridgePackage());
      return packages;
    }

NOTE: NativeMobileSDKBridgePackage.kt is present in the above import path.

**Comment by linsang21** [comment]
Hi, not sure what's your code structure, but if your `MainApplication.java` shares the same path with `NativeMobileSDKBridgePackage` class, then you shouldn't need to import the later class. Could you double check the package path and clean build?

**Comment by SuhailBt** [comment]
@linsang21 : I am attaching some screenshots to provide some additional information
![Screenshot from 2021-02-11 12-10-13](https://user-images.githubusercontent.com/65166275/107608711-b8ebfb80-6c62-11eb-904b-0c9b5aade513.png)
![Screenshot from 2021-02-11 12-10-31](https://user-images.githubusercontent.com/65166275/107608716-be494600-6c62-11eb-89a7-e01cda04c343.png)
![Screenshot from 2021-02-11 12-10-45](https://user-images.githubusercontent.com/65166275/107608725-c2756380-6c62-11eb-9c55-2695dcad6ad9.png)

**Comment by SuhailBt** [comment]
First is the structure where my package and mainApplication.java is. The second and third is the code inside the mainApplication.java file. As you can see I am not importing and on running the app I am getting the above-mentioned error.

**Comment by linsang21** [comment]
Thanks for the screenshots, could you also show me the `NativeMobileSDKBridgePackage.kt` file?

**Comment by SuhailBt** [comment]
It is same as in repo https://github.com/aws-samples/amazon-chime-react-native-demo
android/app/src/main/java/com/amazonaws/services/chime/rndemo

**Comment by linsang21** [comment]
OK, I think you could check the package path of `NativeMobileSDKBridgePackage.kt`, make sure it's `java.com.isql.squarecruit` as how it is configured in your project, instead of `com.amazonaws.services.chime.rndemo` as in the repo. The first line of that class should be:

```
package java.com.isql.squarecruit;
```

**Comment by SuhailBt** [comment]
Do I have to change it in NativeMobileSDKBridgePackage.kt file only or other files that I am using from demo as well(*.kt  files)? And what about adding java to the path. Because in MainApllication.java file, package is included as 
package com.isql.squarecruit;
Shall I change it there as well?

**Comment by linsang21** [comment]
> Do I have to change it in NativeMobileSDKBridgePackage.kt file only or other files that I am using from demo as well(*.kt files)? And what about adding java to the path. Because in MainApllication.java file, package is included as
> package com.isql.squarecruit;
> Shall I change it there as well?

Sorry, my mistake, should be `package com.isql.squarecruit;` for all files under the same directory of `MainApllication.java`.

**Comment by SuhailBt** [comment]
Even after making that change, I am getting the same error. Attaching screenshots for your reference.


![error](https://user-images.githubusercontent.com/65166275/108159156-6bf9a080-710c-11eb-9583-476cacdd8071.png)
![MainApplication](https://user-images.githubusercontent.com/65166275/108159160-6d2acd80-710c-11eb-81c6-ebe5961c1b3d.png)
![MeetingObservers](https://user-images.githubusercontent.com/65166275/108159162-6dc36400-710c-11eb-9bc2-e00e1f1b2fa0.png)
![NativeMobileSDKBridge](https://user-images.githubusercontent.com/65166275/108159164-6ef49100-710c-11eb-9da1-db74100ec96a.png)
![NativeMobileSDKBridgePackage](https://user-images.githubusercontent.com/65166275/108159167-6f8d2780-710c-11eb-8bef-a147f6b84cf1.png)
![RNEventEmitter](https://user-images.githubusercontent.com/65166275/108159170-7025be00-710c-11eb-9c58-98c90914bb67.png)
![RNVideoViewManager](https://user-images.githubusercontent.com/65166275/108159172-7156eb00-710c-11eb-97da-c5627b4d9c07.png)


Will .aar files that had to be copied in the libs folder inside android/app affect this in any way or maybe bridge.js file for that matter?

**Comment by SuhailBt** [comment]
Since these are Kotlin files, do I have to bridge them into react-native as well?

**Comment by zhinang-amazon** [comment]
Hi @SuhailBt 
You do not need the `import com.isql.squarecruit.NativeMobileSDKBridgePackage` in `MainApplication.java` if both files are under the same path.

Other than this, the packages and paths look right to me. Can you try to clean build? If you are still having this issue, do you mind putting any relevant code in a repo and share with us?

We understand our set up documentation is missing some information and will address that.

**Comment by Pcartau** [comment]
Following those steps, I still have the same issue.

I forked my project with minimal code to show you @zhinang-amazon 

https://github.com/Pcartau/aws-react-native-test-fork

Hope it helps.

(ps: didn't clean package.json, sorry about that)

**Comment by zhinang-amazon** [comment]
@Pcartau 
Thanks for posting your repo. I was able to find the root cause for your issue and hopefully it helps @SuhailBt as well.
1. Your repo did not configure Kotlin properly, so the .kt source files are not built properly (Gradle build error is not very helpful in this case). To fix this, at the top of `android/app/build.gradle`, add:
```
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
```
In `android/build.gradle`, add the following under `buildscript {`:
```
ext.kotlin_version = '1.3.71'
```
and the following under `dependencies (`
```
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
```
2. You did not copy over `MeetingObservers.kt` and `RNVideoViewManager.kt`. 
To fix: Copy those two and adjust the package and import path as needed.

3. I'm not sure what `amazon-chime-sdk-media.aar` and `amazon-chime-sdk.aar` version you are using and replaced with v0.8.2.

I was able to build and run on an Android device after making these changes with your repo. I saw the "TEST" message :) 
Clearly our setup documentation can be improved, and our team will update the README accordingly.

@SuhailBt Let us know if this is what's causing your build issue.

**Comment by Pcartau** [comment]
Thanks a lot for your answers (on both issues) !
I'll check all of this and I come back to you.

Btw if this repo accept pull requests I would be delighted to help If I can !

**Comment by Pcartau** [comment]
After following your feedback during the build phase I found myself with 2 errors:

`MeetingObservers.kt: (93, 5): 'onVideoTileSizeChanged' overrides nothing`
`NativeMobileSDKBridge.kt: (141, 75): Too many arguments for public constructor MeetingSessionCredentials(attendeeId: String, joinToken: String) defined in com.amazonaws.services.chime.sdk.meetings.session.MeetingSessionCredentials`

I can remove the first one by commenting the function (don't know if is a good idea but don't need a listener on tile for now)
But the second one is weird, because based on [DOC](https://aws.github.io/amazon-chime-sdk-android/amazon-chime-sdk/com.amazonaws.services.chime.sdk.meetings.session/-meeting-session-credentials/index.html) it seems to be okay..

Do you have an idea ?

**Comment by SuhailBt** [comment]
@zhinang-amazon:I will come back after testing the steps provided. Thanks a lot.

**Comment by hokyungh** [comment]
@Pcartau What SDK version are you using?

**Comment by Pcartau** [comment]
@hokyungh 

`react-native-cli: 2.0.1`
`react-native: 0.63.4`

I run on MacOS, without android studio from memory, or minimal required because of disk space

**Comment by hokyungh** [comment]
@Pcartau sorry for confusion. I mean Chime Mobile SDK and Chime Media SDK version described [here](https://github.com/aws-samples/amazon-chime-react-native-demo#2-add-sdk-binaries-to-the-projec)

**Comment by Pcartau** [comment]
@hokyungh 

I use the latest version `0.8.2`. I just started implementing the lib.
The thing is when I try to clone the demo repo in order to build, it works on IOS but I still have kotlin build errors on Android

**Comment by timorss** [comment]
> @Pcartau
> Thanks for posting your repo. I was able to find the root cause for your issue and hopefully it helps @SuhailBt as well.
> 
> 1. Your repo did not configure Kotlin properly, so the .kt source files are not built properly (Gradle build error is not very helpful in this case). To fix this, at the top of `android/app/build.gradle`, add:
> 
> ```
> apply plugin: 'kotlin-android'
> apply plugin: 'kotlin-android-extensions'
> ```
> 
> In `android/build.gradle`, add the following under `buildscript {`:
> 
> ```
> ext.kotlin_version = '1.3.71'
> ```
> 
> and the following under `dependencies (`
> 
> ```
> classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> ```
> 
> 1. You did not copy over `MeetingObservers.kt` and `RNVideoViewManager.kt`.
>    To fix: Copy those two and adjust the package and import path as needed.
> 2. I'm not sure what `amazon-chime-sdk-media.aar` and `amazon-chime-sdk.aar` version you are using and replaced with v0.8.2.
> 
> I was able to build and run on an Android device after making these changes with your repo. I saw the "TEST" message :)
> Clearly our setup documentation can be improved, and our team will update the README accordingly.
> 
> @SuhailBt Let us know if this is what's causing your build issue.

same problem...
Any final solution?

**Comment by SuhailBt** [comment]
@timorss @zhinang-amazon 

Attaching the screenshot for the error I am getting.
![Uploading Screenshot from 2021-02-22 11-02-43.png…]()

**Comment by SuhailBt** [comment]
@zhinang-amazon  The import and package issue I was getting earlier is resolved I guess, but getting this error on running 
./gradlew assembleRelease

**Comment by SuhailBt** [comment]
![Uploading Screenshot from 2021-02-22 11-02-43.png…]()

**Comment by SuhailBt** [comment]
Screenshot is not getting uploaded I guess, copy pasting the error

 /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (140, 41): Type mismatch: inferred type is String but CreateMeetingResponse was expected
e: /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (141, 21): Type mismatch: inferred type is MeetingSessionCredentials but CreateAttendeeResponse was expected
e: /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (142, 21): Type mismatch: inferred type is MeetingSessionURLs but URLRewriter /* = (String) -> String */ was expected

FAILURE: Build failed with an exception.

**Comment by timorss** [comment]
Same here

> Screenshot is not getting uploaded I guess, copy pasting the error
> 
> /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (140, 41): Type mismatch: inferred type is String but CreateMeetingResponse was expected
> e: /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (141, 21): Type mismatch: inferred type is MeetingSessionCredentials but CreateAttendeeResponse was expected
> e: /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (142, 21): Type mismatch: inferred type is MeetingSessionURLs but URLRewriter /* = (String) -> String */ was expected
> 
> FAILURE: Build failed with an exception.

**Comment by timorss** [comment]
I opened a new react-native project,
followed the above,
getting new error...

![kerror](https://user-images.githubusercontent.com/13855015/108671493-34626e00-74e9-11eb-8c43-2d37a4f64816.JPG)

**Comment by Pcartau** [comment]
If you guys have time to resolve this issue I am free all day if you want to join me for screen sharing / live call / whatever.
Just ping me @ paul.cartau@gmail.com

**Comment by AlysCole** [comment]
> Same here
> 
> > Screenshot is not getting uploaded I guess, copy pasting the error
> > /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (140, 41): Type mismatch: inferred type is String but CreateMeetingResponse was expected
> > e: /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (141, 21): Type mismatch: inferred type is MeetingSessionCredentials but CreateAttendeeResponse was expected
> > e: /home/lenovo/ISPL/Workspace/react-partner/android/app/src/main/java/com/ispl/squarecruit/NativeMobileSDKBridge.kt: (142, 21): Type mismatch: inferred type is MeetingSessionURLs but URLRewriter /* = (String) -> String */ was expected
> > FAILURE: Build failed with an exception.

I've been getting this same error on my end. If you guys find a solution, let us know! Racking my brain over what could be causing this.

**Comment by SuhailBt** [comment]
@AlysCole @timorss 
I believe it has something to do with these imports in NativeMobileSDKBridge.kt

import com.amazonaws.services.chime.sdk.meetings.session.DefaultMeetingSession
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSession
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSessionConfiguration
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSessionCredentials
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSessionURLs
import com.amazonaws.services.chime.sdk.meetings.session.defaultUrlRewriter
import com.amazonaws.services.chime.sdk.meetings.utils.logger.ConsoleLogger
import com.amazonaws.services.chime.sdk.meetings.utils.logger.LogLevel

**Comment by AlysCole** [comment]
Figured it out on my end.

Turns out I'd installed version 0.11.0 of the SDK [binaries](https://github.com/aws/amazon-chime-sdk-android/releases/tag/v0.11.0). I replaced the binaries in my local repo with version [0.8.2](https://github.com/aws-samples/amazon-chime-react-native-demo#2-add-sdk-binaries-to-the-project) (as stated in the README.md) and re-ran `npx react-native run-android` in my project root directory. 

It builds correctly now.

**Comment by Pcartau** [comment]
OMG I'm so confused !!
Indeed I certainly DL 0.11.0 too !
![Screenshot 2021-02-23 at 11 15 25](https://user-images.githubusercontent.com/33002088/108829435-78787000-75c8-11eb-96da-6bf939d423b9.png)

That's because this link redirects to v 0.11.0...

**Comment by SuhailBt** [comment]
Works for me as well. Thanks

**Comment by timorss** [comment]
getting new Error, maybe someone got into it?
![chime-error](https://user-images.githubusercontent.com/13855015/108963534-e71a0400-7682-11eb-8df9-a33bdc9021d2.JPG)

**Comment by timorss** [comment]
Oh I created so many react native versions to solve it,
and this time I didn't set 
      flatDir {
        dirs 'libs'
        }
        
But i got this again :
![again](https://user-images.githubusercontent.com/13855015/108968663-ba1d1f80-7689-11eb-97f6-e15bff78927d.JPG)

**Comment by SuhailBt** [comment]
@timorss : 
Check the above comments, this issue is mentioned there. Try adding kotlin into your project

**Comment by timorss** [comment]
I did all the steps above, Realy struggling here....
![kotlin1](https://user-images.githubusercontent.com/13855015/108989332-26a21980-769e-11eb-81f4-1cfa5164190f.JPG)
![kotlin2](https://user-images.githubusercontent.com/13855015/108989337-27d34680-769e-11eb-945b-89ba15ad6b9e.JPG)
![er](https://user-images.githubusercontent.com/13855015/108989435-41748e00-769e-11eb-8484-6b09514e741e.JPG)

**Comment by timorss** [comment]
OK I had to add in app/build.gradle:
    packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
    }
    
   Please add it to your setup documentation as well...

**Comment by SuhailBt** [comment]
I am getting a new error when trying to invoke start meeting. Anyone else getting it ?

Couldnot invoke NativeMobileSDKBridge.startMeeting

Attaching screenshot.

![Screenshot from 2021-02-24 18-01-46](https://user-images.githubusercontent.com/65166275/109001062-772f6c00-76ca-11eb-92a6-504f0d6bfc87.png)

**Comment by Devo-React** [comment]
I am also getting same error.

**Comment by SuhailBt** [comment]
@Devo-React : Follow this issue regarding that, since this one is closed
https://github.com/aws-samples/amazon-chime-react-native-demo/issues/60

**Comment by john-raymon** [comment]
I'm experiencing the same issues seen here. Is there anyway to update the README to include the import references changes needed to be done to get it working? I've changed all the imports mentioning `com.amazonaws.services.chime.sdk` and `com.amazonaws.services.chime.rndemo` with my own packages `com.spacegramapp` and still getting "unresolved reference" errors.

**Comment by SuhailBt** [comment]
@john-raymon: Follow all the above-mentioned steps, that should solve the issue
