### ISSUE TITLE
Joining 2 meeting simultaneously 

### ISSUE THREAD

**Issue by ruggero-balteri** [aws-samples/amazon-chime-react-native-demo#55]
Hi!
I would like to record the individual audio stream a 2-person-meeting. Let us call the 2 attendees A and B.

From the documentation, `the media service group mixes audio together from each attendee and sends the mix to each recipient, after subtracting their own audio from the mix.` 

Hence, the only solution I envision is to make 
A join meeting "common" and meeting "alpha"
B join meeting "common" and meeting "beta"

Then, I plan to create 2 participants as "recorder" and let them record "alpha" and "beta" meetings.

If I try to join 2 meetings I get the error message 
"Failed to start meeting: error illegalState"

Is it possible to join 2 meetings simultaneously?

**Comment by linsang21** [comment]
Hi there, if I understand correctly, you want to record the local attendee's audio? Do you consider to capture the audio from the microphone to achieve that, so that you won't get the other person's voice?

**Comment by ruggero-balteri** [comment]
My apologies for the late answer!
Thank you very much for your insight, yes! you are correct!
Simply using https://github.com/dooboolab/react-native-audio-recorder-player makes my life much easier!

Thank you again!
