### ISSUE TITLE
Voip audio call 

### ISSUE THREAD

**Issue by SpurtiB** [aws-samples/amazon-chime-react-native-demo#56]
Hi,
Can we implement only voice calling feature using this sdk?

In my react native mobile application registered user A needs to do initiate only normal voice call to another registered user B by clicking a button and user B phone should get a ring(sound). Normal conversation will go on between these two users. Is this feature possible using this  Amazon Chime SDK ?

In the demos I did not found how to initiate immediate call by clicking on a button and how does the receiver gets notified by a ring.

**Comment by zhinang-amazon** [comment]
Hi @SpurtiB 
In order to achieve this with Amazon Chime SDK, once user A initiates the call and create a [MeetingSession](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/session/MeetingSession.swift), it's builders' responsibility to send a VoIP Push Notification to user B so that B can join the same MeetingSession from the client side.

**Comment by SpurtiB** [comment]
what is builders here?

**Comment by zhinang-amazon** [comment]
Sorry, builders are SDK consumers that are building the mobile applications.

**Comment by SpurtiB** [comment]
Is there any demo source code for this audio calling feature or any documentation would be helpful.

**Comment by zhinang-amazon** [comment]
We have this [blogpost](https://aws.amazon.com/blogs/business-productivity/how-to-integrate-apples-callkit-into-ios-applications-using-the-amazon-chime-sdk/) on client side iOS CallKit integration, but the server side Push Notification sending is not part of the blogpost.

**Comment by SpurtiB** [comment]
Which framework should we use for android app integration?

**Comment by SpurtiB** [comment]
Currently my react native project is integrated with amazon auth.
Going further with the integration with amazon chime, how to integrate my react native app with my amazon chime account? Is there any document available regarding basic settings?

**Comment by linsang21** [comment]
Hi @SpurtiB, if I understand correctly, you want to implement an app that:
1) Maintains a user pool
2) An user can initialize a meeting and directly call another user
3) Users exchanges audio over the meeting

However, Amazon Chime Mobile SDK is a client library only covers 3). If you follow the [How to Run the React Native Demo Application](https://github.com/aws-samples/amazon-chime-react-native-demo#how-to-run-the-react-native-demo-application), you can get the examples on both platforms on how to start the meeting after "the other user answer the ring".

This is the [server side code](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js) supporting this demo, you can see that's where it interacts with [Amazon Chime APIs](https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations.html) or other AWS service APIs, such as createMeeting, createAttendee. To achieve 1) and 2), you might need to implement the corresponding functionalities on the server side, and there should be multiple way to achieve so. 

These docs may be useful:
* [Using the Amazon Chime SDK](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html)
* [Creating meetings with the Amazon Chime SDK](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html)
* [Amazon Chime SDK event notifications](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-notifications.html)
* [How Amazon Chime works with IAM](https://docs.aws.amazon.com/chime/latest/ag/security_iam_service-with-iam.html)

**Comment by SpurtiB** [comment]
> This is the [server side code](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js) supporting this demo, you can see that's where it interacts with [Amazon Chime APIs](https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations.html) or other AWS

exactly I was looking for this...thanks.
