### ISSUE TITLE
Implementation of aws chime into existing react native project doesn't work [bug 🐛]

### ISSUE THREAD

**Issue by Pcartau** [aws-samples/amazon-chime-react-native-demo#57]
### Problem

When I'm trying to implement aws chime into existing react native project by following all steps, I've got those errors:

Android: on build phase
`.../MainApplication.java:29: error: cannot find symbol
packages.add(new NativeMobileSDKBridgePackage());`
`symbol: class NativeMobileSDKBridgePackage`
  
 IOS: build is good, but got this error
 `Invariant Violation: Native module cannot be null.`

Indeed my NativeModules is empty: `{}`

 ### How to reproduce
 
Follow all the steps of the tutorial.
Use files listed in tutorial

### Solution needed

I cleaned build / cache, tried manual react-native link, but nothing worked.
Where am I wrong ?

### Additional informations

React native: [react-native-cli: 2.0.1 - react-native: 0.63.4]
Env: [MacOS, Android devide, IOS Simulator iPhone 11]

Ps: someone seems to have the same issue https://stackoverflow.com/questions/66097914/error-while-importing-nativemobilesdkbridgepackage-when-using-amazon-chime-integ

**Comment by zhinang-amazon** [comment]
Hi @Pcartau,
For the Android side, please follow this issue: https://github.com/aws-samples/amazon-chime-react-native-demo/issues/54
For the iOS side, when are you see the error? `Invariant Violation: Native module cannot be null.`
Can you share how you are linking or referencing the iOS files in this repo?

**Comment by Pcartau** [comment]
Hi @zhinang-amazon and thanks for your answer !

Thanks for the Android side (and my bad for didnt see it before posting this issue), I'll check !

For IOS part, this error comes on `Bridge.js` file on line 20 `const _eventEmitter = new NativeEventEmitter(NativeModules.NativeMobileSDKBridge);` when `NativeModules` is equals to an empty object `{}`.
For the linking, I followed IOS integration tutorial (I took without bitcode support for the libs) and linked it via Xcode (just followed tutorial).
Then I took all the files needed and put it in my `root` folder
![Screenshot 2021-02-18 at 09 08 09](https://user-images.githubusercontent.com/33002088/108324989-e2f46f00-71c8-11eb-9aea-4501518342c4.png)

The weird part is when I was doing `pod install`, it seems that those lib weren't detected
The files `NativeMobileSDKBridge` `MeetingObserver ` `RNVideoView ` etc.... contains same code as the github repo.

Tell me if you need more informations !

**Comment by zhinang-amazon** [comment]
For the iOS side, did you add those NativeMobileSDKBridge MeetingObserver RNVideoView etc through Xcode?
If you are adding to existing react native repo, you should have something similar to our `RNDemo.xcworkspace`
Open that in Xcode and cross reference with our `RNDemo` project and see if you are missing any of those ObjC files.
![Screen Shot 2021-02-18 at 10 26 07 AM](https://user-images.githubusercontent.com/62256490/108403624-c578d280-71d3-11eb-8bf5-f289ece3179f.png)

**Comment by Pcartau** [comment]
I'll check after dinner and I come back to you !

**Comment by Pcartau** [comment]
Indeed I didn't add my files through Xcode..

Here's my folder structure now: 
![Screenshot 2021-02-18 at 22 01 58](https://user-images.githubusercontent.com/33002088/108421064-ed4c5280-7234-11eb-86b1-0665f7d24834.png)

Problem is it doesn't build anymore..
I've seen that our Podfile are not similar, maybe something on this side ?
Here is my Podfile: https://pastebin.com/m4FNMT2f

Here's the error:

`The following build commands failed:
	CompileC /Users/pcartau/Library/Developer/Xcode/DerivedData/NoAppNameFront-cetuvvdraorpvgffwajwmwupdcsj/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperRSocketResponder.o /Users/pcartau/NoAppNameFront/ios/Pods/Flipper/xplat/Flipper/FlipperRSocketResponder.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

Again thanks for your time !

**Comment by zhinang-amazon** [comment]
Hi @Pcartau,
I don't think this issue is related to our Amazon Chime SDK. Can you try to mirror our RNDemo Podfile and see if it has something to do with how Flipper and its dependencies are being compiled?

**Comment by Pcartau** [comment]
Indeed Flipper was causing issue. Now it compile and works. Thank you !
