### ISSUE TITLE
createMeeting, createAttendee 

### ISSUE THREAD

**Issue by Devo-React** [aws-samples/amazon-chime-react-native-demo#58]
I did run the amazon-chime-react-native-demo using serverless code with SAM CLI it and worked well.

Implementing same meeting feature in my react native project.
using Amazon Chime mobile SDK iOS and Android both.

I have followed the [all the steps here.](https://github.com/aws-samples/amazon-chime-react-native-demo#how-to-integrate-the-amazon-chime-sdk-into-your-existing-react-native-application) 

Now I am stuck in creating AWS service APIs such as createMeeting, createAttendee. 

To achieve this I have written [this code](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js) in my  src/utils/Api.js 

 npx react-native run-ios

  ERROR    TypeError: undefined is not a constructor (evaluating 'new _awsSdk.default.Chime({
    region: 'us-east-1'
  })')
 ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

Is src/utils/Api.js  is the correct place to write server side code createMeeting, createAttendee and so on?
If correct why am I getting above error?
If incorrect where should I write create meeting and other API related code for my app? 
Because in my app users will create the meeting and choose the attendee.

**Comment by hokyungh** [comment]
@Devo-React react-native is mobile cross platform source code, so if you are trying to write server side code, you would need to start new project in your preferred language and implemented (server)[https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html].

**Comment by Devo-React** [comment]
> you would need to start new project in your preferred language and implemented [chime doc](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html) in the preferred language.

Do I need to follow below steps: 
1. write server side code in separate project in any preferred language
2. Deploy that code to get SERVER_URL
3. Use that url in the SERVER_URL and SERVER_REGION in src/utils/Api.js

Are these above steps correct?

**Comment by hokyungh** [comment]
That is correct step with demo application. If you want to have custom logic, for example, having login and get some token, the flow will be
1. Login
2. Get token
3. Make request to server url to create meeting and attendee
4. Use Chime Mobile SDK to join meeting after getting [`CreateMeeting`](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html) Response and pass those information to `DefaultMeetingSession`

These implementation changes based on your logic. For example, the reason why we require SERVER_REGION is to pass to the server [region parameter](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L38). You can also take this within your app and pass to JS server. These logics can change based on your need and your server.

The server also [createMeeting](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L67). Any reason why you would like to move that logic to client?

**Comment by Devo-React** [comment]
> . Any reason why you would like to move that logic to client?

Basically I am creating a voip/voice calling simple app. User logs in (using aws Auth) and clicks on call button which generates voice call to a random user. 

So have planned to create meeting and Attendee when user clicks on call button. 
Because user has no scope to enter here any meeting id and attendee info.

**Comment by hokyungh** [comment]
@Devo-React I am not sure if that is currently possible. It looks there is no Chime SDK in the Android to createMeeting unless you call HTTP request directly with payload https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html. In this case, you might need to [sig4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html), yourself. I'll update the comment if there is any update on it.
