### ISSUE TITLE
Audio only meeting

### ISSUE THREAD

**Issue by e-nouri** [aws-samples/amazon-chime-react-native-demo#59]
How can i get the audio feed into a react native component for playing only the audio. In addition to that, is there a way to leave the audio running while the app in background (both ios and android). The same applies for the mic, I may need to run some filters before piping the audio stream to Chime SDK.

FYI I am running those calls inside redux-saga, not using any hooks or lifecycle methods.

Any guidance and pointers is much appreciated.

**Comment by hokyungh** [comment]
@e-nouri in order for the app to run in background, you would need to implement [Service](https://developer.android.com/guide/components/services) in the Android layer to make sure that it continues to run without OS killing it. 

For iOS, I believe you could add [background modes](https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio)
 and also check Voice Over IP

Let me know if this works.

**Comment by john-raymon** [comment]
Hey, I'm also trying to figure out how to start a meeting without requiring video permissions, in other words for playing audio only.
