### ISSUE TITLE
Is there a way to start a meeting without asking for video permissions?

### ISSUE THREAD

**Issue by john-raymon** [aws-samples/amazon-chime-react-native-demo#63]
I'm building an app that currently doesn't require nor utilize video, is there a way to not require video permissions in order to start a meeting?

**Comment by hokyungh** [comment]
Hello @john-raymon . Video permission is not required to start the meeting, but audio permission is currently needed to start the meeting. You can test it by removing [Camera Permission](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/b72d6316f4ac00dd739bef1d099a246dd40c8e2b/android/app/src/main/AndroidManifest.xml#L10)  and [Camera Permission](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/b72d6316f4ac00dd739bef1d099a246dd40c8e2b/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L54). Also you can remove NSCameraUsageDescription from iOS to test. 

Let me know if this works. Thanks.

**Comment by john-raymon** [comment]
Thank you that works!
