### ISSUE TITLE
video in meeting is mirror image not the actual one (non-mirrored)

### ISSUE THREAD

**Issue by SuhailBt** [aws-samples/amazon-chime-react-native-demo#66]
After joining the meeting, the video is coming as mirrored. Need it in normal way

**Comment by linsang21** [comment]
Hi @SuhailBt,
The SDK dose not mirror the video at sending and receiving end, but app can mirror the preview video. I did a testing across RN-Android demo and native Android demo. The receiving video is the actual one, as in how it got sent from the source. 

* Join a meeting from the RN demo as attendee "G"
* Join the same meeting from the native demo as attendee "l"
* "l" enable the video using **back camera**
![image-1(2)](https://user-images.githubusercontent.com/55719628/111543236-ffd08380-872f-11eb-986e-3a2cfa1502f8.jpg)
* "G" receive the video as the same, no mirrored
![image-f02f95f1-1c98-4e0a-8484-378e498ca693](https://user-images.githubusercontent.com/55719628/111543296-1676da80-8730-11eb-800d-e37492e7c1de.jpg)

* "l" switch to **front camera**, **NOTE** the [demo app](https://github.com/aws/amazon-chime-sdk-android/blob/master/app/src/main/java/com/amazonaws/services/chime/sdkdemo/adapter/VideoAdapter.kt#L142) (not SDK) sets local video tile as mirrored only for preview, what being sending to the server is the non-mirrored version, which I think is where you got confused.
![image-1(1)](https://user-images.githubusercontent.com/55719628/111543559-75d4ea80-8730-11eb-9482-928085ff7ba6.jpg)
* "G" received the non-mirrored version as expected
![image-ba9bd504-6c13-41ff-9c20-58012696def6](https://user-images.githubusercontent.com/55719628/111544170-4f637f00-8731-11eb-954b-7fb42e1b4957.jpg)

**Comment by SuhailBt** [comment]
I am using the front camera and using the complete code present in the demo. I did not do any changes to that code and get the video image as mirrored. Would you suggest where it could be going wrong and where should I make changes to fix it?

**Comment by SuhailBt** [comment]
And the screenshot you shared using the front camera is mirrored I believe, if I am not worng.

**Comment by linsang21** [comment]
As I suggested, for this test, the front camera is only mirrored at the **sender** end for preview only (means it sends the none-mirrored version to the backend, and RN is showing the non-mirrored version as the correct behavior). 

If this is not your observation, the same format of screenshot and description would be helpful.

**Comment by SuhailBt** [comment]
@linsang21 Yes it is mirrored at the sender end only. But I don't want it to be mirrored. What are the changes I should do to override that default behavior?
And you are correct receiver receives the same sent from sender side

**Comment by linsang21** [comment]
The default behavior is none-mirrored. You don't have to do anything except for creating a DefaultVideoRenderView ([iOS](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/DefaultVideoRenderView.swift), [Android](https://github.com/aws/amazon-chime-sdk-android/blob/master/amazon-chime-sdk/src/main/java/com/amazonaws/services/chime/sdk/meetings/audiovideo/video/DefaultVideoRenderView.kt)), and bind it with your local video tile.

The only reason it's mirrored in the above screenshots (or maybe in your observation) is our native **Demo App** called the mirror function ([iOS demo](), [Android demo](https://github.com/aws/amazon-chime-sdk-android/blob/6def615e4de8e5734c74ba71376d36bee450e636/app/src/main/java/com/amazonaws/services/chime/sdkdemo/adapter/VideoAdapter.kt#L142)) to mirror it for review, because it's more natural this way (imaging you're using the front camera on the default camera app, it'd be like looking at a mirror). If you don't call that function, it's by default none-mirrored. 

However, this react native demo does not mirror the video, so if you follow it, front camera won't mirror.

**Comment by SuhailBt** [comment]
Just FYI I am using it in react-native(Integrating into the existing app). The links you shared are for android. Just to make sure we are on same page

**Comment by SuhailBt** [comment]
Because as I mentioned, I am using the same code as present in the demo. I did not change any flow to make the video mirrored.

**Comment by SuhailBt** [comment]
@linsang21 Anything regarding this?

**Comment by zhinang-amazon** [comment]
Hi @SuhailBt,
What @linsang21 is saying is that local front camera view from RN demo in this repo is not mirrored. Local front camera view from iOS/Android demo in iOS and Android SDK are mirrored. 

Are you trying to show the local front camera view same as our RN demo, or our iOS/Android demo? I think there is some confusion around what is mirrored.

**Comment by SuhailBt** [comment]
@zhinang-amazon : Trying to explain it in another way. 
When I move my face towards the left, the movement is kind of the opposite in the video. I have no idea how to explain that by sharing the screenshot. Hope you understand what I mean.
And in this demo, I can see only one way of displaying the video. And that is the way I am using it. Sharing a screenshot of my file structure. Hope that helps to avoid confusion.
![Screenshot from 2021-03-29 12-59-36](https://user-images.githubusercontent.com/65166275/112801625-c16f8880-908e-11eb-9167-2b1cfa261035.png)

**Comment by SuhailBt** [comment]
using this class to bind and unbind video

RNVideoRenderView

**Comment by SuhailBt** [comment]
> ou trying to show the local front camera view same as our RN demo

I am using local front camera view same as RN demo.

**Comment by SuhailBt** [comment]
> Hi @SuhailBt,
> The SDK dose not mirror the video at sending and receiving end, but app can mirror the preview video. I did a testing across RN-Android demo and native iOS demo. The receiving video is the actual one, as in how it got sent from the source.
> 
> * Join a meeting from the RN demo as attendee "G"
> * Join the same meeting from the native demo as attendee "l"
> * "l" enable the video using **back camera**
>   ![image-1(2)](https://user-images.githubusercontent.com/55719628/111543236-ffd08380-872f-11eb-986e-3a2cfa1502f8.jpg)
> * "G" receive the video as the same, no mirrored
>   ![image-f02f95f1-1c98-4e0a-8484-378e498ca693](https://user-images.githubusercontent.com/55719628/111543296-1676da80-8730-11eb-800d-e37492e7c1de.jpg)
> * "l" switch to **front camera**, **NOTE** the [demo app](https://github.com/aws/amazon-chime-sdk-android/blob/master/app/src/main/java/com/amazonaws/services/chime/sdkdemo/adapter/VideoAdapter.kt#L142) (not SDK) sets local video tile as mirrored only for preview, what being sending to the server is the non-mirrored version, which I think is where you got confused.
>   ![image-1(1)](https://user-images.githubusercontent.com/55719628/111543559-75d4ea80-8730-11eb-9482-928085ff7ba6.jpg)
> * "G" received the non-mirrored version as expected
>   ![image-ba9bd504-6c13-41ff-9c20-58012696def6](https://user-images.githubusercontent.com/55719628/111544170-4f637f00-8731-11eb-954b-7fb42e1b4957.jpg)

If you observe in these screenshots, the one taken from the rare camera, at sender side image content is tilted slightly towards left and at the receiver end, it is slightly towards right and same for the front camera as well. the lamp is from the left side of the image from the sender and on the right side at the receiver end. That is the problem I am talking about. It is kind of opposite and not completely mirrored. Hope you got the issue now.

**Comment by hokyungh** [comment]
Hi @SuhailBt could you try this?

on RNVideoViewManager.kt file
Add following 
```
    @ReactProp(name = "mirror")
    fun setMirror(renderView: DefaultVideoRenderView, mirror: Boolean) {
        renderView.mirror = mirror
    }
```

And for your local render view, add mirror property. For instance, for our code [code](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/containers/Meeting.js#L159),
it will be 
```
 <RNVideoRenderView style={styles.video} key={tileId} tileId={tileId} mirror={true}/>
```

**Comment by SuhailBt** [comment]
@hokyungh Thanks a lot. That solved my issue.

**Comment by Thuku** [comment]
@SuhailBt How did you achieve switching to back camera?

**Comment by AlkanV** [comment]
@hokyungh how can i achive same functionality on iOS side? is there any way to implement setMirror function on iOS obj-c side?

**Comment by AlkanV** [comment]
hello @hokyungh could you please help me on mirroring the local camera view on iOS side?

thanks

**Comment by KhrisnaIndrawan** [comment]
> @hokyungh how can i achive same functionality on iOS side? is there any way to implement setMirror function on iOS obj-c side?

> hello @hokyungh could you please help me on mirroring the local camera view on iOS side?
> 
> thanks

For iOS you can change the value like this

`let localVideoRenderView = DefaultVideoRenderView(frame: self.localVideoRenderView.frame)
   localVideoRenderView.mirror = true`
