### ISSUE TITLE
Dear Amazon Team,

### ISSUE THREAD

**Issue by SIDDIQUISAZID** [aws-samples/amazon-chime-react-native-demo#67]
Greetings..!!

I am writing this note for seeking your help. I am developing a mobile application using the "React Native" technology in which we're giving the features of screens sharing and calling so for the same we're using the amazon chime service. We've successfully done the calling part but facing issues and errors in "screen sharing", so for the same, we want your contribution and guidance on an urgent basis.
I am sure that you'll help us. Here I am sharing some screenshots please look into this and let us know how can we do this screens sharing feature.

Thanks..!!

**Comment by idmobileacc** [comment]
Hi, 

Don't see your screenshots. Please add more details to understand your issue better. Thank you.

**Comment by linsang21** [comment]
Hi @SIDDIQUISAZID, could you provide more data by filling the form below? And on which platform you had this issue? How did you integrate with the system API to record your screen?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
If applicable, add logs from logcat to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Test environment Info (please complete the following information):**
 - Device: [e.g. Pixel3]
 - OS: [e.g. Android 10]
 - Version amazon-chime-sdk: [e.g. 0.4.0]
 - Version amazon-chime-sdk-media: [e.g. 0.4.0]

**Additional context**
Add any other context about the problem here.

**Comment by SIDDIQUISAZID** [comment]
Dear Support,

Thanks for your revert..!

Issue is when we're trying to call "screenShareTile: tileState.tileId" is always giving null, due to this we're unable to share the screen and also the view are return false so the view are not showing.


!!this.state.screenShareTile &&    
          <React.Fragment>
            <Text style={styles.title}>Screen Share</Text>
            <View style={styles.videoContainer}>
              <RNVideoRenderView style={styles.screenShare} key={this.state.screenShareTile} tileId={this.state.screenShareTile} />
            </View>
          </React.Fragment>,

<img width="865" alt="Screenshot 2021-03-23 at 10 50 04 AM" src="https://user-images.githubusercontent.com/20954375/112102801-cfc12e80-8bce-11eb-8fa6-f3d2fecb695d.png">
<img width="929" alt="Screenshot 2021-03-23 at 11 41 34 AM" src="https://user-images.githubusercontent.com/20954375/112102807-d354b580-8bce-11eb-81be-2946608ec51c.png">


{
  "name": "RNDemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by linsang21** [comment]
Is the 'screenShareTile' referring to the local preview of the screen share, or the screen share from other attendee?

More specially, if there's 2 attendees A and B.
When A shares the screen, there will NOT be `onAddVideoTile` event for its own sharing video.
However B will receive the event for A's sharing video.

**Comment by SIDDIQUISAZID** [comment]
When we host meeting from web, it has the functionality to share screen and the shared screen is also reflected in app side, however the app side do not have the functionality to share the screen.

**Comment by hokyungh** [comment]
Hi @SIDDIQUISAZID we have screen share on the app. React Native might not have example of it, but you can take a look at [android](https://github.com/aws/amazon-chime-sdk-android/blob/master/guides/content_share.md) and [ios](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/content_share.md)

**Comment by SIDDIQUISAZID** [comment]
Dear Support,

Thanks for your revert..!

Issue is when we're trying to call " Android naive code on in react native " is always giving a pop for start screen share the I click on start then its not working, I am sharing my code, please review my code 

////////////////////////////NativeMobileSDKBridge/////////////////////////////////////
   @ReactMethod
    private fun toggleScreenCapture() {

        mediaProjectionManager = currentActivity?.getSystemService(Context.MEDIA_PROJECTION_SERVICE) as MediaProjectionManager

        getCurrentActivity()?.startActivityForResult(
                mediaProjectionManager?.createScreenCaptureIntent(),
                    SCREEN_CAPTURE_REQUEST_CODE
            )
    }
      fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
          //mReactInstanceManager.onActivityResult(requestCode, resultCode, data)
        if (SCREEN_CAPTURE_REQUEST_CODE == requestCode) {
            if (resultCode != Activity.RESULT_OK) {
                data?.let { startScreenShare(resultCode, it) }

               // Toast.makeText(currentActivity!!.applicationContext, "Screen share cannot work without permissions", Toast.LENGTH_LONG).show()

            } else {
                data?.let { startScreenShare(resultCode, it) }
            }
        }
    }
/////////////////////////////////ScreenCaptureService///////////////////////////////////////////

class ScreenCaptureService : Service() {
    private lateinit var notificationManager: NotificationManager

    private val CHANNEL_ID = "ScreenCaptureServiceChannelID"
    private val CHANNEL_NAME = "Screen Share"
    private val SERVICE_ID = 1

    override fun onCreate() {
        super.onCreate()

        notificationManager =
                applicationContext.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                    CHANNEL_ID,
                    CHANNEL_NAME,
                    NotificationManager.IMPORTANCE_DEFAULT
            )
            notificationManager.createNotificationChannel(channel)
        }

        startForeground(
                SERVICE_ID,
                NotificationCompat.Builder(this, CHANNEL_ID)
                        .setSmallIcon(R.mipmap.ic_launcher)
                        .setContentTitle(getString(R.string.screen_capture_notification_tile))
                        .setContentText(getText(R.string.screen_capture_notification_text))
                        .setPriority(NotificationCompat.PRIORITY_DEFAULT)
                        .build()
        )
        return START_STICKY
    }

    override fun onBind(intent: Intent?): IBinder? = null
}

**Comment by SIDDIQUISAZID** [comment]
Dear Support,

Thanks for your revert..!

Issue is when we're trying to call " Android naive code on in react native " is always giving a pop for start screen share the I click on start then its not working, I am sharing my code, please review my code

////////////////////////////NativeMobileSDKBridge/////////////////////////////////////
@ReactMethod
private fun toggleScreenCapture() {

mediaProjectionManager = currentActivity?.getSystemService(Context.MEDIA_PROJECTION_SERVICE) as MediaProjectionManager

getCurrentActivity()?.startActivityForResult(
mediaProjectionManager?.createScreenCaptureIntent(),
SCREEN_CAPTURE_REQUEST_CODE
)
}
fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
//mReactInstanceManager.onActivityResult(requestCode, resultCode, data)
if (SCREEN_CAPTURE_REQUEST_CODE == requestCode) {
if (resultCode != Activity.RESULT_OK) {
data?.let { startScreenShare(resultCode, it) }

// Toast.makeText(currentActivity!!.applicationContext, "Screen share cannot work without permissions", Toast.LENGTH_LONG).show()

} else {
data?.let { startScreenShare(resultCode, it) }
}
}
}
/////////////////////////////////ScreenCaptureService///////////////////////////////////////////

class ScreenCaptureService : Service() {
private lateinit var notificationManager: NotificationManager

private val CHANNEL_ID = "ScreenCaptureServiceChannelID"
private val CHANNEL_NAME = "Screen Share"
private val SERVICE_ID = 1

override fun onCreate() {
super.onCreate()

notificationManager =
applicationContext.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
}

override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
val channel = NotificationChannel(
CHANNEL_ID,
CHANNEL_NAME,
NotificationManager.IMPORTANCE_DEFAULT
)
notificationManager.createNotificationChannel(channel)
}

startForeground(
SERVICE_ID,
NotificationCompat.Builder(this, CHANNEL_ID)
.setSmallIcon(R.mipmap.ic_launcher)
.setContentTitle(getString(R.string.screen_capture_notification_tile))
.setContentText(getText(R.string.screen_capture_notification_text))
.setPriority(NotificationCompat.PRIORITY_DEFAULT)
.build()
)
return START_STICKY
}

override fun onBind(intent: Intent?): IBinder? = null
}
![processed](https://user-images.githubusercontent.com/20954375/113548377-0d7d7880-960d-11eb-81f5-718bca8fa3ee.jpeg)

**Comment by SIDDIQUISAZID** [comment]
Dear Support,

Please help me. and  please review my code
