### ISSUE TITLE
Issue in iOS demo code on xcode 112

### ISSUE THREAD

**Issue by Inshad-Ansari** [aws-samples/amazon-chime-react-native-demo#68]
Hi , 
Everyone hope you are doing well,

I am trying to run a demo app on Xcode 12 but it throws an error ex: /Users/apple/Desktop/calling/ios/RNDemo.xcodeproj Building for iOS, but the linked and embedded framework 'AmazonChimeSDKMedia.framework' was built for iOS + iOS Simulator. form framework so please guide me, how I can run on Xcode 12 as I have followed all the steps of the demo. please see the screenshot attached below: [
<img width="1044" alt="Screenshot 2021-03-29 at 9 17 10 AM" src="https://user-images.githubusercontent.com/27268609/112784552-97f33480-906f-11eb-859c-e0f6c326e010.png">
](url)

**Comment by zhinang-amazon** [comment]
Hi @Inshad-Ansari ,
Looking at your screenshot, you should 
1. Remove `AmazonChimeSDK.framework` and `AmazonChimeSDKMedia.framework`.
2. Change `AmazonChimeSDK.xcframework` and `AmazonChimeSDKMedia.xcframework` to `Embed & Sign`

Let us know if this fixes your issue.

**Comment by Inshad-Ansari** [comment]
Thanks for your support , issue was resolved
