### ISSUE TITLE
What should be the aspect ratio if splitting mobile screen based on below screenshots?

### ISSUE THREAD

**Issue by SuhailBt** [aws-samples/amazon-chime-react-native-demo#70]
I am trying to split the entire mobile screen as per the attendees in the call. Attaching screenshots for the same

![Screenshot from 2021-03-31 16-23-49](https://user-images.githubusercontent.com/65166275/113133670-8b243b80-923d-11eb-96ec-1b0da1e31524.png)
![Screenshot from 2021-03-31 16-20-06](https://user-images.githubusercontent.com/65166275/113133512-5ca66080-923d-11eb-93f3-aebbe98c7286.png)
![Screenshot from 2021-03-31 16-20-08](https://user-images.githubusercontent.com/65166275/113133515-5dd78d80-923d-11eb-87b1-54f82e177875.png)

**Comment by hokyungh** [comment]
Hi you should be able to change aspect ratio for your need. We don't have recommendation on UI. You might want to try different combination to see which one fits the best.

You can see [code](https://github.com/aws/amazon-chime-sdk-android/blob/master/app/src/main/java/com/amazonaws/services/chime/sdkdemo/adapter/VideoAdapter.kt#L63) which changes the aspect ratio.

React Native doesn't currently expose it, so you would need to make modification on [RNVideoViewManager](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/RNVideoViewManager.kt#L32) like mirror property to expose to react native.
