### ISSUE TITLE
Android suddenly crash on join meeting

### ISSUE THREAD

**Issue by IronTony** [aws-samples/amazon-chime-react-native-demo#73]
Hi,

I found a bug in the current SDK for iOS and Android (the one used for the example), here the links:
general -> https://github.com/aws/amazon-chime-sdk-ios/issues/200
iOS -> https://github.com/aws/amazon-chime-sdk-ios/pull/202
Android -> https://github.com/aws/amazon-chime-sdk-android/pull/208

I have upgraded to the latest iOS SDK and everything works fine, but when I do the same on Android, and if I try to join a meeting call, the app crashes without any error in console on Android Studio.

Any help?

**Comment by dylonChime** [comment]
Hi @IronTony, do you mind providing the following info?

 - Device: [e.g. Pixel3]
 - OS: [e.g. Android 10]
 - Version amazon-chime-sdk: [e.g. 0.4.0]
 - Version amazon-chime-sdk-media: [e.g. 0.4.0]
 - Can you reproduce this in the demo app?
 - Full crash logs.

**Comment by IronTony** [comment]
sorry guys had some problems, I hope to complete the infos, but here the following:

- Device: Huawei P30, Samsung Galaxy j6
- OS: Android 10
- Version amazon-chime-sdk: 0.11.3
- Version amazon-chime-sdk-media: 0.11.2

The other two I try to reproduce and attach the logs within next days.
Thank you

**Comment by hokyungh** [comment]
@IronTony Any logs you found?

**Comment by IronTony** [comment]
@hokyungh sorry guys, I had some problem in r.l. and didn't had the time for a repro. Try to do this weekend! 🙏
