### ISSUE TITLE
Is there a way to neatly pack these sdk so that we don't get these sort of errors?

### ISSUE THREAD

**Issue by bm181354** [aws-samples/amazon-chime-react-native-demo#74]
Since, I dragged and drop all the SDK files like instructed. These are causing GitHub issue. 

I get following error: File ios/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia is 235.79 MB; this exceeds GitHub's file size limit of 100.00 MB

Any help will be appreciated!!

**Comment by dylonChime** [comment]
Hi @bm181354, thanks for your interest in our SDK!

We don't recommend pushing the frameworks to your repository. They should be [ignored by git](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/.gitignore#L24). Double check your .gitignore file has "*.framework" listed.

Let me know if that answers your question.

**Comment by dylonChime** [comment]
I see you've also found the [feature request](https://github.com/aws/amazon-chime-sdk-ios/issues/59) we have for Cocoapods support.

**Comment by bm181354** [comment]
> Hi @bm181354, thanks for your interest in our SDK!
> 
> We don't recommend pushing the frameworks to your repository. They should be [ignored by git](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/.gitignore#L24). Double check your .gitignore file has "*.framework" listed.
> 
> Let me know if that answers your question.

On an ideally situation that's the standard protocol but we have CI/CD that gets trigger when we push our code into GitHub. If it has npm packages or pod/gradle package, we'll just ignore all frameworks. Since, we don't have npm, cocoapods nor Gradle. We need to push everything. These frameworks are must on appcenter for creating builds and deploying into app stores. We are not archiving and building anything locally.

That being said I found a temporary fix for now. **AmazonChimeSDKMedia** newer version has lower file size. I'm planing to use that.

Honestly, it will great to have all npm package, cocoapods and gradle packages for aws chime. It shouldn't take that much of time to official release this to be real.

**Comment by dylonChime** [comment]
Hi @bm181354,

I'm glad you found a workaround. Yes, I agree the process right now is not ideal.

Cocoapods support is a highly requested feature, so hopefully we can provide this sometime in the near future.
