### ISSUE TITLE
Messaging Session and Observers

### ISSUE THREAD

**Issue by kvntzn** [aws-samples/amazon-chime-react-native-demo#76]
I tried using this [amazon-chime-sdk-js](https://www.npmjs.com/package/amazon-chime-sdk-js#starting-a-messaging-session) on a react native environment, However when I start the default messaging session it shows an error related  to a browser. 

Now I am trying to work on adding a messaging session  and adding observer same with [this](https://www.npmjs.com/package/amazon-chime-sdk-js#starting-a-messaging-session). However I couldn't add it because they're not existing on this package `com.amazonaws.services.chime.sdk`

A solution I can think of is adding the messaging part with native modules not only the meeting part.
Another alternative is an updated/new npm that would work with the messaging in react native as its working fine for the browsers.

Any help would be greatly appreciated.

**Comment by linsang21** [comment]
Hi, thanks for reaching out. Adding messaging functionality on Android/iOS SDK is one of our planned work, we will update once more info is available.

I understand that amazon-chime-sdk-js was designed for browser app development, which sometimes doesn't  work perfectly on RN. So at the meantime you could consider a self implementation to unblock your work, similar to amazon-chime-sdk-js's implementation. The high level logics are not too complicated, basically you need a [websocket](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/messagingsession/DefaultMessagingSession.ts#L32) to get connect to the messaging session and observers to [listen to the events](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/messagingsession/DefaultMessagingSession.ts#L86) from the websocket connection, which messages will be sent by that. Details need to pay attention are [signing the websocket connect request](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/messagingsession/DefaultMessagingSession.ts#L121) and [converting the event to message](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/messagingsession/DefaultMessagingSession.ts#L148).
