### ISSUE TITLE
Unknown type name 

### ISSUE THREAD

**Issue by ceremonious** [aws-samples/amazon-chime-react-native-demo#80]
**Describe the bug**
I followed the steps described in the readme to integrate AWS Chime into an existing React Native project, however I'm unable to build my project in XCode. I'm getting an "Unknown type name" build error any time I try to import / use a class from AWSChimeSDK while building my iOS application. 

**To Reproduce**
1. Download the `AmazonChimeSDK.framework` and `AmazonChimeSDKMedia.framework` binary files and put them in my iOS root directory.
2. Include the provided iOS bridge files in my React Native project (MeetingObserver, NativeMobileSDKBridge, RNVideoView, RNVideoViewManager)
3. Follow these [instructions](https://github.com/aws/amazon-chime-sdk-ios/blob/master/README.md#setup) to properly configure XCode
4. Attempt to build the app

**Expected behavior**
The app should build without errors

**Screenshots**
<img width="1199" alt="Screen Shot 2021-05-17 at 11 48 13 PM" src="https://user-images.githubusercontent.com/6596130/118604756-6262f180-b76a-11eb-9789-36196039ea0a.png">

**Test environment Info:**
 - Device: Macbook Pro (with M1 chip)
 - OS: macOS Big Sur
 - Version amazon-chime-sdk: Both 0.12.2 and most recent
 - Version amazon-chime-sdk-media: Both 0.8.2 and most recent
 - XCode: 12.5

I have been working on this project on a 2017 Macbook Pro without any errors, however I recently switched to a new M1 Macbook. I'm not sure if the M1 could be causing the issues, or if moving the project to a new development machine caused something to get misconfigured somewhere. Do you have any insight into why the Objective C files are unable to properly see the classes from the imported framework?

**Comment by zhinang-amazon** [comment]
Hi @ceremonious,

The issue is indeed the M1 chip. Our iOS SDK currently does not support simulator with arm64 architecture, which is the case for simulators running on M1 machine. Adding support for arm64 simulator is on our roadmap and I will mark this as enhancement until then. In the mean time, the workaround would be building onto a physical device, or building from a Mac with Intel chip.

Sorry for the inconvenience.

**Comment by Beos24vi** [comment]
any update on this? @ceremonious
