### ISSUE TITLE
Video Get Freeze and sometimes video tiles is not shown 

### ISSUE THREAD

**Issue by pradipDevG** [aws-samples/amazon-chime-react-native-demo#81]
i used two component 
One for participant one for active speaker .. if active speaker is detected and displayed the videos on participant list get freezes (paused ). Sometimes the video just went black and doesnot resume and active speaker view doesn't show any video  but can hear audio. this issues is so frequent ? how do i resolve it ?
![Screen Shot 2021-06-04 at 12 04 00](https://user-images.githubusercontent.com/55678848/120754984-1adfb200-c52d-11eb-85da-2e188c309cf9.png)

**Comment by dylonChime** [comment]
Hi @pradipDevG, can you provide the following info?

Device: [e.g. Pixel3]
OS: [e.g. Android 10]
Version amazon-chime-sdk: [e.g. 0.4.0]
Version amazon-chime-sdk-media: [e.g. 0.4.0]
Can you reproduce this in the demo app?
