### ISSUE TITLE
Audio is off in iOS when app goes into background/sleep.

### ISSUE THREAD

**Issue by prashanthacharyam** [aws-samples/amazon-chime-react-native-demo#82]
**Describe the bug**
Audio is off in iOS when app goes into background/sleep. On returning back to app it works.
No such issue on Android

**Expected behavior**
Audio to not go off when app is in background and meeting in progress.

**Test environment Info (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 14.4
 - Version amazon-chime-sdk: 0.16.2
 - Version amazon-chime-sdk-media: 0.11.3

**Comment by ziyiz-amzn** [comment]
Thank you for reporting @prashanthacharyam . 

I will take a look and update.

**Comment by prashanthacharyam** [comment]
Is there an example which uses objective c since the react native examples are in objective c.

**Comment by zhinang-amazon** [comment]
Hi @prashanthacharyam,

Sorry that we do not have an objective c example at this point.

**Comment by prashanthacharyam** [comment]
I ended up enabling background audio for the app which solves my issue. Callkit integration was not needed.

**Comment by zhinang-amazon** [comment]
Hi @prashanthacharyam, I'm glad that worked for you. Background audio is necessary indeed. However also keep in mind that without CallKit integration, your audio/video call can be terminated when there is a phone call or other CallKit enabled call from another application

**Comment by prashanthacharyam** [comment]
Hi, ok. It should be fine for us now.
