### ISSUE TITLE
How to identify the speaker in the meeting and bring his video on full screen

### ISSUE THREAD

**Issue by vats05** [aws-samples/amazon-chime-react-native-demo#83]
**Describe the bug**
Team, we are using Chime SDK in Education sector. In the Meeting id, we have a list of all users joined the meeting id. 

We need to :
1. How to by default get the teacher video on the full screen? As all participants in the meeting ID is in a list. 
2. All students have small video tiles, on our mobile screen UI. How to automatically identify which student is speaking and bring focus on that particular video tile (like it happens in Google Meet). So that we can click on that video tile and bring it on the main full screen. 
3. How to Pin a particular person to bring his/her video in full screen. 

Please help us with whatever resources you have, so that we can create a better User experience on our Mobile app using the Chime SDK. Similar to what we have in Google Meet.

**Comment by prashanthacharyam** [comment]
You should use the ActiveSpeakerObserver methods (onActiveSpeakerDetected) to identify the current active speaker and show that use in centre.

**Comment by ziyiz-amzn** [comment]
A few resources/examples may help you to learn more. @vats05 

1. Chime JS SDK has an sample app for online classroom built with Electron and React - [Virtual Classroom](https://aws.amazon.com/blogs/business-productivity/building-a-virtual-classroom-application-using-the-amazon-chime-sdk/). It covers most of your use cases in the realm of education.
2. Active speaker based policy on iOS [example](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/video_pagination.md), more helpful resources can be found under /guides directory. 
3. Active speaker based policy on Android [example](https://github.com/aws/amazon-chime-sdk-android/blob/master/guides/video_pagination.md), more helpful resources can be found under /guides directory. 

Hope it will help.
