### ISSUE TITLE
Sdk folder is missing in "amazon-chime-react-native-demo/android/app/src/main/java/com/amazonaws/services/chime"

### ISSUE THREAD

**Issue by ShaikAnsar1568** [aws-samples/amazon-chime-react-native-demo#86]
**Describe the bug**
Sdk folder is missing in "amazon-chime-react-native-demo/android/app/src/main/java/com/amazonaws/services/chime"
which causes an unresolved reference error when i try to place .kt files as described in the 4 th point of integrating into existing react native project.

when i place meetingobservers.kt file, it actually has import com.sdk.meetings.audiovideo.AttendeeInfo

So, the path to sdk misses and iam getting the error. 
Can you please provide sdk folder.

**Comment by zhinang-amazon** [comment]
Hi @ShaikAnsar1568,
Have you followed step 1 to download, and copy the `amazon-chime-sdk` and `amazon-chime-sdk-media` aar files to your project?

**Comment by ShaikAnsar1568** [comment]
@zhinang-amazon, Yes. I have downloaded the  amazon-chime-sdk and amazon-chime-sdk-media aar files to app/libs
