### ISSUE TITLE
i have cloned the react native chime sdk demo and deployed the chime-sdk-js to server. I want to find out the active speaker. what changes i will have to make and in which files to achieve this. Kindly help me out

### ISSUE THREAD

**Issue by rnqayush** [aws-samples/amazon-chime-react-native-demo#87]

**Comment by zhinang-amazon** [comment]
Hi @rnqayush,

There will be changes needed on both native iOS/Android and also react native. I will take iOS as example and you will find similar files and APIs on Android.

1. Update `ios/RNDemo/MeetingObservers.h` and `.m` to implement `ActiveSpeakerObserver` and send an event in the `activeSpeakerDidDetectWithAttendeeInfo:(NSArray<AttendeeInfo *> * _Nonnull)attendeeInfo` method
2. Register the activeSpeaker observer [here](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/NativeMobileSDKBridge.m#L193)
3. Add a listener in `src/containers/Meeting.js` to listen to the event sent in step 1 and capture the active speakers and and your own handling logic 

Let us know if you have more questions on this

**Comment by rnqayush** [comment]
thank you @zhinang-amazon , 
 It would be grateful if you could tell it for android too. i have applied the code for active speaker in NativeMobileSDKBridge.kt but getting error shown below.
![activespeaker1](https://user-images.githubusercontent.com/74084740/123586967-2c9e3780-d803-11eb-8196-72890e0d7ce5.png)

**Comment by rnqayush** [comment]
![activespeaker1](https://user-images.githubusercontent.com/74084740/123587049-4fc8e700-d803-11eb-8fcb-af76d825ed01.png)

**Comment by rnqayush** [comment]
and this is code i applied.
![activespeaker2](https://user-images.githubusercontent.com/74084740/123587282-b0f0ba80-d803-11eb-8364-d01b2d85d4c8.png)

**Comment by hokyungh** [comment]
Hi @rnqayush , could you check if you have imported it by `import com.amazonaws.services.chime.sdk.meetings.audiovideo.audio.activespeakerdetector.ActiveSpeakerObserver` same for all other classes. 
`import com.amazonaws.services.chime.sdk.meetings.audiovideo.AttendeeInfo`
`import com.amazonaws.services.chime.sdk.meetings.audiovideo.audio.activespeakerpolicy.DefaultActiveSpeakerPolicy`
?

**Comment by rnqayush** [comment]
thanks @zhinang-amazon , it was import issue and got resolved after it

**Comment by rnqayush** [comment]
@zhinang-amazon , I have implemented active speaker in my mobile app and working fine for mobile but when I am joining same meeting with web it isn't detecting the active speaker of web.

**Comment by dylonChime** [comment]
Hi @rnqayush, Could you provide more details on how you tested the active speaker between mobile and web? When you say web, are you referring to the JS SDK? Is active speaker detected between mobile and mobile? How did you confirm the web client is in the same meeting? Are you receiving any ActiveSpeaker callbacks at all? Are you receiving any other callbacks from web? Do you have logs from mobile side and web you can share?

**Comment by rnqayush** [comment]
@dylonChime thanks for your reply. By saying web I was referring to Js sdk. 
I have checked the attendees joining and active speaker with the Log.i ()
![activeS1](https://user-images.githubusercontent.com/74084740/124227229-efe67f00-db27-11eb-882b-c432bccf5a6e.png)

**Comment by rnqayush** [comment]
Actually my microphone was not working last time I have tested it again and now its working correctly as expected. I apologize for this mistake.
