### ISSUE TITLE
RNVideoView.h and RNVideoView.m UI component are not found in the demo

### ISSUE THREAD

**Issue by youssefhaitham-callvita** [aws-samples/amazon-chime-react-native-demo#88]
**Describe the bug**
I am trying to integrate the demo with my application as described in the steps mentioned in the readme file. It was mentioned that we need to copy some files from the demo to the app, all can be found except for RNVideoView.h and RNVideoView.m in ios. Will this affect the demo on ios ? 

It is working fine on android but I did not try it in ios yet.

**Comment by zhinang-amazon** [comment]
Hi @youssefhaitham-callvita,
It will not affect the demo. That class is replaced by a class provided in the iOS SDK.
I will update our README to remove the reference.
Thanks for catching that.
