### ISSUE TITLE
Freeze screen

### ISSUE THREAD

**Issue by SIDDIQUISAZID** [aws-samples/amazon-chime-react-native-demo#89]
Whenever I am clicking on "Screen" for full screen and for hiding the tiles then the video goes freeze. And when again I click on "screen" to see the tiles then the video starts to play

this is code please help me!

<SafeAreaView style={{ flex: 1, backgroundColor: "#f7f6fb" }}>
            <KeyboardAvoidingView style={{ flex: 1 }}>
              <View
                style={{
                  maxHeight: height,
                  minHeight: height,
                  backgroundColor: "gray",
                }}
              >
                {this.state.videoTiles.length > 0 ? (
                  <RNVideoRenderView
                    style={{
                      ...styles.video,
                      height: height,
                    }}
                    key={teacherfirst}
                    tileId={teacherfirst}
                    mirror={true}
                  />
                ) : null}
                <View
                  style={{
                    flexDirection: "row",
                    alignItems: "center",
                    width: 110,
                    position: "absolute",
                    top: width / 10,
                    right: width / 20,

                    justifyContent: "space-around",
                  }}
                >
                  <View
                    style={{
                      // alignSelf: "flex-end",
                      backgroundColor: "#F74B5B",
                      height: 40,
                      width: 70,
                      justifyContent: "center",
                      alignItems: "center",
                      borderRadius: 5,
                      marginEnd: 20,
                    }}
                  >
                    <Text style={{ color: "#fff" }}>Live</Text>
                  </View>
                  <TouchableOpacity onPress={() => this.speeker()}>
                    <Image
                      style={{ height: 20, width: 20 }}
                      source={
                        this.state.isSpeekerOff ? speaker_off : speaker_on
                      }
                      resizeMode="contain"
                    />
                  </TouchableOpacity>
                </View>

                <View style={{ position: "absolute", bottom: width / 10 }}>
                  <View
                    style={{
                      width: width,

                      flexDirection: "row",
                    }}
                  >
                    <FlatList
                      style={{ width: "100%" }}
                      contentContainerStyle={{ width: "90%" }}
                      data={userList}
                      horizontal={true}
                      renderItem={({ item }) => (
                        <TouchableOpacity
                          onPress={() => {
                            if (item.extra) {
                              this.setState({
                                modalVisible: true,
                              });
                            }
                          }}
                          style={{
                            marginLeft: 10,
                            height: 40,
                            width: 40,
                            borderRadius: 20,
                            justifyContent: "center",
                            alignItems: "center",
                            borderWidth: 1,
                            borderColor: "#fff",
                          }}
                        >
                          {!item.extra ? (
                            <Image
                              style={{
                                height: 40,
                                width: 40,
                                borderRadius: 20,
                              }}
                              source={{ uri: item.profilePic }}
                            />
                          ) : (
                            <Text style={{ color: "#fff" }}>
                              +{this.state.userList.length - 3}
                            </Text>
                          )}
                        </TouchableOpacity>
                      )}
                    />
                  </View>
                  <View
                    style={{
                      position: "absolute",
                      maxHeight: 150,
                      bottom: this.state.bottomPadding
                        ? 200 + this.state.bottomPadding
                        : 350,
                    }}
                  >
                    <FlatList
                      style={[styles.list]}
                      ref={(c) => {
                        this.flatList = c;
                      }}
                      data={this.state.messagesList}
                      inverted
                      extraData={this.state}
                      selected={this.state.selected}
                      onEndReached={({ distanceFromEnd }) => {
                        if (distanceFromEnd > 0) {
                          // this.handleMoreOrders();
                        }
                      }}
                      onEndReachedThreshold={0.5}
                      keyExtractor={(item, index) => index.toString()}
                      // keyExtractor={item => item.id}
                      renderItem={({ item }) => (
                        <View
                          style={{
                            flexDirection: "row",
                            marginTop: 5,
                          }}
                        >
                          <View>
                            <Image
                              style={{
                                height: 40,
                                width: 40,
                                borderRadius: 20,
                              }}
                              source={{
                                uri: item.senderData.profilePic,
                              }}
                            />
                          </View>
                          <View style={{ marginLeft: 10 }}>
                            <Text style={{ color: "#fff" }}>
                              {item.senderData.firstName}{" "}
                              {item.senderData.lastName}
                            </Text>
                            <Text style={{ color: "#fff" }}>
                              {item.message}
                            </Text>
                          </View>
                        </View>
                      )}
                    />
                  </View>
                  <View style={{}}>
                    {isTileViewShow ? (
                      <View
                        style={{
                          width: width,
                          height: 100,
                        }}
                      >
                        <FlatList
                          style={{ width: "100%" }}
                          contentContainerStyle={{ width: "90%" }}
                          data={uniqueChars}
                          horizontal={true}
                          renderItem={({ item, index }) => (
                            <View style={{ marginLeft: 10 }}>
                              <TouchableOpacity
                                onPress={() => this.clickTiles(index)}
                              >
                                <RNVideoRenderView
                                  style={{
                                    ...styles.video,
                                    width: 80,
                                    height: 80,
                                    borderRadious: 10,
                                  }}
                                  key={item}
                                  tileId={item}
                                  mirror={true}
                                />
                              </TouchableOpacity>
                            </View>
                          )}
                        />
                      </View>
                    ) : (
                      <View>
                        <Text>No videos</Text>
                      </View>
                    )}
                  </View>

                  <View
                    style={{
                      width: width,
                      height: 50,
                      flexDirection: "row",
                    }}
                  >
                    <View
                      style={{
                        width: (width - 30) / 2,
                        borderRadius: 10,
                        borderWidth: 1,
                        borderColor: "#fff",
                        height: 50,
                        marginLeft: 10,
                        justifyContent: "center",
                      }}
                    >
                      <TextInput
                        multiline={true}
                        style={{ paddingLeft: 15, marginTop: 5 }}
                        value={this.state.chatMessage}
                        onChangeText={(chatMessage) =>
                          this.setState({
                            chatMessage: chatMessage,
                          })
                        }
                        onFocus={() => {
                          if (Platform.OS == "ios") {
                            this.setState({
                              bottomPadding: 350,
                            });
                          }
                        }}
                        onBlur={() => {
                          if (Platform.OS == "ios") {
                            this.setState({
                              bottomPadding: 0,
                            });
                          }
                        }}
                        placeholderTextColor="#fff"
                        style={{
                          width: (width - 30) / 2,
                          color: "#fff",
                        }}
                        placeholder="Comment"
                      />
                    </View>
                    <View
                      style={{
                        flexDirection: "row",
                        width: (width - 30) / 2,
                        height: 50,
                        alignItems: "center",
                        justifyContent: "space-between",
                        marginLeft: 10,
                      }}
                    >
                      <TouchableOpacity onPress={() => this.send()}>
                        <Image
                          style={{ height: 30, width: 30 }}
                          source={send}
                        />
                      </TouchableOpacity>
                      <MuteButton
                        muted={currentMuted}
                        onPress={() => NativeFunction.setMute(!currentMuted)}
                      />
                      <CameraButton
                        disabled={this.state.selfVideoEnabled}
                        onPress={() =>
                          NativeFunction.setCameraOn(
                            !this.state.selfVideoEnabled
                          )
                        }
                      />
                      <TouchableOpacity
                        onPress={() => {
                          NativeFunction.rotateCamera();
                        }}
                      >
                        <Image
                          style={{ height: 30, width: 30 }}
                          source={rotatecamera}
                        />
                      </TouchableOpacity>
                      <TouchableOpacity
                        onPress={() => {
                          this.meetingStopOrLeave();
                        }}
                      >
                        <Image
                          style={{ height: 30, width: 30 }}
                          source={cutcall}
                        />
                      </TouchableOpacity>
                    </View>
                  </View>
                </View>
              </View>
            </KeyboardAvoidingView>

           
          </SafeAreaView>

**Comment by zhinang-amazon** [comment]
Hi @SIDDIQUISAZID,
Is your `this.clickTiles(index)}` supposed to handle to full screen logic? Do you mind showing what it does?
Are you creating a new `RNVideoRenderView` or resizing existing one?
If you are creating a new one, you need to unbind the video from the previous tile and bind the full screen one. 
Look at this [use case](https://github.com/aws/amazon-chime-sdk-android#use-case-13-view-remote-videos) in our Android README

**Comment by SIDDIQUISAZID** [comment]
hi 
yes i am doing unbind,
share my unbind code please check 

thank you 


 componentWillUnmount() {
    if (this.onAttendeesJoinSubscription) {
      this.onAttendeesJoinSubscription.remove();
    }
    if (this.onAttendeesLeaveSubscription) {
      this.onAttendeesLeaveSubscription.remove();
    }
    if (this.onAttendeesMuteSubscription) {
      this.onAttendeesMuteSubscription.remove();
    }
    if (this.onAttendeesUnmuteSubscription) {
      this.onAttendeesUnmuteSubscription.remove();
    }
    if (this.addActiveSpeakerObserver) {
      this.addActiveSpeakerObserver.remove();
    }

    if (this.onAddVideoTileSubscription) {
      this.onAddVideoTileSubscription.remove();
    }
    if (this.onRemoveVideoTileSubscription) {
      this.onRemoveVideoTileSubscription.remove();
    }
    if (this.onErrorSubscription) {
      this.onErrorSubscription.remove();
    }

    this.socket.emit("roomleavevideo", {
      senderId: this.props.loginUserData._id,
      roomId: this.props.meetingData._id,
      userData: {
        firstName: this.props.loginUserData.firstName,
        lastName: this.props.loginUserData.lastName,
        _id: this.props.loginUserData._id,
        profilePic: this.props.loginUserData.profilePic,
      },
    });
  }

**Comment by vats05** [comment]
Hi @zhinang-amazon , 

Looking forward for your suggestion to get this work? Thank you.

**Comment by vats05** [comment]
Hi @zhinang-amazon / AWS Team,

Please help here, we are struck on this issue. Thank you.

**Comment by hokyungh** [comment]
@vats05 I'll try to reproduce it and get back to you.

**Comment by vats05** [comment]
@hokyungh , Thank you.

**Comment by hokyungh** [comment]
@vats05 and @SIDDIQUISAZID I wasn't able to reproduce the issue. Do you mind sharing the following?

1. is it happening on iOS/Android?
2. Is there a minimal reproducible logic we can use to reproduce? The step I took was to make the video size bigger when clicked, which doesn't seem to pause other video tiles.

**Comment by alnlau** [comment]
Feel free to re-open if this is still an issue.
