### ISSUE TITLE
SDK error on iOS 13+

### ISSUE THREAD

**Issue by sapradev** [aws-samples/amazon-chime-react-native-demo#9]
Hi, i implemented Amazon Chime SDK in my react native project. It completely worked fine for iOS device of version 12. Also worked fine for simulator of version 13.4. But when i tried joining the meeting through iOS 13 or 13+ devices i got this error =>
Failed to start meeting, error: Error Domain=AmazonChimeSDK.MediaError Code=1 "(null)".
Using same code i was able to join meeting from iOS 12 device and iOS 13.4 simulator. But was not able to join from iOS 13 and 13+ devices. 
![Screenshot 2020-08-07 at 4 59 25 PM](https://user-images.githubusercontent.com/32849524/89641591-9f42b380-d8cf-11ea-8ce8-35cf15677388.png)

**Comment by anoop-sharma** [comment]
Are you able to solve it? I am also getting the same error.

**Comment by HarshMB** [comment]
I am also getting the same error in iOS 13.7

**Comment by anoop-sharma** [comment]
> I am also getting the same error in iOS 13.7

Are you testing on simulator or device?

**Comment by HarshMB** [comment]
In simulator

**Comment by HarshMB** [comment]
Hey it's working for me for iOS v13.7 in simulator. What is the problem is i am using mac mini so audio is disable automatically so it is showing this error, after that i connected my headphone and tried... it's working
