### ISSUE TITLE
switching the position of the RNVideoRenderView with same tileId results in lost video 

### ISSUE THREAD

**Issue by red62labs** [aws-samples/amazon-chime-react-native-demo#91]
**Describe the bug**

**To Reproduce**
- render video views in a list like so 
`            {filter(videoTiles, e => e.pos === vid)[0] ? (
                    <RNVideoRenderView
                      style={{
                        //aspectRatio: 7 / 9,
                        width: 250,
                        height: 250,
                      }}
                      tileId={
                        filter(videoTiles, e => e.pos === vid)[0]
                          ? filter(videoTiles, e => e.pos === vid)[0].tileId
                          : vid
                      }
                    />
                  ) : null}`
when changing the pos the view container in the video, you can see the position change but the video stream does not show up anymore .

**Expected behavior**
expected the video the go along with the new RNVideoRenderView 
**Logs**
my videotile object looks like this 
{tileId: 2, isLocal: false, isScreenShare: false, pos: 2}

i just click a button to change the pos, it changes but will not render the video after the initial position 

**Test environment Info (please complete the following information):**
 same behavior on simulator and device

**Comment by hokyungh** [comment]
Thank you for reporting. We'll try to reproduce it and get back to you.

**Comment by red62labs** [comment]
no need, I just noticed in the sample app you are not sending the attendeeId when sending the event onAddVideoTile. I added it to the event and now everything is working . organizing videos from attendeeId as it is consistent across all devices instead if by tileId. thanks.

**Comment by rnqayush** [comment]
@red62labs @hokyungh  I am facing the similar issue. kindly refer to this link to see the issue ( https://github.com/aws-samples/amazon-chime-react-native-demo/issues/94 ) . 
1- I tried using attendee Id for rendering of videos but its  showing an error that string is used rather than integer.
2- Kindly help me how can I use attendeeId in place of tileId to render my video.

**Comment by red62labs** [comment]
I used the attendee id to sort the video tiles in the order I wanted. If you have to use the tileId to render the video.
