### ISSUE TITLE
no audio through mic in ios

### ISSUE THREAD

**Issue by subhendukundu** [aws-samples/amazon-chime-react-native-demo#98]
Even tho the user's mic getting change to unmute from mute when user is clicking on the unmute button, attendees not able to hear the speaker. Can you please guide, what could be an issue? Or suggest what I need to make sure to have the audio (Not sure how to debug this)?

**Comment by zhinang-amazon** [comment]
Hi @subhendukundu,

Did you request microphone permission similar to [this](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/NativeMobileSDKBridge.m#L209)

And did you declare microphone usage in your info.plist similar to [this](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/ios/RNDemo/Info.plist#L40)

**Comment by zhinang-amazon** [comment]
Have you tried building onto physical device from your local xcode? Are you able to reproduce the issue that way?
Regarding your first change, I'm not sure where useEffect is, but you would want to make sure setMute is called after meeting session is started ([this event](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/utils/Bridge.js#L23)).

**Comment by subhendukundu** [comment]
Calling `NativeFunction.setMute(true);` in [this line](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/containers/Meeting.js#L34).

I am trying to run it on a physical device, will update you.

**Comment by zhinang-amazon** [comment]
Hi @subhendukundu,
I'm suspecting your setMute call is too early and audio session is not ready yet. Could you try listening to `OnMeetingStart ` event and call setMute there?

**Comment by ziyiz-amzn** [comment]
Closing it. Feel free to re-open if any question.
